// Code generated by glojure codegen. DO NOT EDIT.

package protocols

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
)

var aotDirectFn0 lang.FnFunc3
var aotRootVersion0 *lang.VarRootVersion
var aotDirectFn1 lang.FnFunc3
var aotRootVersion1 *lang.VarRootVersion

func init() {
	runtime.RegisterNSLoader("clojure/core/protocols", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "clojure.core.protocols"
func LoadNS() {
	sym_CollReduce := lang.NewSymbolUnchecked("CollReduce")
	sym_Datafiable := lang.NewSymbolUnchecked("Datafiable")
	sym_IKVReduce := lang.NewSymbolUnchecked("IKVReduce")
	sym_InternalReduce := lang.NewSymbolUnchecked("InternalReduce")
	sym_Navigable := lang.NewSymbolUnchecked("Navigable")
	sym_amap := lang.NewSymbolUnchecked("amap")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_chunk_DASH_first := lang.NewSymbolUnchecked("chunk-first")
	sym_chunk_DASH_next := lang.NewSymbolUnchecked("chunk-next")
	sym_chunked_DASH_seq_QMARK_ := lang.NewSymbolUnchecked("chunked-seq?")
	sym_class := lang.NewSymbolUnchecked("class")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_core_DOT_protocols := lang.NewSymbolUnchecked("clojure.core.protocols")
	sym_coll := lang.NewSymbolUnchecked("coll")
	sym_coll_DASH_reduce := lang.NewSymbolUnchecked("coll-reduce")
	sym_cons := lang.NewSymbolUnchecked("cons")
	sym_datafy := lang.NewSymbolUnchecked("datafy")
	sym_deref := lang.NewSymbolUnchecked("deref")
	sym_f := lang.NewSymbolUnchecked("f")
	sym_first := lang.NewSymbolUnchecked("first")
	sym_global_DASH_hierarchy := lang.NewSymbolUnchecked("global-hierarchy")
	sym_identical_QMARK_ := lang.NewSymbolUnchecked("identical?")
	sym_init := lang.NewSymbolUnchecked("init")
	sym_instance_QMARK_ := lang.NewSymbolUnchecked("instance?")
	sym_interface_DASH_or_DASH_naive_DASH_reduce := lang.NewSymbolUnchecked("interface-or-naive-reduce")
	sym_internal_DASH_reduce := lang.NewSymbolUnchecked("internal-reduce")
	sym_iter_DASH_reduce := lang.NewSymbolUnchecked("iter-reduce")
	sym_k := lang.NewSymbolUnchecked("k")
	sym_kv_DASH_reduce := lang.NewSymbolUnchecked("kv-reduce")
	sym_naive_DASH_seq_DASH_reduce := lang.NewSymbolUnchecked("naive-seq-reduce")
	sym_nav := lang.NewSymbolUnchecked("nav")
	sym_next := lang.NewSymbolUnchecked("next")
	sym_o := lang.NewSymbolUnchecked("o")
	sym_s := lang.NewSymbolUnchecked("s")
	sym_seq := lang.NewSymbolUnchecked("seq")
	sym_seq_DASH_reduce := lang.NewSymbolUnchecked("seq-reduce")
	sym_start := lang.NewSymbolUnchecked("start")
	sym_v := lang.NewSymbolUnchecked("v")
	sym_val := lang.NewSymbolUnchecked("val")
	kw_arglists := lang.NewKeyword("arglists")
	kw_coll_DASH_reduce := lang.NewKeyword("coll-reduce")
	kw_column := lang.NewKeyword("column")
	kw_datafy := lang.NewKeyword("datafy")
	kw_default := lang.NewKeyword("default")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_internal_DASH_reduce := lang.NewKeyword("internal-reduce")
	kw_kv_DASH_reduce := lang.NewKeyword("kv-reduce")
	kw_line := lang.NewKeyword("line")
	kw_multis := lang.NewKeyword("multis")
	kw_nav := lang.NewKeyword("nav")
	kw_ns := lang.NewKeyword("ns")
	kw_on_DASH_interface := lang.NewKeyword("on-interface")
	kw_private := lang.NewKeyword("private")
	kw_sigs := lang.NewKeyword("sigs")
	// var clojure.core.protocols/CollReduce
	var_clojure_DOT_core_DOT_protocols_CollReduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_CollReduce)
	// var clojure.core.protocols/Datafiable
	var_clojure_DOT_core_DOT_protocols_Datafiable := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_Datafiable)
	// var clojure.core.protocols/IKVReduce
	var_clojure_DOT_core_DOT_protocols_IKVReduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_IKVReduce)
	// var clojure.core.protocols/InternalReduce
	var_clojure_DOT_core_DOT_protocols_InternalReduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_InternalReduce)
	// var clojure.core.protocols/Navigable
	var_clojure_DOT_core_DOT_protocols_Navigable := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_Navigable)
	// var clojure.core.protocols/coll-reduce
	var_clojure_DOT_core_DOT_protocols_coll_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_coll_DASH_reduce)
	// var clojure.core.protocols/datafy
	var_clojure_DOT_core_DOT_protocols_datafy := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_datafy)
	// var clojure.core.protocols/interface-or-naive-reduce
	var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_interface_DASH_or_DASH_naive_DASH_reduce)
	// var clojure.core.protocols/internal-reduce
	var_clojure_DOT_core_DOT_protocols_internal_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_internal_DASH_reduce)
	// var clojure.core.protocols/iter-reduce
	var_clojure_DOT_core_DOT_protocols_iter_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_iter_DASH_reduce)
	// var clojure.core.protocols/kv-reduce
	var_clojure_DOT_core_DOT_protocols_kv_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_kv_DASH_reduce)
	// var clojure.core.protocols/naive-seq-reduce
	var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_naive_DASH_seq_DASH_reduce)
	// var clojure.core.protocols/nav
	var_clojure_DOT_core_DOT_protocols_nav := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_nav)
	// var clojure.core.protocols/seq-reduce
	var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce := lang.InternVarName(sym_clojure_DOT_core_DOT_protocols, sym_seq_DASH_reduce)
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/chunk-first
	var_clojure_DOT_core_chunk_DASH_first := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_first)
	// var clojure.core/chunk-next
	var_clojure_DOT_core_chunk_DASH_next := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_next)
	// var clojure.core/chunked-seq?
	var_clojure_DOT_core_chunked_DASH_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_chunked_DASH_seq_QMARK_)
	// var clojure.core/class
	var_clojure_DOT_core_class := lang.InternVarName(sym_clojure_DOT_core, sym_class)
	// var clojure.core/cons
	var_clojure_DOT_core_cons := lang.InternVarName(sym_clojure_DOT_core, sym_cons)
	// var clojure.core/deref
	var_clojure_DOT_core_deref := lang.InternVarName(sym_clojure_DOT_core, sym_deref)
	// var clojure.core/first
	var_clojure_DOT_core_first := lang.InternVarName(sym_clojure_DOT_core, sym_first)
	// var clojure.core/identical?
	var_clojure_DOT_core_identical_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_identical_QMARK_)
	// var clojure.core/instance?
	var_clojure_DOT_core_instance_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_instance_QMARK_)
	// var clojure.core/next
	var_clojure_DOT_core_next := lang.InternVarName(sym_clojure_DOT_core, sym_next)
	// var clojure.core/seq
	var_clojure_DOT_core_seq := lang.InternVarName(sym_clojure_DOT_core, sym_seq)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	var closed0 any
	{
		var tmp0 lang.ArityFn
		tmp0 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				tmp3 := lang.Apply0(v2)
				return tmp3
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				v3 := p2
				_ = v3
				return v3
			}),
			nil,
			nil,
			0,
		)
		closed0 = tmp0
	}
	var closed1 any
	{
		var tmp0 lang.ArityFn
		tmp0 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				tmp3, _ := lang.FieldOrMethod(v1, "Reduce")
				if reflect.TypeOf(tmp3).Kind() != reflect.Func {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("Reduce is not a function")))
				}
				tmp4 := lang.Apply1(tmp3, v2)
				return tmp4
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				v3 := p2
				_ = v3
				tmp4, _ := lang.FieldOrMethod(v1, "ReduceInit")
				if reflect.TypeOf(tmp4).Kind() != reflect.Func {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("ReduceInit is not a function")))
				}
				tmp5 := lang.Apply2(tmp4, v2, v3)
				return tmp5
			}),
			nil,
			nil,
			0,
		)
		closed1 = tmp0
	}
	var closed5 any
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			return nil
		})
		closed5 = tmp0
	}
	var closed6 any
	{
		var tmp0 lang.FnFunc3
		tmp0 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v1 := p0
			_ = v1
			v2 := p1
			_ = v2
			v3 := p2
			_ = v3
			return v3
		})
		closed6 = tmp0
	}
	var closed2 any
	{
		var tmp0 lang.ArityFn
		tmp0 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				tmp3 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce)
				tmp4 := lang.Apply2(tmp3, v1, v2)
				return tmp4
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				v3 := p2
				_ = v3
				tmp4 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce)
				tmp5 := lang.Apply3(tmp4, v1, v2, v3)
				return tmp5
			}),
			nil,
			nil,
			0,
		)
		closed2 = tmp0
	}
	var closed3 any
	{
		var tmp0 lang.ArityFn
		tmp0 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				tmp3 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce)
				tmp4 := lang.Apply2(tmp3, v1, v2)
				return tmp4
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				v3 := p2
				_ = v3
				tmp4 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce)
				tmp5 := lang.Apply3(tmp4, v1, v2, v3)
				return tmp5
			}),
			nil,
			nil,
			0,
		)
		closed3 = tmp0
	}
	var closed4 any
	{
		var tmp0 lang.ArityFn
		tmp0 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				tmp3 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce)
				tmp4 := lang.Apply2(tmp3, v1, v2)
				return tmp4
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v1 := p0
				_ = v1
				v2 := p1
				_ = v2
				v3 := p2
				_ = v3
				tmp4 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce)
				tmp5 := lang.Apply3(tmp4, v1, v2, v3)
				return tmp5
			}),
			nil,
			nil,
			0,
		)
		closed4 = tmp0
	}
	var closed7 any
	{
		var tmp0 lang.FnFunc3
		tmp0 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v1 := p0
			_ = v1
			v2 := p1
			_ = v2
			v3 := p2
			_ = v3
		recur_loop_2880:
			var tmp4 any
			{ // let
				// let binding "temp__0__auto__"
				tmp5 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp6 := lang.Apply1(tmp5, v1)
				var v7 any = tmp6
				_ = v7
				var tmp8 any
				if lang.IsTruthy(v7) {
					var tmp9 any
					{ // let
						// let binding "s"
						var v10 any = v7
						_ = v10
						var tmp11 any
						tmp12 := checkDerefVar(var_clojure_DOT_core_chunked_DASH_seq_QMARK_)
						tmp13 := lang.Apply1(tmp12, v10)
						if lang.IsTruthy(tmp13) {
							var tmp14 any
							{ // let
								// let binding "ret"
								tmp15 := checkDerefVar(var_clojure_DOT_core_chunk_DASH_first)
								tmp16 := lang.Apply1(tmp15, v10)
								tmp17, _ := lang.FieldOrMethod(tmp16, "ReduceInit")
								if reflect.TypeOf(tmp17).Kind() != reflect.Func {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("ReduceInit is not a function")))
								}
								tmp18 := lang.Apply2(tmp17, v2, v3)
								var v19 any = tmp18
								_ = v19
								var tmp20 any
								tmp21 := lang.IsReduced(v19)
								if lang.IsTruthy(tmp21) {
									tmp22 := checkDerefVar(var_clojure_DOT_core_deref)
									tmp23 := lang.Apply1(tmp22, v19)
									tmp20 = tmp23
								} else {
									tmp25 := checkDerefVar(var_clojure_DOT_core_chunk_DASH_next)
									tmp26 := lang.Apply1(tmp25, v10)
									var tmp24 any = tmp26
									var tmp27 any = v2
									var tmp28 any = v19
									v1 = tmp24
									v2 = tmp27
									v3 = tmp28
									goto recur_loop_2880
								}
								tmp14 = tmp20
							} // end let
							tmp11 = tmp14
						} else {
							tmp15 := var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce.RootVersion() == aotRootVersion0 && !var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce.IsMacro()
							var tmp16 any
							if !tmp15 {
								tmp16 = checkDerefVar(var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce)
							}
							var tmp17 any
							if tmp15 {
								tmp17 = aotDirectFn0(v10, v2, v3)
							} else {
								tmp17 = lang.Apply3(tmp16, v10, v2, v3)
							}
							tmp11 = tmp17
						}
						tmp9 = tmp11
					} // end let
					tmp8 = tmp9
				} else {
					tmp8 = v3
				}
				tmp4 = tmp8
			} // end let
			return tmp4
		})
		closed7 = tmp0
	}
	var closed8 any
	{
		var tmp0 lang.FnFunc3
		tmp0 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v1 := p0
			_ = v1
			v2 := p1
			_ = v2
			v3 := p2
			_ = v3
			var tmp4 any
			{ // let
				// let binding "cls"
				tmp5 := checkDerefVar(var_clojure_DOT_core_class)
				tmp6 := lang.Apply1(tmp5, v1)
				var v7 any = tmp6
				_ = v7
				// let binding "s"
				var v8 any = v1
				_ = v8
				// let binding "f"
				var v9 any = v2
				_ = v9
				// let binding "val"
				var v10 any = v3
				_ = v10
				for {
					var tmp11 any
					{ // let
						// let binding "temp__0__auto__"
						tmp12 := checkDerefVar(var_clojure_DOT_core_seq)
						tmp13 := lang.Apply1(tmp12, v8)
						var v14 any = tmp13
						_ = v14
						var tmp15 any
						if lang.IsTruthy(v14) {
							var tmp16 any
							{ // let
								// let binding "s"
								var v17 any = v14
								_ = v17
								var tmp18 any
								tmp19 := checkDerefVar(var_clojure_DOT_core_identical_QMARK_)
								tmp20 := checkDerefVar(var_clojure_DOT_core_class)
								tmp21 := lang.Apply1(tmp20, v17)
								tmp22 := lang.Apply2(tmp19, tmp21, v7)
								if lang.IsTruthy(tmp22) {
									var tmp23 any
									{ // let
										// let binding "ret"
										tmp24 := checkDerefVar(var_clojure_DOT_core_first)
										tmp25 := lang.Apply1(tmp24, v17)
										tmp26 := lang.Apply2(v9, v10, tmp25)
										var v27 any = tmp26
										_ = v27
										var tmp28 any
										tmp29 := lang.IsReduced(v27)
										if lang.IsTruthy(tmp29) {
											tmp30 := checkDerefVar(var_clojure_DOT_core_deref)
											tmp31 := lang.Apply1(tmp30, v27)
											tmp28 = tmp31
										} else {
											var tmp32 any = v7
											tmp34 := checkDerefVar(var_clojure_DOT_core_next)
											tmp35 := lang.Apply1(tmp34, v17)
											var tmp33 any = tmp35
											var tmp36 any = v9
											var tmp37 any = v27
											v7 = tmp32
											v8 = tmp33
											v9 = tmp36
											v10 = tmp37
											continue
										}
										tmp23 = tmp28
									} // end let
									tmp18 = tmp23
								} else {
									tmp24 := var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce.RootVersion() == aotRootVersion0 && !var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce.IsMacro()
									var tmp25 any
									if !tmp24 {
										tmp25 = checkDerefVar(var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce)
									}
									var tmp26 any
									if tmp24 {
										tmp26 = aotDirectFn0(v17, v9, v10)
									} else {
										tmp26 = lang.Apply3(tmp25, v17, v9, v10)
									}
									tmp18 = tmp26
								}
								tmp16 = tmp18
							} // end let
							tmp15 = tmp16
						} else {
							tmp15 = v10
						}
						tmp11 = tmp15
					} // end let
					tmp4 = tmp11
					break
				}
			} // end let
			return tmp4
		})
		closed8 = tmp0
	}
	// CollReduce
	{
		tmp0 := sym_CollReduce
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_class)
				tmp7 := lang.Apply1(tmp6, v4)
				return tmp7
			}),
			1,
		)
		// MultiFn coll-reduce
		tmp2 := lang.NewMultiFn("coll-reduce", tmp3, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var tmp4 lang.ArityFn
		tmp4 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v5 := args[0]
				_ = v5
				var v6 any = rest
				_ = v6
				tmp7 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp8 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp9 := lang.Apply2(tmp8, v5, v6)
				tmp10 := lang.Apply2(tmp7, closed0, tmp9)
				return tmp10
			}),
			1,
		)
		tmp2.AddMethod(nil, tmp4)
		tmp5 := reflect.TypeOf((*lang.IReduceInit)(nil)).Elem()
		var tmp6 lang.ArityFn
		tmp6 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v7 := args[0]
				_ = v7
				var v8 any = rest
				_ = v8
				tmp9 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp10 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp11 := lang.Apply2(tmp10, v7, v8)
				tmp12 := lang.Apply2(tmp9, closed1, tmp11)
				return tmp12
			}),
			1,
		)
		tmp2.AddMethod(tmp5, tmp6)
		tmp7 := reflect.TypeOf((*lang.LazySeq)(nil))
		var tmp8 lang.ArityFn
		tmp8 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v9 := args[0]
				_ = v9
				var v10 any = rest
				_ = v10
				tmp11 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp12 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp13 := lang.Apply2(tmp12, v9, v10)
				tmp14 := lang.Apply2(tmp11, closed2, tmp13)
				return tmp14
			}),
			1,
		)
		tmp2.AddMethod(tmp7, tmp8)
		tmp9 := reflect.TypeOf((*lang.Vector)(nil))
		var tmp10 lang.ArityFn
		tmp10 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v11 := args[0]
				_ = v11
				var v12 any = rest
				_ = v12
				tmp13 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp14 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp15 := lang.Apply2(tmp14, v11, v12)
				tmp16 := lang.Apply2(tmp13, closed3, tmp15)
				return tmp16
			}),
			1,
		)
		tmp2.AddMethod(tmp9, tmp10)
		tmp11 := reflect.TypeOf("")
		var tmp12 lang.ArityFn
		tmp12 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v13 := args[0]
				_ = v13
				var v14 any = rest
				_ = v14
				tmp15 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp16 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp17 := lang.Apply2(tmp16, v13, v14)
				tmp18 := lang.Apply2(tmp15, closed4, tmp17)
				return tmp18
			}),
			1,
		)
		tmp2.AddMethod(tmp11, tmp12)
		tmp1 := lang.NewAtom(lang.NewMap(kw_multis, lang.NewMap(kw_coll_DASH_reduce, tmp2), kw_on_DASH_interface, true, kw_sigs, lang.NewList(lang.NewList(sym_coll_DASH_reduce, lang.NewVector(sym_coll, sym_f), lang.NewVector(sym_coll, sym_f, sym_val)))))
		var_clojure_DOT_core_DOT_protocols_CollReduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_CollReduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(13), kw_column, int(14), kw_end_DASH_line, int(13), kw_end_DASH_column, int(23), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// Datafiable
	{
		tmp0 := sym_Datafiable
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_class)
				tmp7 := lang.Apply1(tmp6, v4)
				return tmp7
			}),
			1,
		)
		// MultiFn datafy
		tmp2 := lang.NewMultiFn("datafy", tmp3, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var tmp4 lang.ArityFn
		tmp4 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v5 := args[0]
				_ = v5
				var v6 any = rest
				_ = v6
				tmp7 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp8 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp9 := lang.Apply2(tmp8, v5, v6)
				tmp10 := lang.Apply2(tmp7, closed5, tmp9)
				return tmp10
			}),
			1,
		)
		tmp2.AddMethod(nil, tmp4)
		tmp1 := lang.NewAtom(lang.NewMap(kw_multis, lang.NewMap(kw_datafy, tmp2), kw_on_DASH_interface, true, kw_sigs, lang.NewList(lang.NewList(sym_datafy, lang.NewVector(sym_o), "return a representation of o as data (default identity)"))))
		var_clojure_DOT_core_DOT_protocols_Datafiable = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_Datafiable.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(188), kw_column, int(14), kw_end_DASH_line, int(188), kw_end_DASH_column, int(23), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// IKVReduce
	{
		tmp0 := sym_IKVReduce
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_class)
				tmp7 := lang.Apply1(tmp6, v4)
				return tmp7
			}),
			1,
		)
		// MultiFn kv-reduce
		tmp2 := lang.NewMultiFn("kv-reduce", tmp3, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		tmp1 := lang.NewAtom(lang.NewMap(kw_multis, lang.NewMap(kw_kv_DASH_reduce, tmp2), kw_on_DASH_interface, true, kw_sigs, lang.NewList(lang.NewList(sym_kv_DASH_reduce, lang.NewVector(sym_amap, sym_f, sym_init)))))
		var_clojure_DOT_core_DOT_protocols_IKVReduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_IKVReduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(181), kw_column, int(14), kw_end_DASH_line, int(181), kw_end_DASH_column, int(22), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// InternalReduce
	{
		tmp0 := sym_InternalReduce
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_class)
				tmp7 := lang.Apply1(tmp6, v4)
				return tmp7
			}),
			1,
		)
		// MultiFn internal-reduce
		tmp2 := lang.NewMultiFn("internal-reduce", tmp3, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var tmp4 lang.ArityFn
		tmp4 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v5 := args[0]
				_ = v5
				var v6 any = rest
				_ = v6
				tmp7 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp8 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp9 := lang.Apply2(tmp8, v5, v6)
				tmp10 := lang.Apply2(tmp7, closed6, tmp9)
				return tmp10
			}),
			1,
		)
		tmp2.AddMethod(nil, tmp4)
		tmp5 := reflect.TypeOf((*lang.IChunkedSeq)(nil)).Elem()
		var tmp6 lang.ArityFn
		tmp6 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v7 := args[0]
				_ = v7
				var v8 any = rest
				_ = v8
				tmp9 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp10 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp11 := lang.Apply2(tmp10, v7, v8)
				tmp12 := lang.Apply2(tmp9, closed7, tmp11)
				return tmp12
			}),
			1,
		)
		tmp2.AddMethod(tmp5, tmp6)
		tmp7 := reflect.TypeOf((*lang.Object)(nil)).Elem()
		var tmp8 lang.ArityFn
		tmp8 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v9 := args[0]
				_ = v9
				var v10 any = rest
				_ = v10
				tmp11 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp12 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp13 := lang.Apply2(tmp12, v9, v10)
				tmp14 := lang.Apply2(tmp11, closed8, tmp13)
				return tmp14
			}),
			1,
		)
		tmp2.AddMethod(tmp7, tmp8)
		tmp1 := lang.NewAtom(lang.NewMap(kw_multis, lang.NewMap(kw_internal_DASH_reduce, tmp2), kw_on_DASH_interface, true, kw_sigs, lang.NewList(lang.NewList(sym_internal_DASH_reduce, lang.NewVector(sym_seq, sym_f, sym_start)))))
		var_clojure_DOT_core_DOT_protocols_InternalReduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_InternalReduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(19), kw_column, int(14), kw_end_DASH_line, int(19), kw_end_DASH_column, int(27), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// Navigable
	{
		tmp0 := sym_Navigable
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_class)
				tmp7 := lang.Apply1(tmp6, v4)
				return tmp7
			}),
			1,
		)
		// MultiFn nav
		tmp2 := lang.NewMultiFn("nav", tmp3, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		tmp1 := lang.NewAtom(lang.NewMap(kw_multis, lang.NewMap(kw_nav, tmp2), kw_on_DASH_interface, true, kw_sigs, lang.NewList(lang.NewList(sym_nav, lang.NewVector(sym_coll, sym_k, sym_v), "return (possibly transformed) v in the context of coll and k (a key/index or nil),\ndefaults to returning v."))))
		var_clojure_DOT_core_DOT_protocols_Navigable = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_Navigable.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(200), kw_column, int(14), kw_end_DASH_line, int(200), kw_end_DASH_column, int(22), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// coll-reduce
	{
		tmp0 := sym_coll_DASH_reduce
		var tmp2 lang.ArityFn
		tmp2 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v3 := args[0]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_class)
				tmp6 := lang.Apply1(tmp5, v3)
				return tmp6
			}),
			1,
		)
		// MultiFn coll-reduce
		tmp1 := lang.NewMultiFn("coll-reduce", tmp2, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp7 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp8 := lang.Apply2(tmp7, v4, v5)
				tmp9 := lang.Apply2(tmp6, closed0, tmp8)
				return tmp9
			}),
			1,
		)
		tmp1.AddMethod(nil, tmp3)
		tmp4 := reflect.TypeOf((*lang.IReduceInit)(nil)).Elem()
		var tmp5 lang.ArityFn
		tmp5 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v6 := args[0]
				_ = v6
				var v7 any = rest
				_ = v7
				tmp8 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp9 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp10 := lang.Apply2(tmp9, v6, v7)
				tmp11 := lang.Apply2(tmp8, closed1, tmp10)
				return tmp11
			}),
			1,
		)
		tmp1.AddMethod(tmp4, tmp5)
		tmp6 := reflect.TypeOf((*lang.LazySeq)(nil))
		var tmp7 lang.ArityFn
		tmp7 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v8 := args[0]
				_ = v8
				var v9 any = rest
				_ = v9
				tmp10 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp11 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp12 := lang.Apply2(tmp11, v8, v9)
				tmp13 := lang.Apply2(tmp10, closed2, tmp12)
				return tmp13
			}),
			1,
		)
		tmp1.AddMethod(tmp6, tmp7)
		tmp8 := reflect.TypeOf((*lang.Vector)(nil))
		var tmp9 lang.ArityFn
		tmp9 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v10 := args[0]
				_ = v10
				var v11 any = rest
				_ = v11
				tmp12 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp13 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp14 := lang.Apply2(tmp13, v10, v11)
				tmp15 := lang.Apply2(tmp12, closed3, tmp14)
				return tmp15
			}),
			1,
		)
		tmp1.AddMethod(tmp8, tmp9)
		tmp10 := reflect.TypeOf("")
		var tmp11 lang.ArityFn
		tmp11 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v12 := args[0]
				_ = v12
				var v13 any = rest
				_ = v13
				tmp14 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp15 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp16 := lang.Apply2(tmp15, v12, v13)
				tmp17 := lang.Apply2(tmp14, closed4, tmp16)
				return tmp17
			}),
			1,
		)
		tmp1.AddMethod(tmp10, tmp11)
		var_clojure_DOT_core_DOT_protocols_coll_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_coll_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(17), kw_column, int(4), kw_end_DASH_line, int(17), kw_end_DASH_column, int(14), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// datafy
	{
		tmp0 := sym_datafy
		var tmp2 lang.ArityFn
		tmp2 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v3 := args[0]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_class)
				tmp6 := lang.Apply1(tmp5, v3)
				return tmp6
			}),
			1,
		)
		// MultiFn datafy
		tmp1 := lang.NewMultiFn("datafy", tmp2, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp7 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp8 := lang.Apply2(tmp7, v4, v5)
				tmp9 := lang.Apply2(tmp6, closed5, tmp8)
				return tmp9
			}),
			1,
		)
		tmp1.AddMethod(nil, tmp3)
		var_clojure_DOT_core_DOT_protocols_datafy = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_datafy.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(191), kw_column, int(4), kw_end_DASH_line, int(191), kw_end_DASH_column, int(9), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// interface-or-naive-reduce
	{
		tmp0 := sym_interface_DASH_or_DASH_naive_DASH_reduce
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			tmp6 := checkDerefVar(var_clojure_DOT_core_instance_QMARK_)
			tmp7 := reflect.TypeOf((*lang.IReduceInit)(nil)).Elem()
			tmp8 := lang.Apply2(tmp6, tmp7, v2)
			if lang.IsTruthy(tmp8) {
				tmp9, _ := lang.FieldOrMethod(v2, "ReduceInit")
				if reflect.TypeOf(tmp9).Kind() != reflect.Func {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("ReduceInit is not a function")))
				}
				tmp10 := lang.Apply2(tmp9, v3, v4)
				tmp5 = tmp10
			} else {
				tmp11 := var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce.RootVersion() == aotRootVersion1 && !var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce.IsMacro()
				var tmp12 any
				if !tmp11 {
					tmp12 = checkDerefVar(var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce)
				}
				var tmp13 any
				if tmp11 {
					tmp13 = aotDirectFn1(v2, v3, v4)
				} else {
					tmp13 = lang.Apply3(tmp12, v2, v3, v4)
				}
				tmp5 = tmp13
			}
			return tmp5
		})
		aotDirectFn0 = tmp1
		var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion0 = var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce.RootVersion()
		var_clojure_DOT_core_DOT_protocols_interface_DASH_or_DASH_naive_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_coll, sym_f, sym_val)), kw_doc, "Reduces via IReduceInit if possible, else naively.", kw_file, "clojure/core/protocols.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols), kw_end_DASH_column, int(32), kw_column, int(8), kw_line, int(68), kw_end_DASH_line, int(68), kw_private, true)
		})
	}
	// internal-reduce
	{
		tmp0 := sym_internal_DASH_reduce
		var tmp2 lang.ArityFn
		tmp2 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v3 := args[0]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_class)
				tmp6 := lang.Apply1(tmp5, v3)
				return tmp6
			}),
			1,
		)
		// MultiFn internal-reduce
		tmp1 := lang.NewMultiFn("internal-reduce", tmp2, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp7 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp8 := lang.Apply2(tmp7, v4, v5)
				tmp9 := lang.Apply2(tmp6, closed6, tmp8)
				return tmp9
			}),
			1,
		)
		tmp1.AddMethod(nil, tmp3)
		tmp4 := reflect.TypeOf((*lang.IChunkedSeq)(nil)).Elem()
		var tmp5 lang.ArityFn
		tmp5 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v6 := args[0]
				_ = v6
				var v7 any = rest
				_ = v7
				tmp8 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp9 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp10 := lang.Apply2(tmp9, v6, v7)
				tmp11 := lang.Apply2(tmp8, closed7, tmp10)
				return tmp11
			}),
			1,
		)
		tmp1.AddMethod(tmp4, tmp5)
		tmp6 := reflect.TypeOf((*lang.Object)(nil)).Elem()
		var tmp7 lang.ArityFn
		tmp7 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v8 := args[0]
				_ = v8
				var v9 any = rest
				_ = v9
				tmp10 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp11 := checkDerefVar(var_clojure_DOT_core_cons)
				tmp12 := lang.Apply2(tmp11, v8, v9)
				tmp13 := lang.Apply2(tmp10, closed8, tmp12)
				return tmp13
			}),
			1,
		)
		tmp1.AddMethod(tmp6, tmp7)
		var_clojure_DOT_core_DOT_protocols_internal_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_internal_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(22), kw_column, int(4), kw_end_DASH_line, int(22), kw_end_DASH_column, int(18), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// iter-reduce
	{
		tmp0 := sym_iter_DASH_reduce
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				var tmp4 any
				{ // let
					// let binding "iter"
					tmp5, ok := lang.FieldOrMethod(v2, "iterator")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v2, "iterator")))
					}
					var tmp6 any
					switch reflect.TypeOf(tmp5).Kind() {
					case reflect.Func:
						tmp6 = lang.Apply(tmp5, nil)
					default:
						tmp6 = tmp5
					}
					var v7 any = tmp6
					_ = v7
					var tmp8 any
					tmp9, ok := lang.FieldOrMethod(v7, "hasNext")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "hasNext")))
					}
					var tmp10 any
					switch reflect.TypeOf(tmp9).Kind() {
					case reflect.Func:
						tmp10 = lang.Apply(tmp9, nil)
					default:
						tmp10 = tmp9
					}
					if lang.IsTruthy(tmp10) {
						var tmp11 any
						{ // let
							// let binding "ret"
							tmp12, ok := lang.FieldOrMethod(v7, "next")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "next")))
							}
							var tmp13 any
							switch reflect.TypeOf(tmp12).Kind() {
							case reflect.Func:
								tmp13 = lang.Apply(tmp12, nil)
							default:
								tmp13 = tmp12
							}
							var v14 any = tmp13
							_ = v14
							for {
								var tmp15 any
								tmp16, ok := lang.FieldOrMethod(v7, "hasNext")
								if !ok {
									panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "hasNext")))
								}
								var tmp17 any
								switch reflect.TypeOf(tmp16).Kind() {
								case reflect.Func:
									tmp17 = lang.Apply(tmp16, nil)
								default:
									tmp17 = tmp16
								}
								if lang.IsTruthy(tmp17) {
									var tmp18 any
									{ // let
										// let binding "ret"
										tmp19, ok := lang.FieldOrMethod(v7, "next")
										if !ok {
											panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "next")))
										}
										var tmp20 any
										switch reflect.TypeOf(tmp19).Kind() {
										case reflect.Func:
											tmp20 = lang.Apply(tmp19, nil)
										default:
											tmp20 = tmp19
										}
										tmp21 := lang.Apply2(v3, v14, tmp20)
										var v22 any = tmp21
										_ = v22
										var tmp23 any
										tmp24 := lang.IsReduced(v22)
										if lang.IsTruthy(tmp24) {
											tmp25 := checkDerefVar(var_clojure_DOT_core_deref)
											tmp26 := lang.Apply1(tmp25, v22)
											tmp23 = tmp26
										} else {
											var tmp27 any = v22
											v14 = tmp27
											continue
										}
										tmp18 = tmp23
									} // end let
									tmp15 = tmp18
								} else {
									tmp15 = v14
								}
								tmp11 = tmp15
								break
							}
						} // end let
						tmp8 = tmp11
					} else {
						tmp12 := lang.Apply0(v3)
						tmp8 = tmp12
					}
					tmp4 = tmp8
				} // end let
				return tmp4
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				v4 := p2
				_ = v4
				var tmp5 any
				{ // let
					// let binding "iter"
					tmp6, ok := lang.FieldOrMethod(v2, "iterator")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v2, "iterator")))
					}
					var tmp7 any
					switch reflect.TypeOf(tmp6).Kind() {
					case reflect.Func:
						tmp7 = lang.Apply(tmp6, nil)
					default:
						tmp7 = tmp6
					}
					var v8 any = tmp7
					_ = v8
					var tmp9 any
					{ // let
						// let binding "ret"
						var v10 any = v4
						_ = v10
						for {
							var tmp11 any
							tmp12, ok := lang.FieldOrMethod(v8, "hasNext")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "hasNext")))
							}
							var tmp13 any
							switch reflect.TypeOf(tmp12).Kind() {
							case reflect.Func:
								tmp13 = lang.Apply(tmp12, nil)
							default:
								tmp13 = tmp12
							}
							if lang.IsTruthy(tmp13) {
								var tmp14 any
								{ // let
									// let binding "ret"
									tmp15, ok := lang.FieldOrMethod(v8, "next")
									if !ok {
										panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "next")))
									}
									var tmp16 any
									switch reflect.TypeOf(tmp15).Kind() {
									case reflect.Func:
										tmp16 = lang.Apply(tmp15, nil)
									default:
										tmp16 = tmp15
									}
									tmp17 := lang.Apply2(v3, v10, tmp16)
									var v18 any = tmp17
									_ = v18
									var tmp19 any
									tmp20 := lang.IsReduced(v18)
									if lang.IsTruthy(tmp20) {
										tmp21 := checkDerefVar(var_clojure_DOT_core_deref)
										tmp22 := lang.Apply1(tmp21, v18)
										tmp19 = tmp22
									} else {
										var tmp23 any = v18
										v10 = tmp23
										continue
									}
									tmp14 = tmp19
								} // end let
								tmp11 = tmp14
							} else {
								tmp11 = v10
							}
							tmp9 = tmp11
							break
						}
					} // end let
					tmp5 = tmp9
				} // end let
				return tmp5
			}),
			nil,
			nil,
			0,
		)
		var_clojure_DOT_core_DOT_protocols_iter_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_iter_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(33), kw_column, int(8), kw_end_DASH_line, int(33), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_coll, sym_f), lang.NewVector(sym_coll, sym_f, sym_val)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// kv-reduce
	{
		tmp0 := sym_kv_DASH_reduce
		var tmp2 lang.ArityFn
		tmp2 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v3 := args[0]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_class)
				tmp6 := lang.Apply1(tmp5, v3)
				return tmp6
			}),
			1,
		)
		// MultiFn kv-reduce
		tmp1 := lang.NewMultiFn("kv-reduce", tmp2, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var_clojure_DOT_core_DOT_protocols_kv_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_kv_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(186), kw_column, int(4), kw_end_DASH_line, int(186), kw_end_DASH_column, int(12), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// naive-seq-reduce
	{
		tmp0 := sym_naive_DASH_seq_DASH_reduce
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "s"
				tmp6 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp7 := lang.Apply1(tmp6, v2)
				var v8 any = tmp7
				_ = v8
				// let binding "val"
				var v9 any = v4
				_ = v9
				for {
					var tmp10 any
					if lang.IsTruthy(v8) {
						var tmp11 any
						{ // let
							// let binding "ret"
							tmp12 := checkDerefVar(var_clojure_DOT_core_first)
							tmp13 := lang.Apply1(tmp12, v8)
							tmp14 := lang.Apply2(v3, v9, tmp13)
							var v15 any = tmp14
							_ = v15
							var tmp16 any
							tmp17 := lang.IsReduced(v15)
							if lang.IsTruthy(tmp17) {
								tmp18 := checkDerefVar(var_clojure_DOT_core_deref)
								tmp19 := lang.Apply1(tmp18, v15)
								tmp16 = tmp19
							} else {
								tmp21 := checkDerefVar(var_clojure_DOT_core_next)
								tmp22 := lang.Apply1(tmp21, v8)
								var tmp20 any = tmp22
								var tmp23 any = v15
								v8 = tmp20
								v9 = tmp23
								continue
							}
							tmp11 = tmp16
						} // end let
						tmp10 = tmp11
					} else {
						tmp10 = v9
					}
					tmp5 = tmp10
					break
				}
			} // end let
			return tmp5
		})
		aotDirectFn1 = tmp1
		var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion1 = var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce.RootVersion()
		var_clojure_DOT_core_DOT_protocols_naive_DASH_seq_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_s, sym_f, sym_val)), kw_doc, "Reduces a seq, ignoring any opportunities to switch to a more\n  specialized implementation.", kw_file, "clojure/core/protocols.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols), kw_end_DASH_column, int(23), kw_column, int(8), kw_line, int(55), kw_end_DASH_line, int(55), kw_private, true)
		})
	}
	// nav
	{
		tmp0 := sym_nav
		var tmp2 lang.ArityFn
		tmp2 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v3 := args[0]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_class)
				tmp6 := lang.Apply1(tmp5, v3)
				return tmp6
			}),
			1,
		)
		// MultiFn nav
		tmp1 := lang.NewMultiFn("nav", tmp2, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		var_clojure_DOT_core_DOT_protocols_nav = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_nav.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(203), kw_column, int(4), kw_end_DASH_line, int(203), kw_end_DASH_column, int(6), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
	// seq-reduce
	{
		tmp0 := sym_seq_DASH_reduce
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				var tmp4 any
				{ // let
					// let binding "temp__0__auto__"
					tmp5 := checkDerefVar(var_clojure_DOT_core_seq)
					tmp6 := lang.Apply1(tmp5, v2)
					var v7 any = tmp6
					_ = v7
					var tmp8 any
					if lang.IsTruthy(v7) {
						var tmp9 any
						{ // let
							// let binding "s"
							var v10 any = v7
							_ = v10
							tmp11 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_internal_DASH_reduce)
							tmp12 := checkDerefVar(var_clojure_DOT_core_next)
							tmp13 := lang.Apply1(tmp12, v10)
							tmp14 := checkDerefVar(var_clojure_DOT_core_first)
							tmp15 := lang.Apply1(tmp14, v10)
							tmp16 := lang.Apply3(tmp11, tmp13, v3, tmp15)
							tmp9 = tmp16
						} // end let
						tmp8 = tmp9
					} else {
						tmp10 := lang.Apply0(v3)
						tmp8 = tmp10
					}
					tmp4 = tmp8
				} // end let
				return tmp4
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				v4 := p2
				_ = v4
				var tmp5 any
				{ // let
					// let binding "s"
					tmp6 := checkDerefVar(var_clojure_DOT_core_seq)
					tmp7 := lang.Apply1(tmp6, v2)
					var v8 any = tmp7
					_ = v8
					tmp9 := checkDerefVar(var_clojure_DOT_core_DOT_protocols_internal_DASH_reduce)
					tmp10 := lang.Apply3(tmp9, v8, v3, v4)
					tmp5 = tmp10
				} // end let
				return tmp5
			}),
			nil,
			nil,
			0,
		)
		var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_protocols_seq_DASH_reduce.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/protocols.glj", kw_line, int(24), kw_column, int(8), kw_end_DASH_line, int(24), kw_end_DASH_column, int(17), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_coll, sym_f), lang.NewVector(sym_coll, sym_f, sym_val)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_protocols))
		})
	}
}
