//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

const maxFixedArity = 20

func names(n int, prefix string) []string {
	result := make([]string, n)
	for i := range result {
		result[i] = fmt.Sprintf("%s%d", prefix, i)
	}
	return result
}

func repeated(n int, value string) string {
	values := make([]string, n)
	for i := range values {
		values[i] = value
	}
	return strings.Join(values, ", ")
}

func main() {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package lang")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, `import "fmt"`)
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "func requireExtendedFixedSeqArity(args ISeq, expected int) [20]any {")
	fmt.Fprintln(&out, "\tvar values [20]any")
	fmt.Fprintln(&out, "\tseq := args")
	fmt.Fprintln(&out, "\tfor i := 0; i < expected; i++ {")
	fmt.Fprintln(&out, "\t\tif seq == nil {")
	fmt.Fprintln(&out, "\t\t\tpanic(NewIllegalArgumentError(fmt.Sprintf(")
	fmt.Fprintln(&out, "\t\t\t\t\"wrong number of arguments: expected %d, got %d\", expected, i)))")
	fmt.Fprintln(&out, "\t\t}")
	fmt.Fprintln(&out, "\t\tvalues[i] = seq.First()")
	fmt.Fprintln(&out, "\t\tseq = seq.Next()")
	fmt.Fprintln(&out, "\t}")
	fmt.Fprintln(&out, "\tif seq != nil {")
	fmt.Fprintln(&out, "\t\tgot := expected")
	fmt.Fprintln(&out, "\t\tfor ; seq != nil; seq = seq.Next() {")
	fmt.Fprintln(&out, "\t\t\tgot++")
	fmt.Fprintln(&out, "\t\t}")
	fmt.Fprintln(&out, "\t\tpanic(NewIllegalArgumentError(fmt.Sprintf(")
	fmt.Fprintln(&out, "\t\t\t\"wrong number of arguments: expected %d, got %d\", expected, got)))")
	fmt.Fprintln(&out, "\t}")
	fmt.Fprintln(&out, "\treturn values")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)

	for arity := 6; arity <= maxFixedArity; arity++ {
		params := strings.Join(names(arity, "a"), ", ")
		typedParams := params + " any"
		anyParams := repeated(arity, "any")
		argIndexes := make([]string, arity)
		valueIndexes := make([]string, arity)
		for i := 0; i < arity; i++ {
			argIndexes[i] = fmt.Sprintf("args[%d]", i)
			valueIndexes[i] = fmt.Sprintf("values[%d]", i)
		}

		fmt.Fprintf(&out, "type FixedArityFn%d interface { Invoke%d(%s) any }\n\n",
			arity, arity, anyParams)
		fmt.Fprintf(&out, "type FnFunc%d func(%s) any\n\n", arity, anyParams)
		fmt.Fprintf(&out, "func NewFnFunc%d(fn func(%s) any) FnFunc%d { return FnFunc%d(fn) }\n\n",
			arity, anyParams, arity, arity)
		fmt.Fprintf(&out, "func (f FnFunc%d) Invoke(args ...any) any {\n", arity)
		fmt.Fprintf(&out, "\tif len(args) != %d {\n", arity)
		fmt.Fprintf(&out, "\t\tpanic(NewIllegalArgumentError(fmt.Sprintf(\"wrong number of arguments: expected %d, got %%d\", len(args))))\n", arity)
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintf(&out, "\treturn f(%s)\n", strings.Join(argIndexes, ", "))
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "func (f FnFunc%d) Invoke%d(%s) any { return f(%s) }\n\n",
			arity, arity, typedParams, params)
		fmt.Fprintf(&out, "func (f FnFunc%d) ApplyTo(args ISeq) any {\n", arity)
		fmt.Fprintf(&out, "\tvalues := requireExtendedFixedSeqArity(args, %d)\n", arity)
		fmt.Fprintf(&out, "\treturn f(%s)\n", strings.Join(valueIndexes, ", "))
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "func (f FnFunc%d) Meta() IPersistentMap { return nil }\n", arity)
		fmt.Fprintf(&out, "func (f FnFunc%d) WithMeta(_ IPersistentMap) any { return f }\n\n", arity)

		fmt.Fprintf(&out, "func Apply%d(fn interface{}, %s) any {\n", arity, typedParams)
		fmt.Fprintln(&out, "\tswitch f := fn.(type) {")
		fmt.Fprintf(&out, "\tcase FnFunc%d:\n\t\treturn f(%s)\n", arity, params)
		fmt.Fprintf(&out, "\tcase FnFunc:\n\t\treturn f(%s)\n", params)
		fmt.Fprintf(&out, "\tcase func(%s) any:\n\t\treturn f(%s)\n", anyParams, params)
		fmt.Fprintf(&out, "\tcase FixedArityFn%d:\n\t\treturn f.Invoke%d(%s)\n", arity, arity, params)
		fmt.Fprintf(&out, "\tcase IFn:\n\t\treturn f.Invoke(%s)\n", params)
		fmt.Fprintf(&out, "\tdefault:\n\t\treturn Apply(fn, []any{%s})\n", params)
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)

		fmt.Fprintf(&out, "func (f ArityFn) Invoke%d(%s) any {\n", arity, typedParams)
		fmt.Fprintf(&out, "\tif method := f.fixedMethod(%d); method != nil {\n", arity)
		fmt.Fprintf(&out, "\t\treturn Apply%d(method, %s)\n", arity, params)
		fmt.Fprintln(&out, "\t}")
		fmt.Fprintf(&out, "\treturn f.Invoke(%s)\n", params)
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}

	fmt.Fprintln(&out, "var (")
	for arity := 6; arity <= maxFixedArity; arity++ {
		fmt.Fprintf(&out, "\t_ IFn = FnFunc%d(nil)\n", arity)
		fmt.Fprintf(&out, "\t_ FixedArityFn%d = ArityFn{}\n", arity)
	}
	fmt.Fprintln(&out, ")")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("fixed_arities_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
