// Code generated by glojure codegen. DO NOT EDIT.

package uuid

import (
	fmt "fmt"
	uuid4 "github.com/glojurelang/glojure/pkg/javacompat/uuid"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func init() {
	runtime.RegisterNSLoader("clojure/uuid", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "clojure.uuid"
func LoadNS() {
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_uuid := lang.NewSymbolUnchecked("clojure.uuid")
	sym_default_DASH_uuid_DASH_reader := lang.NewSymbolUnchecked("default-uuid-reader")
	sym_form := lang.NewSymbolUnchecked("form")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.uuid/default-uuid-reader
	var_clojure_DOT_uuid_default_DASH_uuid_DASH_reader := lang.InternVarName(sym_clojure_DOT_uuid, sym_default_DASH_uuid_DASH_reader)
	aotExternalFn0 := aotLinkFn1(var_clojure_DOT_core_string_QMARK_)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_clojure_DOT_uuid)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// default-uuid-reader
	{
		tmp0 := sym_default_DASH_uuid_DASH_reader
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			tmp4 := aotExternalFn0(v2)
			if lang.IsTruthy(tmp4) {
				tmp5 := lang.Apply1(uuid4.FromString, v2)
				tmp3 = tmp5
			} else {
				tmp6 := lang.Apply1(lang.NewIllegalArgumentError, "#uuid data reader expected string")
				panic(tmp6)
			}
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_clojure_DOT_uuid_default_DASH_uuid_DASH_reader = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_uuid_default_DASH_uuid_DASH_reader.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/uuid.glj", kw_line, int(11), kw_column, int(8), kw_end_DASH_line, int(11), kw_end_DASH_column, int(26), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_uuid))
		})
	}
}
