// Code generated by glojure codegen. DO NOT EDIT.

package walk

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
)

var aotDirectFn0 lang.FnFunc1
var aotRootVersion0 *lang.VarRootVersion
var aotDirectFn1 lang.FnFunc1
var aotRootVersion1 *lang.VarRootVersion
var aotDirectFn2 lang.FnFunc2
var aotRootVersion2 *lang.VarRootVersion
var aotDirectFn3 lang.FnFunc1
var aotRootVersion3 *lang.VarRootVersion
var aotDirectFn4 lang.FnFunc2
var aotRootVersion4 *lang.VarRootVersion
var aotDirectFn5 lang.FnFunc2
var aotRootVersion5 *lang.VarRootVersion
var aotDirectFn6 lang.FnFunc1
var aotRootVersion6 *lang.VarRootVersion
var aotDirectFn7 lang.FnFunc2
var aotRootVersion7 *lang.VarRootVersion
var aotDirectFn8 lang.FnFunc1
var aotRootVersion8 *lang.VarRootVersion
var aotDirectFn9 lang.FnFunc3
var aotRootVersion9 *lang.VarRootVersion

func init() {
	runtime.RegisterNSLoader("clojure/walk", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "clojure.walk"
func LoadNS() {
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_walk := lang.NewSymbolUnchecked("clojure.walk")
	sym_coll_QMARK_ := lang.NewSymbolUnchecked("coll?")
	sym_conj := lang.NewSymbolUnchecked("conj")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_doall := lang.NewSymbolUnchecked("doall")
	sym_empty := lang.NewSymbolUnchecked("empty")
	sym_f := lang.NewSymbolUnchecked("f")
	sym_form := lang.NewSymbolUnchecked("form")
	sym_identity := lang.NewSymbolUnchecked("identity")
	sym_inner := lang.NewSymbolUnchecked("inner")
	sym_instance_QMARK_ := lang.NewSymbolUnchecked("instance?")
	sym_into := lang.NewSymbolUnchecked("into")
	sym_key := lang.NewSymbolUnchecked("key")
	sym_keyword := lang.NewSymbolUnchecked("keyword")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_keywordize_DASH_keys := lang.NewSymbolUnchecked("keywordize-keys")
	sym_list := lang.NewSymbolUnchecked("list")
	sym_list_QMARK_ := lang.NewSymbolUnchecked("list?")
	sym_m := lang.NewSymbolUnchecked("m")
	sym_macroexpand := lang.NewSymbolUnchecked("macroexpand")
	sym_macroexpand_DASH_all := lang.NewSymbolUnchecked("macroexpand-all")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_map_QMARK_ := lang.NewSymbolUnchecked("map?")
	sym_meta := lang.NewSymbolUnchecked("meta")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_nth := lang.NewSymbolUnchecked("nth")
	sym_outer := lang.NewSymbolUnchecked("outer")
	sym_partial := lang.NewSymbolUnchecked("partial")
	sym_postwalk := lang.NewSymbolUnchecked("postwalk")
	sym_postwalk_DASH_demo := lang.NewSymbolUnchecked("postwalk-demo")
	sym_postwalk_DASH_replace := lang.NewSymbolUnchecked("postwalk-replace")
	sym_prewalk := lang.NewSymbolUnchecked("prewalk")
	sym_prewalk_DASH_demo := lang.NewSymbolUnchecked("prewalk-demo")
	sym_prewalk_DASH_replace := lang.NewSymbolUnchecked("prewalk-replace")
	sym_print := lang.NewSymbolUnchecked("print")
	sym_prn := lang.NewSymbolUnchecked("prn")
	sym_reduce := lang.NewSymbolUnchecked("reduce")
	sym_seq_QMARK_ := lang.NewSymbolUnchecked("seq?")
	sym_smap := lang.NewSymbolUnchecked("smap")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_stringify_DASH_keys := lang.NewSymbolUnchecked("stringify-keys")
	sym_val := lang.NewSymbolUnchecked("val")
	sym_walk := lang.NewSymbolUnchecked("walk")
	sym_with_DASH_meta := lang.NewSymbolUnchecked("with-meta")
	kw_added := lang.NewKeyword("added")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/coll?
	var_clojure_DOT_core_coll_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_coll_QMARK_)
	// var clojure.core/conj
	var_clojure_DOT_core_conj := lang.InternVarName(sym_clojure_DOT_core, sym_conj)
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/doall
	var_clojure_DOT_core_doall := lang.InternVarName(sym_clojure_DOT_core, sym_doall)
	// var clojure.core/empty
	var_clojure_DOT_core_empty := lang.InternVarName(sym_clojure_DOT_core, sym_empty)
	// var clojure.core/identity
	var_clojure_DOT_core_identity := lang.InternVarName(sym_clojure_DOT_core, sym_identity)
	// var clojure.core/instance?
	var_clojure_DOT_core_instance_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_instance_QMARK_)
	// var clojure.core/into
	var_clojure_DOT_core_into := lang.InternVarName(sym_clojure_DOT_core, sym_into)
	// var clojure.core/key
	var_clojure_DOT_core_key := lang.InternVarName(sym_clojure_DOT_core, sym_key)
	// var clojure.core/keyword
	var_clojure_DOT_core_keyword := lang.InternVarName(sym_clojure_DOT_core, sym_keyword)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/list
	var_clojure_DOT_core_list := lang.InternVarName(sym_clojure_DOT_core, sym_list)
	// var clojure.core/list?
	var_clojure_DOT_core_list_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_list_QMARK_)
	// var clojure.core/macroexpand
	var_clojure_DOT_core_macroexpand := lang.InternVarName(sym_clojure_DOT_core, sym_macroexpand)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/map?
	var_clojure_DOT_core_map_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_map_QMARK_)
	// var clojure.core/meta
	var_clojure_DOT_core_meta := lang.InternVarName(sym_clojure_DOT_core, sym_meta)
	// var clojure.core/name
	var_clojure_DOT_core_name := lang.InternVarName(sym_clojure_DOT_core, sym_name)
	// var clojure.core/nth
	var_clojure_DOT_core_nth := lang.InternVarName(sym_clojure_DOT_core, sym_nth)
	// var clojure.core/partial
	var_clojure_DOT_core_partial := lang.InternVarName(sym_clojure_DOT_core, sym_partial)
	// var clojure.core/print
	var_clojure_DOT_core_print := lang.InternVarName(sym_clojure_DOT_core, sym_print)
	// var clojure.core/prn
	var_clojure_DOT_core_prn := lang.InternVarName(sym_clojure_DOT_core, sym_prn)
	// var clojure.core/reduce
	var_clojure_DOT_core_reduce := lang.InternVarName(sym_clojure_DOT_core, sym_reduce)
	// var clojure.core/seq?
	var_clojure_DOT_core_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_seq_QMARK_)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.core/val
	var_clojure_DOT_core_val := lang.InternVarName(sym_clojure_DOT_core, sym_val)
	// var clojure.core/with-meta
	var_clojure_DOT_core_with_DASH_meta := lang.InternVarName(sym_clojure_DOT_core, sym_with_DASH_meta)
	// var clojure.walk/keywordize-keys
	var_clojure_DOT_walk_keywordize_DASH_keys := lang.InternVarName(sym_clojure_DOT_walk, sym_keywordize_DASH_keys)
	// var clojure.walk/macroexpand-all
	var_clojure_DOT_walk_macroexpand_DASH_all := lang.InternVarName(sym_clojure_DOT_walk, sym_macroexpand_DASH_all)
	// var clojure.walk/postwalk
	var_clojure_DOT_walk_postwalk := lang.InternVarName(sym_clojure_DOT_walk, sym_postwalk)
	// var clojure.walk/postwalk-demo
	var_clojure_DOT_walk_postwalk_DASH_demo := lang.InternVarName(sym_clojure_DOT_walk, sym_postwalk_DASH_demo)
	// var clojure.walk/postwalk-replace
	var_clojure_DOT_walk_postwalk_DASH_replace := lang.InternVarName(sym_clojure_DOT_walk, sym_postwalk_DASH_replace)
	// var clojure.walk/prewalk
	var_clojure_DOT_walk_prewalk := lang.InternVarName(sym_clojure_DOT_walk, sym_prewalk)
	// var clojure.walk/prewalk-demo
	var_clojure_DOT_walk_prewalk_DASH_demo := lang.InternVarName(sym_clojure_DOT_walk, sym_prewalk_DASH_demo)
	// var clojure.walk/prewalk-replace
	var_clojure_DOT_walk_prewalk_DASH_replace := lang.InternVarName(sym_clojure_DOT_walk, sym_prewalk_DASH_replace)
	// var clojure.walk/stringify-keys
	var_clojure_DOT_walk_stringify_DASH_keys := lang.InternVarName(sym_clojure_DOT_walk, sym_stringify_DASH_keys)
	// var clojure.walk/walk
	var_clojure_DOT_walk_walk := lang.InternVarName(sym_clojure_DOT_walk, sym_walk)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_clojure_DOT_walk)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// keywordize-keys
	{
		tmp0 := sym_keywordize_DASH_keys
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "f"
				var tmp4 lang.FnFunc1
				tmp4 = lang.FnFunc1(func(p0 any) any {
					v5 := p0
					_ = v5
					var tmp6 any
					{ // let
						// let binding "vec__765"
						var v7 any = v5
						_ = v7
						// let binding "k"
						tmp8 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp9 := lang.Apply3(tmp8, v7, int64(0), nil)
						var v10 any = tmp9
						_ = v10
						// let binding "v"
						tmp11 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp12 := lang.Apply3(tmp11, v7, int64(1), nil)
						var v13 any = tmp12
						_ = v13
						var tmp14 any
						tmp15 := checkDerefVar(var_clojure_DOT_core_string_QMARK_)
						tmp16 := lang.Apply1(tmp15, v10)
						if lang.IsTruthy(tmp16) {
							tmp17 := checkDerefVar(var_clojure_DOT_core_keyword)
							tmp18 := lang.Apply1(tmp17, v10)
							tmp19 := lang.NewVector(tmp18, v13)
							tmp20 := lang.NewMap(kw_file, "clojure/walk.glj", kw_line, int(98), kw_column, int(39), kw_end_DASH_line, int(98), kw_end_DASH_column, int(53))
							tmp21, err := lang.WithMeta(tmp19, tmp20.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp14 = tmp21
						} else {
							tmp22 := lang.NewVector(v10, v13)
							tmp23 := lang.NewMap(kw_file, "clojure/walk.glj", kw_line, int(98), kw_column, int(55), kw_end_DASH_line, int(98), kw_end_DASH_column, int(59))
							tmp24, err := lang.WithMeta(tmp22, tmp23.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp14 = tmp24
						}
						tmp6 = tmp14
					} // end let
					return tmp6
				})
				var v5 any = tmp4
				_ = v5
				tmp6 := var_clojure_DOT_walk_postwalk.RootVersion() == aotRootVersion2 && !var_clojure_DOT_walk_postwalk.IsMacro()
				var tmp7 any
				if !tmp6 {
					tmp7 = checkDerefVar(var_clojure_DOT_walk_postwalk)
				}
				var tmp8 lang.FnFunc1
				tmp8 = lang.FnFunc1(func(p0 any) any {
					v9 := p0
					_ = v9
					var tmp10 any
					tmp11 := checkDerefVar(var_clojure_DOT_core_map_QMARK_)
					tmp12 := lang.Apply1(tmp11, v9)
					if lang.IsTruthy(tmp12) {
						tmp13 := checkDerefVar(var_clojure_DOT_core_into)
						tmp14 := lang.NewMap()
						tmp15 := lang.NewMap(kw_file, "clojure/walk.glj", kw_line, int(100), kw_column, int(42), kw_end_DASH_line, int(100), kw_end_DASH_column, int(43))
						tmp16, err := lang.WithMeta(tmp14, tmp15.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp17 := checkDerefVar(var_clojure_DOT_core_map)
						tmp18 := lang.Apply2(tmp17, v5, v9)
						tmp19 := lang.Apply2(tmp13, tmp16, tmp18)
						tmp10 = tmp19
					} else {
						tmp10 = v9
					}
					return tmp10
				})
				var tmp9 any
				if tmp6 {
					tmp9 = aotDirectFn2(tmp8, v2)
				} else {
					tmp9 = lang.Apply2(tmp7, tmp8, v2)
				}
				tmp3 = tmp9
			} // end let
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_clojure_DOT_walk_keywordize_DASH_keys = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion0 = var_clojure_DOT_walk_keywordize_DASH_keys.RootVersion()
		var_clojure_DOT_walk_keywordize_DASH_keys.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_m)), kw_doc, "Recursively transforms all map keys from strings to keywords.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(21), kw_column, int(7), kw_line, int(94), kw_end_DASH_line, int(94))
		})
	}
	// macroexpand-all
	{
		tmp0 := sym_macroexpand_DASH_all
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := var_clojure_DOT_walk_prewalk.RootVersion() == aotRootVersion5 && !var_clojure_DOT_walk_prewalk.IsMacro()
			var tmp4 any
			if !tmp3 {
				tmp4 = checkDerefVar(var_clojure_DOT_walk_prewalk)
			}
			var tmp5 lang.FnFunc1
			tmp5 = lang.FnFunc1(func(p0 any) any {
				v6 := p0
				_ = v6
				var tmp7 any
				tmp8 := checkDerefVar(var_clojure_DOT_core_seq_QMARK_)
				tmp9 := lang.Apply1(tmp8, v6)
				if lang.IsTruthy(tmp9) {
					tmp10 := checkDerefVar(var_clojure_DOT_core_macroexpand)
					tmp11 := lang.Apply1(tmp10, v6)
					tmp7 = tmp11
				} else {
					tmp7 = v6
				}
				return tmp7
			})
			var tmp6 any
			if tmp3 {
				tmp6 = aotDirectFn5(tmp5, v2)
			} else {
				tmp6 = lang.Apply2(tmp4, tmp5, v2)
			}
			return tmp6
		})
		aotDirectFn1 = tmp1
		var_clojure_DOT_walk_macroexpand_DASH_all = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion1 = var_clojure_DOT_walk_macroexpand_DASH_all.RootVersion()
		var_clojure_DOT_walk_macroexpand_DASH_all.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_doc, "Recursively performs all possible macroexpansions in form.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(21), kw_column, int(7), kw_line, int(126), kw_end_DASH_line, int(126))
		})
	}
	// postwalk
	{
		tmp0 := sym_postwalk
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := var_clojure_DOT_walk_walk.RootVersion() == aotRootVersion9 && !var_clojure_DOT_walk_walk.IsMacro()
			var tmp5 any
			if !tmp4 {
				tmp5 = checkDerefVar(var_clojure_DOT_walk_walk)
			}
			tmp6 := checkDerefVar(var_clojure_DOT_core_partial)
			tmp7 := checkDerefVar(var_clojure_DOT_walk_postwalk)
			tmp8 := lang.Apply2(tmp6, tmp7, v2)
			var tmp9 any
			if tmp4 {
				tmp9 = aotDirectFn9(tmp8, v2, v3)
			} else {
				tmp9 = lang.Apply3(tmp5, tmp8, v2, v3)
			}
			return tmp9
		})
		aotDirectFn2 = tmp1
		var_clojure_DOT_walk_postwalk = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion2 = var_clojure_DOT_walk_postwalk.RootVersion()
		var_clojure_DOT_walk_postwalk.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_f, sym_form)), kw_doc, "Performs a depth-first, post-order traversal of form.  Calls f on\n  each sub-form, uses f's return value in place of the original.\n  Recognizes all Clojure data structures. Consumes seqs as with doall.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(14), kw_column, int(7), kw_line, int(53), kw_end_DASH_line, int(53))
		})
	}
	// postwalk-demo
	{
		tmp0 := sym_postwalk_DASH_demo
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := var_clojure_DOT_walk_postwalk.RootVersion() == aotRootVersion2 && !var_clojure_DOT_walk_postwalk.IsMacro()
			var tmp4 any
			if !tmp3 {
				tmp4 = checkDerefVar(var_clojure_DOT_walk_postwalk)
			}
			var tmp5 lang.FnFunc1
			tmp5 = lang.FnFunc1(func(p0 any) any {
				v6 := p0
				_ = v6
				tmp7 := checkDerefVar(var_clojure_DOT_core_print)
				tmp8 := lang.Apply1(tmp7, "Walked: ")
				_ = tmp8
				tmp9 := checkDerefVar(var_clojure_DOT_core_prn)
				tmp10 := lang.Apply1(tmp9, v6)
				_ = tmp10
				return v6
			})
			var tmp6 any
			if tmp3 {
				tmp6 = aotDirectFn2(tmp5, v2)
			} else {
				tmp6 = lang.Apply2(tmp4, tmp5, v2)
			}
			return tmp6
		})
		aotDirectFn3 = tmp1
		var_clojure_DOT_walk_postwalk_DASH_demo = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion3 = var_clojure_DOT_walk_postwalk_DASH_demo.RootVersion()
		var_clojure_DOT_walk_postwalk_DASH_demo.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_doc, "Demonstrates the behavior of postwalk by printing each form as it is\n  walked.  Returns form.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(19), kw_column, int(7), kw_line, int(80), kw_end_DASH_line, int(80))
		})
	}
	// postwalk-replace
	{
		tmp0 := sym_postwalk_DASH_replace
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := var_clojure_DOT_walk_postwalk.RootVersion() == aotRootVersion2 && !var_clojure_DOT_walk_postwalk.IsMacro()
			var tmp5 any
			if !tmp4 {
				tmp5 = checkDerefVar(var_clojure_DOT_walk_postwalk)
			}
			var tmp6 lang.FnFunc1
			tmp6 = lang.FnFunc1(func(p0 any) any {
				v7 := p0
				_ = v7
				var tmp8 any
				tmp9 := checkDerefVar(var_clojure_DOT_core_contains_QMARK_)
				tmp10 := lang.Apply2(tmp9, v2, v7)
				if lang.IsTruthy(tmp10) {
					tmp11 := lang.Apply1(v2, v7)
					tmp8 = tmp11
				} else {
					tmp8 = v7
				}
				return tmp8
			})
			var tmp7 any
			if tmp4 {
				tmp7 = aotDirectFn2(tmp6, v3)
			} else {
				tmp7 = lang.Apply2(tmp5, tmp6, v3)
			}
			return tmp7
		})
		aotDirectFn4 = tmp1
		var_clojure_DOT_walk_postwalk_DASH_replace = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion4 = var_clojure_DOT_walk_postwalk_DASH_replace.RootVersion()
		var_clojure_DOT_walk_postwalk_DASH_replace.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_smap, sym_form)), kw_doc, "Recursively transforms form by replacing keys in smap with their\n  values.  Like clojure/replace but works on any data structure.  Does\n  replacement at the leaves of the tree first.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(22), kw_column, int(7), kw_line, int(118), kw_end_DASH_line, int(118))
		})
	}
	// prewalk
	{
		tmp0 := sym_prewalk
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := var_clojure_DOT_walk_walk.RootVersion() == aotRootVersion9 && !var_clojure_DOT_walk_walk.IsMacro()
			var tmp5 any
			if !tmp4 {
				tmp5 = checkDerefVar(var_clojure_DOT_walk_walk)
			}
			tmp6 := checkDerefVar(var_clojure_DOT_core_partial)
			tmp7 := checkDerefVar(var_clojure_DOT_walk_prewalk)
			tmp8 := lang.Apply2(tmp6, tmp7, v2)
			tmp9 := checkDerefVar(var_clojure_DOT_core_identity)
			tmp10 := lang.Apply1(v2, v3)
			var tmp11 any
			if tmp4 {
				tmp11 = aotDirectFn9(tmp8, tmp9, tmp10)
			} else {
				tmp11 = lang.Apply3(tmp5, tmp8, tmp9, tmp10)
			}
			return tmp11
		})
		aotDirectFn5 = tmp1
		var_clojure_DOT_walk_prewalk = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion5 = var_clojure_DOT_walk_prewalk.RootVersion()
		var_clojure_DOT_walk_prewalk.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_f, sym_form)), kw_doc, "Like postwalk, but does pre-order traversal.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(13), kw_column, int(7), kw_line, int(61), kw_end_DASH_line, int(61))
		})
	}
	// prewalk-demo
	{
		tmp0 := sym_prewalk_DASH_demo
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := var_clojure_DOT_walk_prewalk.RootVersion() == aotRootVersion5 && !var_clojure_DOT_walk_prewalk.IsMacro()
			var tmp4 any
			if !tmp3 {
				tmp4 = checkDerefVar(var_clojure_DOT_walk_prewalk)
			}
			var tmp5 lang.FnFunc1
			tmp5 = lang.FnFunc1(func(p0 any) any {
				v6 := p0
				_ = v6
				tmp7 := checkDerefVar(var_clojure_DOT_core_print)
				tmp8 := lang.Apply1(tmp7, "Walked: ")
				_ = tmp8
				tmp9 := checkDerefVar(var_clojure_DOT_core_prn)
				tmp10 := lang.Apply1(tmp9, v6)
				_ = tmp10
				return v6
			})
			var tmp6 any
			if tmp3 {
				tmp6 = aotDirectFn5(tmp5, v2)
			} else {
				tmp6 = lang.Apply2(tmp4, tmp5, v2)
			}
			return tmp6
		})
		aotDirectFn6 = tmp1
		var_clojure_DOT_walk_prewalk_DASH_demo = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion6 = var_clojure_DOT_walk_prewalk_DASH_demo.RootVersion()
		var_clojure_DOT_walk_prewalk_DASH_demo.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_doc, "Demonstrates the behavior of prewalk by printing each form as it is\n  walked.  Returns form.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(18), kw_column, int(7), kw_line, int(87), kw_end_DASH_line, int(87))
		})
	}
	// prewalk-replace
	{
		tmp0 := sym_prewalk_DASH_replace
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := var_clojure_DOT_walk_prewalk.RootVersion() == aotRootVersion5 && !var_clojure_DOT_walk_prewalk.IsMacro()
			var tmp5 any
			if !tmp4 {
				tmp5 = checkDerefVar(var_clojure_DOT_walk_prewalk)
			}
			var tmp6 lang.FnFunc1
			tmp6 = lang.FnFunc1(func(p0 any) any {
				v7 := p0
				_ = v7
				var tmp8 any
				tmp9 := checkDerefVar(var_clojure_DOT_core_contains_QMARK_)
				tmp10 := lang.Apply2(tmp9, v2, v7)
				if lang.IsTruthy(tmp10) {
					tmp11 := lang.Apply1(v2, v7)
					tmp8 = tmp11
				} else {
					tmp8 = v7
				}
				return tmp8
			})
			var tmp7 any
			if tmp4 {
				tmp7 = aotDirectFn5(tmp6, v3)
			} else {
				tmp7 = lang.Apply2(tmp5, tmp6, v3)
			}
			return tmp7
		})
		aotDirectFn7 = tmp1
		var_clojure_DOT_walk_prewalk_DASH_replace = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion7 = var_clojure_DOT_walk_prewalk_DASH_replace.RootVersion()
		var_clojure_DOT_walk_prewalk_DASH_replace.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_smap, sym_form)), kw_doc, "Recursively transforms form by replacing keys in smap with their\n  values.  Like clojure/replace but works on any data structure.  Does\n  replacement at the root of the tree first.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(21), kw_column, int(7), kw_line, int(110), kw_end_DASH_line, int(110))
		})
	}
	// stringify-keys
	{
		tmp0 := sym_stringify_DASH_keys
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "f"
				var tmp4 lang.FnFunc1
				tmp4 = lang.FnFunc1(func(p0 any) any {
					v5 := p0
					_ = v5
					var tmp6 any
					{ // let
						// let binding "vec__769"
						var v7 any = v5
						_ = v7
						// let binding "k"
						tmp8 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp9 := lang.Apply3(tmp8, v7, int64(0), nil)
						var v10 any = tmp9
						_ = v10
						// let binding "v"
						tmp11 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp12 := lang.Apply3(tmp11, v7, int64(1), nil)
						var v13 any = tmp12
						_ = v13
						var tmp14 any
						tmp15 := checkDerefVar(var_clojure_DOT_core_keyword_QMARK_)
						tmp16 := lang.Apply1(tmp15, v10)
						if lang.IsTruthy(tmp16) {
							tmp17 := checkDerefVar(var_clojure_DOT_core_name)
							tmp18 := lang.Apply1(tmp17, v10)
							tmp19 := lang.NewVector(tmp18, v13)
							tmp20 := lang.NewMap(kw_file, "clojure/walk.glj", kw_line, int(106), kw_column, int(40), kw_end_DASH_line, int(106), kw_end_DASH_column, int(51))
							tmp21, err := lang.WithMeta(tmp19, tmp20.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp14 = tmp21
						} else {
							tmp22 := lang.NewVector(v10, v13)
							tmp23 := lang.NewMap(kw_file, "clojure/walk.glj", kw_line, int(106), kw_column, int(53), kw_end_DASH_line, int(106), kw_end_DASH_column, int(57))
							tmp24, err := lang.WithMeta(tmp22, tmp23.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp14 = tmp24
						}
						tmp6 = tmp14
					} // end let
					return tmp6
				})
				var v5 any = tmp4
				_ = v5
				tmp6 := var_clojure_DOT_walk_postwalk.RootVersion() == aotRootVersion2 && !var_clojure_DOT_walk_postwalk.IsMacro()
				var tmp7 any
				if !tmp6 {
					tmp7 = checkDerefVar(var_clojure_DOT_walk_postwalk)
				}
				var tmp8 lang.FnFunc1
				tmp8 = lang.FnFunc1(func(p0 any) any {
					v9 := p0
					_ = v9
					var tmp10 any
					tmp11 := checkDerefVar(var_clojure_DOT_core_map_QMARK_)
					tmp12 := lang.Apply1(tmp11, v9)
					if lang.IsTruthy(tmp12) {
						tmp13 := checkDerefVar(var_clojure_DOT_core_into)
						tmp14 := lang.NewMap()
						tmp15 := lang.NewMap(kw_file, "clojure/walk.glj", kw_line, int(108), kw_column, int(42), kw_end_DASH_line, int(108), kw_end_DASH_column, int(43))
						tmp16, err := lang.WithMeta(tmp14, tmp15.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp17 := checkDerefVar(var_clojure_DOT_core_map)
						tmp18 := lang.Apply2(tmp17, v5, v9)
						tmp19 := lang.Apply2(tmp13, tmp16, tmp18)
						tmp10 = tmp19
					} else {
						tmp10 = v9
					}
					return tmp10
				})
				var tmp9 any
				if tmp6 {
					tmp9 = aotDirectFn2(tmp8, v2)
				} else {
					tmp9 = lang.Apply2(tmp7, tmp8, v2)
				}
				tmp3 = tmp9
			} // end let
			return tmp3
		})
		aotDirectFn8 = tmp1
		var_clojure_DOT_walk_stringify_DASH_keys = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion8 = var_clojure_DOT_walk_stringify_DASH_keys.RootVersion()
		var_clojure_DOT_walk_stringify_DASH_keys.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_m)), kw_doc, "Recursively transforms all map keys from keywords to strings.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(20), kw_column, int(7), kw_line, int(102), kw_end_DASH_line, int(102))
		})
	}
	// walk
	{
		tmp0 := sym_walk
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			tmp6 := checkDerefVar(var_clojure_DOT_core_list_QMARK_)
			tmp7 := lang.Apply1(tmp6, v4)
			if lang.IsTruthy(tmp7) {
				tmp8 := checkDerefVar(var_clojure_DOT_core_with_DASH_meta)
				tmp9 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp10 := checkDerefVar(var_clojure_DOT_core_list)
				tmp11 := checkDerefVar(var_clojure_DOT_core_map)
				tmp12 := lang.Apply2(tmp11, v2, v4)
				tmp13 := lang.Apply2(tmp9, tmp10, tmp12)
				tmp14 := checkDerefVar(var_clojure_DOT_core_meta)
				tmp15 := lang.Apply1(tmp14, v4)
				tmp16 := lang.Apply2(tmp8, tmp13, tmp15)
				tmp17 := lang.Apply1(v3, tmp16)
				tmp5 = tmp17
			} else {
				var tmp18 any
				tmp19 := checkDerefVar(var_clojure_DOT_core_instance_QMARK_)
				tmp20 := reflect.TypeOf((*lang.IMapEntry)(nil)).Elem()
				tmp21 := lang.Apply2(tmp19, tmp20, v4)
				if lang.IsTruthy(tmp21) {
					tmp22 := checkDerefVar(var_clojure_DOT_core_key)
					tmp23 := lang.Apply1(tmp22, v4)
					tmp24 := lang.Apply1(v2, tmp23)
					tmp25 := checkDerefVar(var_clojure_DOT_core_val)
					tmp26 := lang.Apply1(tmp25, v4)
					tmp27 := lang.Apply1(v2, tmp26)
					tmp28 := lang.Apply2(nil, tmp24, tmp27)
					tmp29 := lang.Apply1(v3, tmp28)
					tmp18 = tmp29
				} else {
					var tmp30 any
					tmp31 := checkDerefVar(var_clojure_DOT_core_seq_QMARK_)
					tmp32 := lang.Apply1(tmp31, v4)
					if lang.IsTruthy(tmp32) {
						tmp33 := checkDerefVar(var_clojure_DOT_core_with_DASH_meta)
						tmp34 := checkDerefVar(var_clojure_DOT_core_doall)
						tmp35 := checkDerefVar(var_clojure_DOT_core_map)
						tmp36 := lang.Apply2(tmp35, v2, v4)
						tmp37 := lang.Apply1(tmp34, tmp36)
						tmp38 := checkDerefVar(var_clojure_DOT_core_meta)
						tmp39 := lang.Apply1(tmp38, v4)
						tmp40 := lang.Apply2(tmp33, tmp37, tmp39)
						tmp41 := lang.Apply1(v3, tmp40)
						tmp30 = tmp41
					} else {
						var tmp42 any
						tmp43 := checkDerefVar(var_clojure_DOT_core_instance_QMARK_)
						tmp44 := reflect.TypeOf((*lang.IRecord)(nil)).Elem()
						tmp45 := lang.Apply2(tmp43, tmp44, v4)
						if lang.IsTruthy(tmp45) {
							tmp46 := checkDerefVar(var_clojure_DOT_core_reduce)
							var tmp47 lang.FnFunc2
							tmp47 = lang.FnFunc2(func(p0, p1 any) any {
								v48 := p0
								_ = v48
								v49 := p1
								_ = v49
								tmp50 := checkDerefVar(var_clojure_DOT_core_conj)
								tmp51 := lang.Apply1(v2, v49)
								tmp52 := lang.Apply2(tmp50, v48, tmp51)
								return tmp52
							})
							tmp48 := lang.Apply3(tmp46, tmp47, v4, v4)
							tmp49 := lang.Apply1(v3, tmp48)
							tmp42 = tmp49
						} else {
							var tmp50 any
							tmp51 := checkDerefVar(var_clojure_DOT_core_coll_QMARK_)
							tmp52 := lang.Apply1(tmp51, v4)
							if lang.IsTruthy(tmp52) {
								tmp53 := checkDerefVar(var_clojure_DOT_core_into)
								tmp54 := checkDerefVar(var_clojure_DOT_core_empty)
								tmp55 := lang.Apply1(tmp54, v4)
								tmp56 := checkDerefVar(var_clojure_DOT_core_map)
								tmp57 := lang.Apply2(tmp56, v2, v4)
								tmp58 := lang.Apply2(tmp53, tmp55, tmp57)
								tmp59 := lang.Apply1(v3, tmp58)
								tmp50 = tmp59
							} else {
								tmp60 := lang.Apply1(v3, v4)
								tmp50 = tmp60
							}
							tmp42 = tmp50
						}
						tmp30 = tmp42
					}
					tmp18 = tmp30
				}
				tmp5 = tmp18
			}
			return tmp5
		})
		aotDirectFn9 = tmp1
		var_clojure_DOT_walk_walk = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion9 = var_clojure_DOT_walk_walk.RootVersion()
		var_clojure_DOT_walk_walk.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_inner, sym_outer, sym_form)), kw_doc, "Traverses form, an arbitrary data structure.  inner and outer are\n  functions.  Applies inner to each element of form, building up a\n  data structure of the same type, then applies outer to the result.\n  Recognizes all Clojure data structures. Consumes seqs as with doall.", kw_file, "clojure/walk.glj", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk), kw_end_DASH_column, int(10), kw_column, int(7), kw_line, int(35), kw_end_DASH_line, int(35))
		})
	}
}
