// Code generated by glojure codegen. DO NOT EDIT.

package walk

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	pkgmap4 "github.com/glojurelang/glojure/pkg/pkgmap"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc2
var aotDirectFn3 lang.FnFunc1
var aotDirectFn4 lang.FnFunc2
var aotDirectFn5 lang.FnFunc2
var aotDirectFn6 lang.FnFunc1
var aotDirectFn7 lang.FnFunc2
var aotDirectFn8 lang.FnFunc1
var aotDirectFn9 lang.FnFunc3

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("clojure/walk", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "clojure.walk"
func LoadNS() {
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_walk := lang.NewSymbolUnchecked("clojure.walk")
	sym_coll_QMARK_ := lang.NewSymbolUnchecked("coll?")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_doall := lang.NewSymbolUnchecked("doall")
	sym_empty := lang.NewSymbolUnchecked("empty")
	sym_f := lang.NewSymbolUnchecked("f")
	sym_form := lang.NewSymbolUnchecked("form")
	sym_identity := lang.NewSymbolUnchecked("identity")
	sym_inner := lang.NewSymbolUnchecked("inner")
	sym_into := lang.NewSymbolUnchecked("into")
	sym_key := lang.NewSymbolUnchecked("key")
	sym_keyword := lang.NewSymbolUnchecked("keyword")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_keywordize_DASH_keys := lang.NewSymbolUnchecked("keywordize-keys")
	sym_list := lang.NewSymbolUnchecked("list")
	sym_list_QMARK_ := lang.NewSymbolUnchecked("list?")
	sym_m := lang.NewSymbolUnchecked("m")
	sym_macroexpand := lang.NewSymbolUnchecked("macroexpand")
	sym_macroexpand_DASH_all := lang.NewSymbolUnchecked("macroexpand-all")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_map_QMARK_ := lang.NewSymbolUnchecked("map?")
	sym_meta := lang.NewSymbolUnchecked("meta")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_outer := lang.NewSymbolUnchecked("outer")
	sym_partial := lang.NewSymbolUnchecked("partial")
	sym_postwalk := lang.NewSymbolUnchecked("postwalk")
	sym_postwalk_DASH_demo := lang.NewSymbolUnchecked("postwalk-demo")
	sym_postwalk_DASH_replace := lang.NewSymbolUnchecked("postwalk-replace")
	sym_prewalk := lang.NewSymbolUnchecked("prewalk")
	sym_prewalk_DASH_demo := lang.NewSymbolUnchecked("prewalk-demo")
	sym_prewalk_DASH_replace := lang.NewSymbolUnchecked("prewalk-replace")
	sym_print := lang.NewSymbolUnchecked("print")
	sym_prn := lang.NewSymbolUnchecked("prn")
	sym_reduce := lang.NewSymbolUnchecked("reduce")
	sym_seq_QMARK_ := lang.NewSymbolUnchecked("seq?")
	sym_smap := lang.NewSymbolUnchecked("smap")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_stringify_DASH_keys := lang.NewSymbolUnchecked("stringify-keys")
	sym_val := lang.NewSymbolUnchecked("val")
	sym_walk := lang.NewSymbolUnchecked("walk")
	sym_with_DASH_meta := lang.NewSymbolUnchecked("with-meta")
	kw_added := lang.NewKeyword("added")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/coll?
	var_clojure_DOT_core_coll_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_coll_QMARK_)
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/doall
	var_clojure_DOT_core_doall := lang.InternVarName(sym_clojure_DOT_core, sym_doall)
	// var clojure.core/empty
	var_clojure_DOT_core_empty := lang.InternVarName(sym_clojure_DOT_core, sym_empty)
	// var clojure.core/identity
	var_clojure_DOT_core_identity := lang.InternVarName(sym_clojure_DOT_core, sym_identity)
	// var clojure.core/into
	var_clojure_DOT_core_into := lang.InternVarName(sym_clojure_DOT_core, sym_into)
	// var clojure.core/key
	var_clojure_DOT_core_key := lang.InternVarName(sym_clojure_DOT_core, sym_key)
	// var clojure.core/keyword
	var_clojure_DOT_core_keyword := lang.InternVarName(sym_clojure_DOT_core, sym_keyword)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/list
	var_clojure_DOT_core_list := lang.InternVarName(sym_clojure_DOT_core, sym_list)
	// var clojure.core/list?
	var_clojure_DOT_core_list_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_list_QMARK_)
	// var clojure.core/macroexpand
	var_clojure_DOT_core_macroexpand := lang.InternVarName(sym_clojure_DOT_core, sym_macroexpand)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/map?
	var_clojure_DOT_core_map_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_map_QMARK_)
	// var clojure.core/meta
	var_clojure_DOT_core_meta := lang.InternVarName(sym_clojure_DOT_core, sym_meta)
	// var clojure.core/name
	var_clojure_DOT_core_name := lang.InternVarName(sym_clojure_DOT_core, sym_name)
	// var clojure.core/partial
	var_clojure_DOT_core_partial := lang.InternVarName(sym_clojure_DOT_core, sym_partial)
	// var clojure.core/print
	var_clojure_DOT_core_print := lang.InternVarName(sym_clojure_DOT_core, sym_print)
	// var clojure.core/prn
	var_clojure_DOT_core_prn := lang.InternVarName(sym_clojure_DOT_core, sym_prn)
	// var clojure.core/reduce
	var_clojure_DOT_core_reduce := lang.InternVarName(sym_clojure_DOT_core, sym_reduce)
	// var clojure.core/seq?
	var_clojure_DOT_core_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_seq_QMARK_)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.core/val
	var_clojure_DOT_core_val := lang.InternVarName(sym_clojure_DOT_core, sym_val)
	// var clojure.core/with-meta
	var_clojure_DOT_core_with_DASH_meta := lang.InternVarName(sym_clojure_DOT_core, sym_with_DASH_meta)
	// var clojure.walk/keywordize-keys
	var_clojure_DOT_walk_keywordize_DASH_keys := lang.InternVarName(sym_clojure_DOT_walk, sym_keywordize_DASH_keys)
	// var clojure.walk/macroexpand-all
	var_clojure_DOT_walk_macroexpand_DASH_all := lang.InternVarName(sym_clojure_DOT_walk, sym_macroexpand_DASH_all)
	// var clojure.walk/postwalk
	var_clojure_DOT_walk_postwalk := lang.InternVarName(sym_clojure_DOT_walk, sym_postwalk)
	// var clojure.walk/postwalk-demo
	var_clojure_DOT_walk_postwalk_DASH_demo := lang.InternVarName(sym_clojure_DOT_walk, sym_postwalk_DASH_demo)
	// var clojure.walk/postwalk-replace
	var_clojure_DOT_walk_postwalk_DASH_replace := lang.InternVarName(sym_clojure_DOT_walk, sym_postwalk_DASH_replace)
	// var clojure.walk/prewalk
	var_clojure_DOT_walk_prewalk := lang.InternVarName(sym_clojure_DOT_walk, sym_prewalk)
	// var clojure.walk/prewalk-demo
	var_clojure_DOT_walk_prewalk_DASH_demo := lang.InternVarName(sym_clojure_DOT_walk, sym_prewalk_DASH_demo)
	// var clojure.walk/prewalk-replace
	var_clojure_DOT_walk_prewalk_DASH_replace := lang.InternVarName(sym_clojure_DOT_walk, sym_prewalk_DASH_replace)
	// var clojure.walk/stringify-keys
	var_clojure_DOT_walk_stringify_DASH_keys := lang.InternVarName(sym_clojure_DOT_walk, sym_stringify_DASH_keys)
	// var clojure.walk/walk
	var_clojure_DOT_walk_walk := lang.InternVarName(sym_clojure_DOT_walk, sym_walk)
	aotExternalFn1 := aotLinkFn1(var_clojure_DOT_core_string_QMARK_)
	aotExternalFn10 := aotLinkFn1(var_clojure_DOT_core_prn)
	aotExternalFn11 := aotLinkFn2(var_clojure_DOT_core_contains_QMARK_)
	aotExternalFn12 := aotLinkFn1(var_clojure_DOT_core_keyword_QMARK_)
	aotExternalFn13 := aotLinkFn1(var_clojure_DOT_core_name)
	aotExternalFn14 := aotLinkFn1(var_clojure_DOT_core_list_QMARK_)
	aotExternalFn15 := aotLinkFn2(var_clojure_DOT_core_with_DASH_meta)
	aotExternalFn16 := aotLinkFn2(var_clojure_DOT_core_apply)
	aotExternalFn17 := aotLinkFn1(var_clojure_DOT_core_meta)
	aotExternalFn19 := aotLinkFn1(var_clojure_DOT_core_key)
	aotExternalFn2 := aotLinkFn1(var_clojure_DOT_core_keyword)
	aotExternalFn20 := aotLinkFn1(var_clojure_DOT_core_val)
	aotExternalFn21 := aotLinkFn1(var_clojure_DOT_core_doall)
	aotExternalFn22 := aotLinkFn3(var_clojure_DOT_core_reduce)
	aotExternalFn24 := aotLinkFn1(var_clojure_DOT_core_coll_QMARK_)
	aotExternalFn25 := aotLinkFn1(var_clojure_DOT_core_empty)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_map_QMARK_)
	aotExternalFn4 := aotLinkFn2(var_clojure_DOT_core_into)
	aotExternalFn5 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn6 := aotLinkFn1(var_clojure_DOT_core_seq_QMARK_)
	aotExternalFn7 := aotLinkFn1(var_clojure_DOT_core_macroexpand)
	aotExternalFn8 := aotLinkFn2(var_clojure_DOT_core_partial)
	aotExternalFn9 := aotLinkFn1(var_clojure_DOT_core_print)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_clojure_DOT_walk)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// keywordize-keys
	{
		tmp0 := sym_keywordize_DASH_keys
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "f"
				var tmp4 lang.FnFunc1
				tmp4 = lang.FnFunc1(func(p0 any) any {
					v5 := p0
					_ = v5
					var tmp6 any
					{ // let
						// let binding "vec__765"
						var v7 any = v5
						_ = v7
						// let binding "k"
						tmp8 := runtime.RT.NthDefault(v7, lang.IntCast(int64(0)), nil)
						var v9 any = tmp8
						_ = v9
						// let binding "v"
						tmp10 := runtime.RT.NthDefault(v7, lang.IntCast(int64(1)), nil)
						var v11 any = tmp10
						_ = v11
						var tmp12 any
						tmp13 := aotExternalFn1(v9)
						if lang.IsTruthy(tmp13) {
							tmp14 := aotExternalFn2(v9)
							tmp15 := lang.NewVector(tmp14, v11)
							tmp12 = tmp15
						} else {
							tmp16 := lang.NewVector(v9, v11)
							tmp12 = tmp16
						}
						tmp6 = tmp12
					} // end let
					return tmp6
				})
				var v5 any = tmp4
				_ = v5
				var tmp6 lang.FnFunc1
				tmp6 = lang.FnFunc1(func(p0 any) any {
					v7 := p0
					_ = v7
					var tmp8 any
					tmp9 := aotExternalFn3(v7)
					if lang.IsTruthy(tmp9) {
						tmp10 := lang.NewMap()
						tmp11 := aotExternalFn5(v5, v7)
						tmp12 := aotExternalFn4(tmp10, tmp11)
						tmp8 = tmp12
					} else {
						tmp8 = v7
					}
					return tmp8
				})
				tmp7 := aotDirectFn2(tmp6, v2)
				tmp3 = tmp7
			} // end let
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_clojure_DOT_walk_keywordize_DASH_keys = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_keywordize_DASH_keys.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(94), kw_column, int(7), kw_end_DASH_line, int(94), kw_end_DASH_column, int(21), kw_arglists, lang.NewList(lang.NewVector(sym_m)), kw_doc, "Recursively transforms all map keys from strings to keywords.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// macroexpand-all
	{
		tmp0 := sym_macroexpand_DASH_all
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 lang.FnFunc1
			tmp3 = lang.FnFunc1(func(p0 any) any {
				v4 := p0
				_ = v4
				var tmp5 any
				tmp6 := aotExternalFn6(v4)
				if lang.IsTruthy(tmp6) {
					tmp7 := aotExternalFn7(v4)
					tmp5 = tmp7
				} else {
					tmp5 = v4
				}
				return tmp5
			})
			tmp4 := aotDirectFn5(tmp3, v2)
			return tmp4
		})
		aotDirectFn1 = tmp1
		var_clojure_DOT_walk_macroexpand_DASH_all = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_macroexpand_DASH_all.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(126), kw_column, int(7), kw_end_DASH_line, int(126), kw_end_DASH_column, int(21), kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_doc, "Recursively performs all possible macroexpansions in form.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// postwalk
	{
		tmp0 := sym_postwalk
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := checkDerefVar(var_clojure_DOT_walk_postwalk)
			tmp5 := aotExternalFn8(tmp4, v2)
			tmp6 := aotDirectFn9(tmp5, v2, v3)
			return tmp6
		})
		aotDirectFn2 = tmp1
		var_clojure_DOT_walk_postwalk = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_postwalk.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(53), kw_column, int(7), kw_end_DASH_line, int(53), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_f, sym_form)), kw_doc, "Performs a depth-first, post-order traversal of form.  Calls f on\n  each sub-form, uses f's return value in place of the original.\n  Recognizes all Clojure data structures. Consumes seqs as with doall.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// postwalk-demo
	{
		tmp0 := sym_postwalk_DASH_demo
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 lang.FnFunc1
			tmp3 = lang.FnFunc1(func(p0 any) any {
				v4 := p0
				_ = v4
				tmp5 := aotExternalFn9("Walked: ")
				_ = tmp5
				tmp6 := aotExternalFn10(v4)
				_ = tmp6
				return v4
			})
			tmp4 := aotDirectFn2(tmp3, v2)
			return tmp4
		})
		aotDirectFn3 = tmp1
		var_clojure_DOT_walk_postwalk_DASH_demo = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_postwalk_DASH_demo.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(80), kw_column, int(7), kw_end_DASH_line, int(80), kw_end_DASH_column, int(19), kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_doc, "Demonstrates the behavior of postwalk by printing each form as it is\n  walked.  Returns form.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// postwalk-replace
	{
		tmp0 := sym_postwalk_DASH_replace
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 lang.FnFunc1
			tmp4 = lang.FnFunc1(func(p0 any) any {
				v5 := p0
				_ = v5
				var tmp6 any
				tmp7 := aotExternalFn11(v2, v5)
				if lang.IsTruthy(tmp7) {
					tmp8 := lang.Apply1(v2, v5)
					tmp6 = tmp8
				} else {
					tmp6 = v5
				}
				return tmp6
			})
			tmp5 := aotDirectFn2(tmp4, v3)
			return tmp5
		})
		aotDirectFn4 = tmp1
		var_clojure_DOT_walk_postwalk_DASH_replace = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_postwalk_DASH_replace.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(118), kw_column, int(7), kw_end_DASH_line, int(118), kw_end_DASH_column, int(22), kw_arglists, lang.NewList(lang.NewVector(sym_smap, sym_form)), kw_doc, "Recursively transforms form by replacing keys in smap with their\n  values.  Like clojure/replace but works on any data structure.  Does\n  replacement at the leaves of the tree first.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// prewalk-demo
	{
		tmp0 := sym_prewalk_DASH_demo
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 lang.FnFunc1
			tmp3 = lang.FnFunc1(func(p0 any) any {
				v4 := p0
				_ = v4
				tmp5 := aotExternalFn9("Walked: ")
				_ = tmp5
				tmp6 := aotExternalFn10(v4)
				_ = tmp6
				return v4
			})
			tmp4 := aotDirectFn5(tmp3, v2)
			return tmp4
		})
		aotDirectFn6 = tmp1
		var_clojure_DOT_walk_prewalk_DASH_demo = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_prewalk_DASH_demo.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(87), kw_column, int(7), kw_end_DASH_line, int(87), kw_end_DASH_column, int(18), kw_arglists, lang.NewList(lang.NewVector(sym_form)), kw_doc, "Demonstrates the behavior of prewalk by printing each form as it is\n  walked.  Returns form.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// prewalk-replace
	{
		tmp0 := sym_prewalk_DASH_replace
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 lang.FnFunc1
			tmp4 = lang.FnFunc1(func(p0 any) any {
				v5 := p0
				_ = v5
				var tmp6 any
				tmp7 := aotExternalFn11(v2, v5)
				if lang.IsTruthy(tmp7) {
					tmp8 := lang.Apply1(v2, v5)
					tmp6 = tmp8
				} else {
					tmp6 = v5
				}
				return tmp6
			})
			tmp5 := aotDirectFn5(tmp4, v3)
			return tmp5
		})
		aotDirectFn7 = tmp1
		var_clojure_DOT_walk_prewalk_DASH_replace = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_prewalk_DASH_replace.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(110), kw_column, int(7), kw_end_DASH_line, int(110), kw_end_DASH_column, int(21), kw_arglists, lang.NewList(lang.NewVector(sym_smap, sym_form)), kw_doc, "Recursively transforms form by replacing keys in smap with their\n  values.  Like clojure/replace but works on any data structure.  Does\n  replacement at the root of the tree first.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// stringify-keys
	{
		tmp0 := sym_stringify_DASH_keys
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "f"
				var tmp4 lang.FnFunc1
				tmp4 = lang.FnFunc1(func(p0 any) any {
					v5 := p0
					_ = v5
					var tmp6 any
					{ // let
						// let binding "vec__769"
						var v7 any = v5
						_ = v7
						// let binding "k"
						tmp8 := runtime.RT.NthDefault(v7, lang.IntCast(int64(0)), nil)
						var v9 any = tmp8
						_ = v9
						// let binding "v"
						tmp10 := runtime.RT.NthDefault(v7, lang.IntCast(int64(1)), nil)
						var v11 any = tmp10
						_ = v11
						var tmp12 any
						tmp13 := aotExternalFn12(v9)
						if lang.IsTruthy(tmp13) {
							tmp14 := aotExternalFn13(v9)
							tmp15 := lang.NewVector(tmp14, v11)
							tmp12 = tmp15
						} else {
							tmp16 := lang.NewVector(v9, v11)
							tmp12 = tmp16
						}
						tmp6 = tmp12
					} // end let
					return tmp6
				})
				var v5 any = tmp4
				_ = v5
				var tmp6 lang.FnFunc1
				tmp6 = lang.FnFunc1(func(p0 any) any {
					v7 := p0
					_ = v7
					var tmp8 any
					tmp9 := aotExternalFn3(v7)
					if lang.IsTruthy(tmp9) {
						tmp10 := lang.NewMap()
						tmp11 := aotExternalFn5(v5, v7)
						tmp12 := aotExternalFn4(tmp10, tmp11)
						tmp8 = tmp12
					} else {
						tmp8 = v7
					}
					return tmp8
				})
				tmp7 := aotDirectFn2(tmp6, v2)
				tmp3 = tmp7
			} // end let
			return tmp3
		})
		aotDirectFn8 = tmp1
		var_clojure_DOT_walk_stringify_DASH_keys = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_stringify_DASH_keys.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(102), kw_column, int(7), kw_end_DASH_line, int(102), kw_end_DASH_column, int(20), kw_arglists, lang.NewList(lang.NewVector(sym_m)), kw_doc, "Recursively transforms all map keys from keywords to strings.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// prewalk
	{
		tmp0 := sym_prewalk
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := checkDerefVar(var_clojure_DOT_walk_prewalk)
			tmp5 := aotExternalFn8(tmp4, v2)
			tmp6 := checkDerefVar(var_clojure_DOT_core_identity)
			tmp7 := lang.Apply1(v2, v3)
			tmp8 := aotDirectFn9(tmp5, tmp6, tmp7)
			return tmp8
		})
		aotDirectFn5 = tmp1
		var_clojure_DOT_walk_prewalk = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_prewalk.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(61), kw_column, int(7), kw_end_DASH_line, int(61), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_f, sym_form)), kw_doc, "Like postwalk, but does pre-order traversal.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
	// walk
	{
		tmp0 := sym_walk
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			tmp6 := aotExternalFn14(v4)
			if lang.IsTruthy(tmp6) {
				tmp7 := checkDerefVar(var_clojure_DOT_core_list)
				tmp8 := aotExternalFn5(v2, v4)
				tmp9 := aotExternalFn16(tmp7, tmp8)
				tmp10 := aotExternalFn17(v4)
				tmp11 := aotExternalFn15(tmp9, tmp10)
				tmp12 := lang.Apply1(v3, tmp11)
				tmp5 = tmp12
			} else {
				var tmp13 any
				tmp14 := lang.IsInstance[lang.IMapEntry](v4)
				if lang.IsTruthy(tmp14) {
					tmp15, ok := pkgmap4.Get("clojure.lang.MapEntry.create")
					if !ok {
						panic(lang.NewIllegalArgumentError("unable to resolve host form: clojure.lang.MapEntry.create"))
					}
					tmp16 := aotExternalFn19(v4)
					tmp17 := lang.Apply1(v2, tmp16)
					tmp18 := aotExternalFn20(v4)
					tmp19 := lang.Apply1(v2, tmp18)
					tmp20 := lang.Apply2(tmp15, tmp17, tmp19)
					tmp21 := lang.Apply1(v3, tmp20)
					tmp13 = tmp21
				} else {
					var tmp22 any
					tmp23 := aotExternalFn6(v4)
					if lang.IsTruthy(tmp23) {
						tmp24 := aotExternalFn5(v2, v4)
						tmp25 := aotExternalFn21(tmp24)
						tmp26 := aotExternalFn17(v4)
						tmp27 := aotExternalFn15(tmp25, tmp26)
						tmp28 := lang.Apply1(v3, tmp27)
						tmp22 = tmp28
					} else {
						var tmp29 any
						tmp30 := lang.IsInstance[lang.IRecord](v4)
						if lang.IsTruthy(tmp30) {
							var tmp31 lang.FnFunc2
							tmp31 = lang.FnFunc2(func(p0, p1 any) any {
								v32 := p0
								_ = v32
								v33 := p1
								_ = v33
								tmp34 := lang.Apply1(v2, v33)
								tmp35 := lang.ConjAny(v32, tmp34)
								return tmp35
							})
							tmp32 := aotExternalFn22(tmp31, v4, v4)
							tmp33 := lang.Apply1(v3, tmp32)
							tmp29 = tmp33
						} else {
							var tmp34 any
							tmp35 := aotExternalFn24(v4)
							if lang.IsTruthy(tmp35) {
								tmp36 := aotExternalFn25(v4)
								tmp37 := aotExternalFn5(v2, v4)
								tmp38 := aotExternalFn4(tmp36, tmp37)
								tmp39 := lang.Apply1(v3, tmp38)
								tmp34 = tmp39
							} else {
								tmp40 := lang.Apply1(v3, v4)
								tmp34 = tmp40
							}
							tmp29 = tmp34
						}
						tmp22 = tmp29
					}
					tmp13 = tmp22
				}
				tmp5 = tmp13
			}
			return tmp5
		})
		aotDirectFn9 = tmp1
		var_clojure_DOT_walk_walk = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_walk_walk.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/walk.glj", kw_line, int(35), kw_column, int(7), kw_end_DASH_line, int(35), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_inner, sym_outer, sym_form)), kw_doc, "Traverses form, an arbitrary data structure.  inner and outer are\n  functions.  Applies inner to each element of form, building up a\n  data structure of the same type, then applies outer to the result.\n  Recognizes all Clojure data structures. Consumes seqs as with doall.", kw_added, "1.1", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_walk))
		})
	}
}
