// Code generated by glojure codegen. DO NOT EDIT.

package generated

import (
	"github.com/glojurelang/glojure/pkg/lang"
)

func init() {
	ns := lang.FindOrCreateNamespace(lang.NewSymbol("codegen.test.const-string"))
	_ = ns
	// const-string
	{
		v0 := lang.NewSymbol("const-string").WithMeta(lang.NewMap(lang.NewKeyword("hello"), true, lang.NewKeyword("file"), "codegen/test/const_string.glj", lang.NewKeyword("line"), int(3), lang.NewKeyword("column"), int(6), lang.NewKeyword("end-line"), int(3), lang.NewKeyword("end-column"), int(25))).(*lang.Symbol)
		ns.InternWithValue(v0, "Hello, World!", true)
	}
}
