// Code generated by glojure codegen. DO NOT EDIT.

package generated

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
)

func init() {
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	ns := lang.FindOrCreateNamespace(lang.NewSymbol("codegen.test.with-meta"))
	_ = ns
	// -main
	{
		tmp0 := lang.NewSymbol("-main").WithMeta(lang.NewMap(lang.NewKeyword("expected-output"), lang.NewKeyword("bar"), lang.NewKeyword("file"), "codegen/test/with_meta.glj", lang.NewKeyword("line"), int(3), lang.NewKeyword("column"), int(7), lang.NewKeyword("end-line"), int(3), lang.NewKeyword("end-column"), int(36), lang.NewKeyword("arglists"), lang.NewList(lang.NewVector()), lang.NewKeyword("ns"), lang.FindOrCreateNamespace(lang.NewSymbol("codegen.test.with-meta")))).(*lang.Symbol)
		var tmp2 lang.FnFunc
		tmp2 = lang.NewFnFunc(func(args ...any) any {
			if len(args) != 0 {
				panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
			}
			tmp3 := lang.FindNamespace(lang.NewSymbol("glojure.core"))
			tmp4 := tmp3.FindInternedVar(lang.NewSymbol("meta"))
			if tmp4.IsMacro() {
				panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", tmp4)))
			}
			tmp5 := tmp4.Get()
			tmp6 := lang.NewVector()
			tmp7 := lang.NewMap(lang.NewKeyword("foo"), lang.NewKeyword("bar"), lang.NewKeyword("file"), "codegen/test/with_meta.glj", lang.NewKeyword("line"), int(4), lang.NewKeyword("column"), int(15), lang.NewKeyword("end-line"), int(4), lang.NewKeyword("end-column"), int(28))
			tmp8 := lang.NewMap(lang.NewKeyword("file"), "codegen/test/with_meta.glj", lang.NewKeyword("line"), int(4), lang.NewKeyword("column"), int(16), lang.NewKeyword("end-line"), int(4), lang.NewKeyword("end-column"), int(26))
			tmp9, err := lang.WithMeta(tmp7, tmp8.(lang.IPersistentMap))
			if err != nil {
				panic(err)
			}
			tmp10, err := lang.WithMeta(tmp6, tmp9.(lang.IPersistentMap))
			if err != nil {
				panic(err)
			}
			tmp11 := lang.Apply(tmp5, []any{tmp10})
			tmp12 := lang.Apply(lang.NewKeyword("foo"), []any{tmp11})
			return tmp12
		})
		tmp2 = tmp2.WithMeta(lang.NewMap(lang.NewKeyword("rettag"), nil)).(lang.FnFunc)
		tmp1 := ns.InternWithValue(tmp0, tmp2, true)
		if tmp0.Meta() != nil {
			tmp1.SetMeta(tmp0.Meta().(lang.IPersistentMap))
		}
	}
}
