// Code generated by glojure codegen. DO NOT EDIT.

package types

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	ast4 "go/ast"
	parser5 "go/parser"
	reflect "reflect"
	strconv6 "strconv"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotRootVersion0 *lang.VarRootVersion
var aotDirectFn1 lang.ArityFn
var aotRootVersion1 *lang.VarRootVersion
var aotDirectFn1Arity1 lang.FnFunc1
var aotDirectFn1Arity2 lang.FnFunc2

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("glojure/go/types", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "glojure.go.types"
func LoadNS() {
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_AstType := lang.NewSymbolUnchecked("AstType")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_ast := lang.NewSymbolUnchecked("ast")
	sym_ast_DASH__GT_type := lang.NewSymbolUnchecked("ast->type")
	sym_butlast := lang.NewSymbolUnchecked("butlast")
	sym_class := lang.NewSymbolUnchecked("class")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_concat := lang.NewSymbolUnchecked("concat")
	sym_from_DASH_string := lang.NewSymbolUnchecked("from-string")
	sym_global_DASH_hierarchy := lang.NewSymbolUnchecked("global-hierarchy")
	sym_glojure_DOT_go_DOT_types := lang.NewSymbolUnchecked("glojure.go.types")
	sym_last := lang.NewSymbolUnchecked("last")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_not := lang.NewSymbolUnchecked("not")
	sym_repeat := lang.NewSymbolUnchecked("repeat")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_struct_DASH_field := lang.NewSymbolUnchecked("struct-field")
	sym_typ := lang.NewSymbolUnchecked("typ")
	sym_type_DASH_ast := lang.NewSymbolUnchecked("type-ast")
	kw_arglists := lang.NewKeyword("arglists")
	kw_ast_DASH__GT_type := lang.NewKeyword("ast->type")
	kw_column := lang.NewKeyword("column")
	kw_default := lang.NewKeyword("default")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_multis := lang.NewKeyword("multis")
	kw_ns := lang.NewKeyword("ns")
	kw_on_DASH_interface := lang.NewKeyword("on-interface")
	kw_private := lang.NewKeyword("private")
	kw_sigs := lang.NewKeyword("sigs")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/butlast
	var_clojure_DOT_core_butlast := lang.InternVarName(sym_clojure_DOT_core, sym_butlast)
	// var clojure.core/class
	var_clojure_DOT_core_class := lang.InternVarName(sym_clojure_DOT_core, sym_class)
	// var clojure.core/concat
	var_clojure_DOT_core_concat := lang.InternVarName(sym_clojure_DOT_core, sym_concat)
	// var clojure.core/last
	var_clojure_DOT_core_last := lang.InternVarName(sym_clojure_DOT_core, sym_last)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/not
	var_clojure_DOT_core_not := lang.InternVarName(sym_clojure_DOT_core, sym_not)
	// var clojure.core/repeat
	var_clojure_DOT_core_repeat := lang.InternVarName(sym_clojure_DOT_core, sym_repeat)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var glojure.go.types/AstType
	var_glojure_DOT_go_DOT_types_AstType := lang.InternVarName(sym_glojure_DOT_go_DOT_types, sym_AstType)
	// var glojure.go.types/ast->type
	var_glojure_DOT_go_DOT_types_ast_DASH__GT_type := lang.InternVarName(sym_glojure_DOT_go_DOT_types, sym_ast_DASH__GT_type)
	// var glojure.go.types/from-string
	var_glojure_DOT_go_DOT_types_from_DASH_string := lang.InternVarName(sym_glojure_DOT_go_DOT_types, sym_from_DASH_string)
	// var glojure.go.types/struct-field
	var_glojure_DOT_go_DOT_types_struct_DASH_field := lang.InternVarName(sym_glojure_DOT_go_DOT_types, sym_struct_DASH_field)
	aotExternalFn0 := aotLinkFn1(var_clojure_DOT_core_class)
	aotExternalFn1 := aotLinkFn2(var_clojure_DOT_core_apply)
	aotExternalFn10 := aotLinkFn1(var_clojure_DOT_core_last)
	aotExternalFn12 := aotLinkFn2(var_clojure_DOT_core_concat)
	aotExternalFn13 := aotLinkFn1(var_clojure_DOT_core_butlast)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_not)
	aotExternalFn4 := aotLinkFn1(var_clojure_DOT_core_string_QMARK_)
	aotExternalFn6 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn8 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn9 := aotLinkFn2(var_clojure_DOT_core_repeat)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_glojure_DOT_go_DOT_types)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	var closed0 any
	var closed1 any
	var closed2 any
	var closed3 any
	var closed4 any
	var closed5 any
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			var tmp2 any
			{ // let
				// let binding "name"
				tmp3, ok := lang.FieldOrMethod(v1, "Name")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Name")))
				}
				var tmp4 any
				switch reflect.TypeOf(tmp3).Kind() {
				case reflect.Func:
					tmp4 = lang.Apply(tmp3, nil)
				default:
					tmp4 = tmp3
				}
				var v5 any = tmp4
				_ = v5
				// let binding "typ"
				tmp6 := runtime.RT.Get(lang.BuiltinTypes, v5)
				var v7 any = tmp6
				_ = v7
				var tmp8 any
				if lang.IsTruthy(v7) {
				} else {
					tmp9 := lang.Apply2(fmt.Errorf, "unknown type %s", v5)
					panic(tmp9)
				}
				_ = tmp8
				tmp2 = v7
			} // end let
			return tmp2
		})
		closed0 = tmp0
	}
	// ast->type
	{
		tmp0 := sym_ast_DASH__GT_type
		var tmp2 lang.ArityFn
		tmp2 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v3 := args[0]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := aotExternalFn0(v3)
				return tmp5
			}),
			1,
		)
		// MultiFn ast->type
		tmp1 := lang.NewMultiFn("ast->type", tmp2, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		tmp3 := reflect.TypeOf((*ast4.Ident)(nil))
		var tmp4 lang.ArityFn
		tmp4 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v5 := args[0]
				_ = v5
				var v6 any = rest
				_ = v6
				tmp7 := lang.NewCons(v5, v6)
				tmp8 := aotExternalFn1(closed0, tmp7)
				return tmp8
			}),
			1,
		)
		tmp1.AddMethod(tmp3, tmp4)
		tmp5 := reflect.TypeOf((*ast4.ArrayType)(nil))
		var tmp6 lang.ArityFn
		tmp6 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v7 := args[0]
				_ = v7
				var v8 any = rest
				_ = v8
				tmp9 := lang.NewCons(v7, v8)
				tmp10 := aotExternalFn1(closed1, tmp9)
				return tmp10
			}),
			1,
		)
		tmp1.AddMethod(tmp5, tmp6)
		tmp7 := reflect.TypeOf((*ast4.MapType)(nil))
		var tmp8 lang.ArityFn
		tmp8 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v9 := args[0]
				_ = v9
				var v10 any = rest
				_ = v10
				tmp11 := lang.NewCons(v9, v10)
				tmp12 := aotExternalFn1(closed2, tmp11)
				return tmp12
			}),
			1,
		)
		tmp1.AddMethod(tmp7, tmp8)
		tmp9 := reflect.TypeOf((*ast4.ChanType)(nil))
		var tmp10 lang.ArityFn
		tmp10 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v11 := args[0]
				_ = v11
				var v12 any = rest
				_ = v12
				tmp13 := lang.NewCons(v11, v12)
				tmp14 := aotExternalFn1(closed3, tmp13)
				return tmp14
			}),
			1,
		)
		tmp1.AddMethod(tmp9, tmp10)
		tmp11 := reflect.TypeOf((*ast4.FuncType)(nil))
		var tmp12 lang.ArityFn
		tmp12 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v13 := args[0]
				_ = v13
				var v14 any = rest
				_ = v14
				tmp15 := lang.NewCons(v13, v14)
				tmp16 := aotExternalFn1(closed4, tmp15)
				return tmp16
			}),
			1,
		)
		tmp1.AddMethod(tmp11, tmp12)
		tmp13 := reflect.TypeOf((*ast4.StructType)(nil))
		var tmp14 lang.ArityFn
		tmp14 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v15 := args[0]
				_ = v15
				var v16 any = rest
				_ = v16
				tmp17 := lang.NewCons(v15, v16)
				tmp18 := aotExternalFn1(closed5, tmp17)
				return tmp18
			}),
			1,
		)
		tmp1.AddMethod(tmp13, tmp14)
		var_glojure_DOT_go_DOT_types_ast_DASH__GT_type = ns.InternWithValue(tmp0, tmp1, true)
		var_glojure_DOT_go_DOT_types_ast_DASH__GT_type.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "glojure/go/types.glj", kw_line, int(4), kw_column, int(4), kw_end_DASH_line, int(4), kw_end_DASH_column, int(12), kw_ns, lang.FindOrCreateNamespace(sym_glojure_DOT_go_DOT_types))
		})
	}
	// from-string
	{
		tmp0 := sym_from_DASH_string
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			tmp4 := aotExternalFn4(v2)
			tmp5 := aotExternalFn3(tmp4)
			if lang.IsTruthy(tmp5) {
				tmp6 := lang.Apply2(fmt.Errorf, "from-string: argument must be a string, got %T", v2)
				panic(tmp6)
			} else {
			}
			_ = tmp3
			var tmp7 any
			{ // let
				// let binding "vec__805"
				tmp8 := lang.Apply1(parser5.ParseExpr, v2)
				var v9 any = tmp8
				_ = v9
				// let binding "ast"
				tmp10 := runtime.RT.NthDefault(v9, lang.IntCast(int64(0)), nil)
				var v11 any = tmp10
				_ = v11
				// let binding "err"
				tmp12 := runtime.RT.NthDefault(v9, lang.IntCast(int64(1)), nil)
				var v13 any = tmp12
				_ = v13
				var tmp14 any
				if lang.IsTruthy(v13) {
					tmp15 := lang.Apply3(fmt.Errorf, "from-string: invalid type string '%s': %w", v2, v13)
					panic(tmp15)
				} else {
				}
				_ = tmp14
				tmp16 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
				tmp17 := lang.Apply1(tmp16, v11)
				tmp7 = tmp17
			} // end let
			return tmp7
		})
		aotDirectFn0 = tmp1
		var_glojure_DOT_go_DOT_types_from_DASH_string = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion0 = var_glojure_DOT_go_DOT_types_from_DASH_string.RootVersion()
		var_glojure_DOT_go_DOT_types_from_DASH_string.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "glojure/go/types.glj", kw_line, int(92), kw_column, int(7), kw_end_DASH_line, int(92), kw_end_DASH_column, int(17), kw_arglists, lang.NewList(lang.NewVector(sym_typ)), kw_doc, "Returns a Go type from a go type expression.", kw_ns, lang.FindOrCreateNamespace(sym_glojure_DOT_go_DOT_types))
		})
	}
	// struct-field
	{
		tmp0 := sym_struct_DASH_field
		var tmp1 lang.ArityFn
		aotDirectFn1Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := var_glojure_DOT_go_DOT_types_struct_DASH_field.RootVersion() == aotRootVersion1 && !var_glojure_DOT_go_DOT_types_struct_DASH_field.IsMacro()
			var tmp4 any
			if !tmp3 {
				tmp4 = checkDerefVar(var_glojure_DOT_go_DOT_types_struct_DASH_field)
			}
			var tmp5 any
			if tmp3 {
				tmp5 = aotDirectFn1Arity2(v2, nil)
			} else {
				tmp5 = lang.Apply2(tmp4, v2, nil)
			}
			return tmp5
		})
		aotDirectFn1Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "typ"
				tmp5 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
				tmp6 := lang.Apply1(tmp5, v2)
				var v7 any = tmp6
				_ = v7
				// let binding "name"
				var tmp8 any
				tmp9 := aotExternalFn6("", v3)
				if lang.IsTruthy(tmp9) {
				} else {
					tmp8 = v3
				}
				var v10 any = tmp8
				_ = v10
				// let binding "anonymous"
				tmp11 := lang.Identical(v10, nil)
				var v12 any = tmp11
				_ = v12
				// let binding "name"
				var tmp13 any
				{ // let
					// let binding "or__0__auto__"
					var v14 any = v10
					_ = v14
					var tmp15 any
					if lang.IsTruthy(v14) {
						tmp15 = v14
					} else {
						tmp16, ok := lang.FieldOrMethod(v7, "Name")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v7, "Name")))
						}
						var tmp17 any
						switch reflect.TypeOf(tmp16).Kind() {
						case reflect.Func:
							tmp17 = lang.Apply(tmp16, nil)
						default:
							tmp17 = tmp16
						}
						tmp15 = tmp17
					}
					tmp13 = tmp15
				} // end let
				var v14 any = tmp13
				_ = v14
				// let binding "sf"
				tmp15 := reflect.TypeOf((*reflect.StructField)(nil)).Elem()
				tmp16 := lang.Apply1(lang.Builtins["new"], tmp15)
				var v17 any = tmp16
				_ = v17
				// set! host field
				var tmp18 any
				{
					targetV := reflect.ValueOf(v17)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Type")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Type"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Type"))
					}
					valV := reflect.ValueOf(v7)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Type to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp18 = v7
				}
				_ = tmp18
				// set! host field
				var tmp19 any
				{
					targetV := reflect.ValueOf(v17)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Name")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Name"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Name"))
					}
					valV := reflect.ValueOf(v14)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Name to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp19 = v14
				}
				_ = tmp19
				var tmp20 any
				if lang.IsTruthy(v12) {
					// set! host field
					var tmp21 any
					{
						targetV := reflect.ValueOf(v17)
						if targetV.Kind() == reflect.Ptr {
							targetV = targetV.Elem()
						}
						fieldVal := targetV.FieldByName("Anonymous")
						if !fieldVal.IsValid() {
							panic(fmt.Errorf("no such field Anonymous"))
						}
						if !fieldVal.CanSet() {
							panic(fmt.Errorf("cannot set field Anonymous"))
						}
						valV := reflect.ValueOf(true)
						if !valV.IsValid() {
							switch fieldVal.Kind() {
							case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
								fieldVal.Set(reflect.Zero(fieldVal.Type()))
							default:
								panic(fmt.Errorf("cannot set field Anonymous to nil"))
							}
						} else {
							fieldVal.Set(valV)
						}
						tmp21 = true
					}
					tmp20 = tmp21
				} else {
				}
				_ = tmp20
				tmp22 := lang.Apply1(lang.Builtins["deref"], v17)
				tmp4 = tmp22
			} // end let
			return tmp4
		})
		tmp1 = lang.NewArityFn(
			nil,
			aotDirectFn1Arity1,
			aotDirectFn1Arity2,
			nil,
			nil,
			nil,
			0,
		)
		aotDirectFn1 = tmp1
		var_glojure_DOT_go_DOT_types_struct_DASH_field = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion1 = var_glojure_DOT_go_DOT_types_struct_DASH_field.RootVersion()
		var_glojure_DOT_go_DOT_types_struct_DASH_field.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "glojure/go/types.glj", kw_line, int(6), kw_column, int(8), kw_end_DASH_line, int(6), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_type_DASH_ast), lang.NewVector(sym_type_DASH_ast, sym_name)), kw_ns, lang.FindOrCreateNamespace(sym_glojure_DOT_go_DOT_types))
		})
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			var tmp2 any
			{ // let
				// let binding "len"
				tmp3, ok := lang.FieldOrMethod(v1, "Len")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Len")))
				}
				var tmp4 any
				switch reflect.TypeOf(tmp3).Kind() {
				case reflect.Func:
					tmp4 = lang.Apply(tmp3, nil)
				default:
					tmp4 = tmp3
				}
				var v5 any = tmp4
				_ = v5
				// let binding "elt"
				tmp6 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
				tmp7, ok := lang.FieldOrMethod(v1, "Elt")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Elt")))
				}
				var tmp8 any
				switch reflect.TypeOf(tmp7).Kind() {
				case reflect.Func:
					tmp8 = lang.Apply(tmp7, nil)
				default:
					tmp8 = tmp7
				}
				tmp9 := lang.Apply1(tmp6, tmp8)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				if lang.IsTruthy(v5) {
					tmp12, ok := lang.FieldOrMethod(v5, "Value")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v5, "Value")))
					}
					var tmp13 any
					switch reflect.TypeOf(tmp12).Kind() {
					case reflect.Func:
						tmp13 = lang.Apply(tmp12, nil)
					default:
						tmp13 = tmp12
					}
					tmp14 := lang.Apply1(strconv6.Atoi, tmp13)
					tmp15 := lang.First(tmp14)
					tmp16 := lang.Apply2(lang.Builtins["array-of"], tmp15, v10)
					tmp11 = tmp16
				} else {
					tmp17 := lang.Apply1(lang.Builtins["slice-of"], v10)
					tmp11 = tmp17
				}
				tmp2 = tmp11
			} // end let
			return tmp2
		})
		closed1 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			tmp2 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
			tmp3, ok := lang.FieldOrMethod(v1, "Key")
			if !ok {
				panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Key")))
			}
			var tmp4 any
			switch reflect.TypeOf(tmp3).Kind() {
			case reflect.Func:
				tmp4 = lang.Apply(tmp3, nil)
			default:
				tmp4 = tmp3
			}
			tmp5 := lang.Apply1(tmp2, tmp4)
			tmp6 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
			tmp7, ok := lang.FieldOrMethod(v1, "Value")
			if !ok {
				panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Value")))
			}
			var tmp8 any
			switch reflect.TypeOf(tmp7).Kind() {
			case reflect.Func:
				tmp8 = lang.Apply(tmp7, nil)
			default:
				tmp8 = tmp7
			}
			tmp9 := lang.Apply1(tmp6, tmp8)
			tmp10 := lang.Apply2(lang.Builtins["map-of"], tmp5, tmp9)
			return tmp10
		})
		closed2 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			var tmp2 any
			{ // let
				// let binding "dir"
				tmp3, ok := lang.FieldOrMethod(v1, "Dir")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Dir")))
				}
				var tmp4 any
				switch reflect.TypeOf(tmp3).Kind() {
				case reflect.Func:
					tmp4 = lang.Apply(tmp3, nil)
				default:
					tmp4 = tmp3
				}
				var v5 any = tmp4
				_ = v5
				// let binding "ctor"
				var tmp6 any
				tmp7 := aotExternalFn6(v5, ast4.SEND)
				if lang.IsTruthy(tmp7) {
					tmp6 = lang.Builtins["chan<--of"]
				} else {
					var tmp8 any
					tmp9 := aotExternalFn6(v5, ast4.RECV)
					if lang.IsTruthy(tmp9) {
						tmp8 = lang.Builtins["<-chan-of"]
					} else {
						tmp8 = lang.Builtins["chan-of"]
					}
					tmp6 = tmp8
				}
				var v10 any = tmp6
				_ = v10
				tmp11 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
				tmp12, ok := lang.FieldOrMethod(v1, "Value")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Value")))
				}
				var tmp13 any
				switch reflect.TypeOf(tmp12).Kind() {
				case reflect.Func:
					tmp13 = lang.Apply(tmp12, nil)
				default:
					tmp13 = tmp12
				}
				tmp14 := lang.Apply1(tmp11, tmp13)
				tmp15 := lang.Apply1(v10, tmp14)
				tmp2 = tmp15
			} // end let
			return tmp2
		})
		closed3 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			var tmp2 any
			{ // let
				// let binding "pl"
				var tmp3 any
				{ // let
					// let binding "or__0__auto__"
					tmp4, ok := lang.FieldOrMethod(v1, "Params")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Params")))
					}
					var tmp5 any
					switch reflect.TypeOf(tmp4).Kind() {
					case reflect.Func:
						tmp5 = lang.Apply(tmp4, nil)
					default:
						tmp5 = tmp4
					}
					var v6 any = tmp5
					_ = v6
					var tmp7 any
					if lang.IsTruthy(v6) {
						tmp7 = v6
					} else {
					}
					tmp3 = tmp7
				} // end let
				var v4 any = tmp3
				_ = v4
				// let binding "params"
				var tmp5 any
				{ // let
					// let binding "and__0__auto__"
					var v6 any = v4
					_ = v6
					var tmp7 any
					if lang.IsTruthy(v6) {
						tmp8 := checkDerefVar(var_clojure_DOT_core_concat)
						var tmp9 lang.FnFunc1
						tmp9 = lang.FnFunc1(func(p0 any) any {
							v10 := p0
							_ = v10
							tmp11, ok := lang.FieldOrMethod(v10, "Names")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v10, "Names")))
							}
							var tmp12 any
							switch reflect.TypeOf(tmp11).Kind() {
							case reflect.Func:
								tmp12 = lang.Apply(tmp11, nil)
							default:
								tmp12 = tmp11
							}
							tmp13 := lang.Apply1(lang.Builtins["len"], tmp12)
							tmp14 := lang.Numbers.Max(int64(1), tmp13)
							tmp15, ok := lang.FieldOrMethod(v10, "Type")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v10, "Type")))
							}
							var tmp16 any
							switch reflect.TypeOf(tmp15).Kind() {
							case reflect.Func:
								tmp16 = lang.Apply(tmp15, nil)
							default:
								tmp16 = tmp15
							}
							tmp17 := aotExternalFn9(tmp14, tmp16)
							return tmp17
						})
						tmp10, ok := lang.FieldOrMethod(v4, "List")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v4, "List")))
						}
						var tmp11 any
						switch reflect.TypeOf(tmp10).Kind() {
						case reflect.Func:
							tmp11 = lang.Apply(tmp10, nil)
						default:
							tmp11 = tmp10
						}
						tmp12 := aotExternalFn8(tmp9, tmp11)
						tmp13 := aotExternalFn1(tmp8, tmp12)
						tmp7 = tmp13
					} else {
						tmp7 = v6
					}
					tmp5 = tmp7
				} // end let
				var v6 any = tmp5
				_ = v6
				// let binding "last-param"
				tmp7 := aotExternalFn10(v6)
				var v8 any = tmp7
				_ = v8
				// let binding "variadic"
				tmp9 := lang.IsInstance[*ast4.Ellipsis](v8)
				var v10 any = tmp9
				_ = v10
				// let binding "params"
				var tmp11 any
				tmp12 := aotExternalFn3(v10)
				if lang.IsTruthy(tmp12) {
					tmp13 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
					tmp14 := aotExternalFn8(tmp13, v6)
					tmp11 = tmp14
				} else {
					tmp15 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
					tmp16 := aotExternalFn13(v6)
					tmp17 := aotExternalFn8(tmp15, tmp16)
					tmp18 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
					tmp19, ok := lang.FieldOrMethod(v8, "Elt")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v8, "Elt")))
					}
					var tmp20 any
					switch reflect.TypeOf(tmp19).Kind() {
					case reflect.Func:
						tmp20 = lang.Apply(tmp19, nil)
					default:
						tmp20 = tmp19
					}
					tmp21 := lang.Apply1(tmp18, tmp20)
					tmp22 := lang.Apply1(lang.Builtins["slice-of"], tmp21)
					tmp23 := lang.NewVector(tmp22)
					tmp24 := aotExternalFn12(tmp17, tmp23)
					tmp11 = tmp24
				}
				var v25 any = tmp11
				_ = v25
				// let binding "rl"
				var tmp26 any
				{ // let
					// let binding "or__0__auto__"
					tmp27, ok := lang.FieldOrMethod(v1, "Results")
					if !ok {
						panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Results")))
					}
					var tmp28 any
					switch reflect.TypeOf(tmp27).Kind() {
					case reflect.Func:
						tmp28 = lang.Apply(tmp27, nil)
					default:
						tmp28 = tmp27
					}
					var v29 any = tmp28
					_ = v29
					var tmp30 any
					if lang.IsTruthy(v29) {
						tmp30 = v29
					} else {
					}
					tmp26 = tmp30
				} // end let
				var v27 any = tmp26
				_ = v27
				// let binding "results"
				var tmp28 any
				{ // let
					// let binding "and__0__auto__"
					var v29 any = v27
					_ = v29
					var tmp30 any
					if lang.IsTruthy(v29) {
						tmp31 := checkDerefVar(var_glojure_DOT_go_DOT_types_ast_DASH__GT_type)
						tmp32 := checkDerefVar(var_clojure_DOT_core_concat)
						var tmp33 lang.FnFunc1
						tmp33 = lang.FnFunc1(func(p0 any) any {
							v34 := p0
							_ = v34
							tmp35, ok := lang.FieldOrMethod(v34, "Names")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v34, "Names")))
							}
							var tmp36 any
							switch reflect.TypeOf(tmp35).Kind() {
							case reflect.Func:
								tmp36 = lang.Apply(tmp35, nil)
							default:
								tmp36 = tmp35
							}
							tmp37 := lang.Apply1(lang.Builtins["len"], tmp36)
							tmp38 := lang.Numbers.Max(int64(1), tmp37)
							tmp39, ok := lang.FieldOrMethod(v34, "Type")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v34, "Type")))
							}
							var tmp40 any
							switch reflect.TypeOf(tmp39).Kind() {
							case reflect.Func:
								tmp40 = lang.Apply(tmp39, nil)
							default:
								tmp40 = tmp39
							}
							tmp41 := aotExternalFn9(tmp38, tmp40)
							return tmp41
						})
						tmp34, ok := lang.FieldOrMethod(v27, "List")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v27, "List")))
						}
						var tmp35 any
						switch reflect.TypeOf(tmp34).Kind() {
						case reflect.Func:
							tmp35 = lang.Apply(tmp34, nil)
						default:
							tmp35 = tmp34
						}
						tmp36 := aotExternalFn8(tmp33, tmp35)
						tmp37 := aotExternalFn1(tmp32, tmp36)
						tmp38 := aotExternalFn8(tmp31, tmp37)
						tmp30 = tmp38
					} else {
						tmp30 = v29
					}
					tmp28 = tmp30
				} // end let
				var v29 any = tmp28
				_ = v29
				tmp30 := lang.Apply3(lang.Builtins["func-of"], v25, v29, v10)
				tmp2 = tmp30
			} // end let
			return tmp2
		})
		closed4 = tmp0
	}
	{
		var tmp0 lang.FnFunc1
		tmp0 = lang.FnFunc1(func(p0 any) any {
			v1 := p0
			_ = v1
			var tmp2 any
			{ // let
				// let binding "fields"
				tmp3, ok := lang.FieldOrMethod(v1, "Fields")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v1, "Fields")))
				}
				var tmp4 any
				switch reflect.TypeOf(tmp3).Kind() {
				case reflect.Func:
					tmp4 = lang.Apply(tmp3, nil)
				default:
					tmp4 = tmp3
				}
				tmp5, ok := lang.FieldOrMethod(tmp4, "List")
				if !ok {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", tmp4, "List")))
				}
				var tmp6 any
				switch reflect.TypeOf(tmp5).Kind() {
				case reflect.Func:
					tmp6 = lang.Apply(tmp5, nil)
				default:
					tmp6 = tmp5
				}
				var v7 any = tmp6
				_ = v7
				// let binding "struct-fields"
				tmp8 := checkDerefVar(var_clojure_DOT_core_concat)
				var tmp9 lang.FnFunc1
				tmp9 = lang.FnFunc1(func(p0 any) any {
					v10 := p0
					_ = v10
					var tmp11 any
					{ // let
						// let binding "names"
						var tmp12 lang.FnFunc1
						tmp12 = lang.FnFunc1(func(p0 any) any {
							v13 := p0
							_ = v13
							tmp14, ok := lang.FieldOrMethod(v13, "Name")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v13, "Name")))
							}
							var tmp15 any
							switch reflect.TypeOf(tmp14).Kind() {
							case reflect.Func:
								tmp15 = lang.Apply(tmp14, nil)
							default:
								tmp15 = tmp14
							}
							return tmp15
						})
						tmp13, ok := lang.FieldOrMethod(v10, "Names")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v10, "Names")))
						}
						var tmp14 any
						switch reflect.TypeOf(tmp13).Kind() {
						case reflect.Func:
							tmp14 = lang.Apply(tmp13, nil)
						default:
							tmp14 = tmp13
						}
						tmp15 := aotExternalFn8(tmp12, tmp14)
						var v16 any = tmp15
						_ = v16
						// let binding "type"
						tmp17, ok := lang.FieldOrMethod(v10, "Type")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v10, "Type")))
						}
						var tmp18 any
						switch reflect.TypeOf(tmp17).Kind() {
						case reflect.Func:
							tmp18 = lang.Apply(tmp17, nil)
						default:
							tmp18 = tmp17
						}
						var v19 any = tmp18
						_ = v19
						// let binding "tag"
						tmp20, ok := lang.FieldOrMethod(v10, "Type")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v10, "Type")))
						}
						var tmp21 any
						switch reflect.TypeOf(tmp20).Kind() {
						case reflect.Func:
							tmp21 = lang.Apply(tmp20, nil)
						default:
							tmp21 = tmp20
						}
						var v22 any = tmp21
						_ = v22
						var tmp23 any
						tmp24 := lang.IsEmpty(v16)
						if lang.IsTruthy(tmp24) {
							tmp25 := var_glojure_DOT_go_DOT_types_struct_DASH_field.RootVersion() == aotRootVersion1 && !var_glojure_DOT_go_DOT_types_struct_DASH_field.IsMacro()
							var tmp26 any
							if !tmp25 {
								tmp26 = checkDerefVar(var_glojure_DOT_go_DOT_types_struct_DASH_field)
							}
							var tmp27 any
							if tmp25 {
								tmp27 = aotDirectFn1Arity1(v19)
							} else {
								tmp27 = lang.Apply1(tmp26, v19)
							}
							tmp28 := lang.NewVector(tmp27)
							tmp23 = tmp28
						} else {
							var tmp29 any
							tmp30 := lang.Count(v16)
							tmp31 := aotExternalFn6(int64(1), tmp30)
							if lang.IsTruthy(tmp31) {
								tmp32 := var_glojure_DOT_go_DOT_types_struct_DASH_field.RootVersion() == aotRootVersion1 && !var_glojure_DOT_go_DOT_types_struct_DASH_field.IsMacro()
								var tmp33 any
								if !tmp32 {
									tmp33 = checkDerefVar(var_glojure_DOT_go_DOT_types_struct_DASH_field)
								}
								tmp34 := lang.First(v16)
								var tmp35 any
								if tmp32 {
									tmp35 = aotDirectFn1Arity2(v19, tmp34)
								} else {
									tmp35 = lang.Apply2(tmp33, v19, tmp34)
								}
								tmp36 := lang.NewVector(tmp35)
								tmp29 = tmp36
							} else {
								var tmp37 lang.FnFunc1
								tmp37 = lang.FnFunc1(func(p0 any) any {
									v38 := p0
									_ = v38
									tmp39 := var_glojure_DOT_go_DOT_types_struct_DASH_field.RootVersion() == aotRootVersion1 && !var_glojure_DOT_go_DOT_types_struct_DASH_field.IsMacro()
									var tmp40 any
									if !tmp39 {
										tmp40 = checkDerefVar(var_glojure_DOT_go_DOT_types_struct_DASH_field)
									}
									var tmp41 any
									if tmp39 {
										tmp41 = aotDirectFn1Arity2(v19, v38)
									} else {
										tmp41 = lang.Apply2(tmp40, v19, v38)
									}
									return tmp41
								})
								tmp38 := aotExternalFn8(tmp37, v16)
								tmp29 = tmp38
							}
							tmp23 = tmp29
						}
						tmp11 = tmp23
					} // end let
					return tmp11
				})
				tmp10 := aotExternalFn8(tmp9, v7)
				tmp11 := aotExternalFn1(tmp8, tmp10)
				var v12 any = tmp11
				_ = v12
				tmp13 := lang.Apply1(reflect.StructOf, v12)
				tmp2 = tmp13
			} // end let
			return tmp2
		})
		closed5 = tmp0
	}
	// AstType
	{
		tmp0 := sym_AstType
		var tmp3 lang.ArityFn
		tmp3 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v4 := args[0]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := aotExternalFn0(v4)
				return tmp6
			}),
			1,
		)
		// MultiFn ast->type
		tmp2 := lang.NewMultiFn("ast->type", tmp3, kw_default, lang.FindOrCreateNamespace(sym_clojure_DOT_core).FindInternedVar(sym_global_DASH_hierarchy))
		tmp4 := reflect.TypeOf((*ast4.Ident)(nil))
		var tmp5 lang.ArityFn
		tmp5 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v6 := args[0]
				_ = v6
				var v7 any = rest
				_ = v7
				tmp8 := lang.NewCons(v6, v7)
				tmp9 := aotExternalFn1(closed0, tmp8)
				return tmp9
			}),
			1,
		)
		tmp2.AddMethod(tmp4, tmp5)
		tmp6 := reflect.TypeOf((*ast4.ArrayType)(nil))
		var tmp7 lang.ArityFn
		tmp7 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v8 := args[0]
				_ = v8
				var v9 any = rest
				_ = v9
				tmp10 := lang.NewCons(v8, v9)
				tmp11 := aotExternalFn1(closed1, tmp10)
				return tmp11
			}),
			1,
		)
		tmp2.AddMethod(tmp6, tmp7)
		tmp8 := reflect.TypeOf((*ast4.MapType)(nil))
		var tmp9 lang.ArityFn
		tmp9 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v10 := args[0]
				_ = v10
				var v11 any = rest
				_ = v11
				tmp12 := lang.NewCons(v10, v11)
				tmp13 := aotExternalFn1(closed2, tmp12)
				return tmp13
			}),
			1,
		)
		tmp2.AddMethod(tmp8, tmp9)
		tmp10 := reflect.TypeOf((*ast4.ChanType)(nil))
		var tmp11 lang.ArityFn
		tmp11 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v12 := args[0]
				_ = v12
				var v13 any = rest
				_ = v13
				tmp14 := lang.NewCons(v12, v13)
				tmp15 := aotExternalFn1(closed3, tmp14)
				return tmp15
			}),
			1,
		)
		tmp2.AddMethod(tmp10, tmp11)
		tmp12 := reflect.TypeOf((*ast4.FuncType)(nil))
		var tmp13 lang.ArityFn
		tmp13 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v14 := args[0]
				_ = v14
				var v15 any = rest
				_ = v15
				tmp16 := lang.NewCons(v14, v15)
				tmp17 := aotExternalFn1(closed4, tmp16)
				return tmp17
			}),
			1,
		)
		tmp2.AddMethod(tmp12, tmp13)
		tmp14 := reflect.TypeOf((*ast4.StructType)(nil))
		var tmp15 lang.ArityFn
		tmp15 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v16 := args[0]
				_ = v16
				var v17 any = rest
				_ = v17
				tmp18 := lang.NewCons(v16, v17)
				tmp19 := aotExternalFn1(closed5, tmp18)
				return tmp19
			}),
			1,
		)
		tmp2.AddMethod(tmp14, tmp15)
		tmp1 := lang.NewAtom(lang.NewMap(kw_multis, lang.NewMap(kw_ast_DASH__GT_type, tmp2), kw_on_DASH_interface, true, kw_sigs, lang.NewList(lang.NewList(sym_ast_DASH__GT_type, lang.NewVector(sym_ast)))))
		var_glojure_DOT_go_DOT_types_AstType = ns.InternWithValue(tmp0, tmp1, true)
		var_glojure_DOT_go_DOT_types_AstType.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "glojure/go/types.glj", kw_line, int(3), kw_column, int(14), kw_end_DASH_line, int(3), kw_end_DASH_column, int(20), kw_ns, lang.FindOrCreateNamespace(sym_glojure_DOT_go_DOT_types))
		})
	}
}
