// Code generated by glojure codegen. DO NOT EDIT.

package async

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	sync "sync"
	time4 "time"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc2
var aotDirectFn3 lang.FnFunc2
var aotDirectFn4 lang.ArityFn
var aotDirectFn5 lang.ArityFn
var aotDirectFn6 lang.ArityFn
var aotDirectFn6Arity0 lang.FnFunc0
var aotDirectFn6Arity1 lang.FnFunc1
var aotDirectFn6Arity2 lang.FnFunc2
var aotDirectFn6Arity3 lang.FnFunc3
var aotDirectFn7 lang.FnFunc1
var aotDirectFn8 lang.FnFunc1
var aotDirectFn9 lang.FnFunc0
var aotDirectFn10 lang.FnFunc2
var aotDirectFn11 lang.FnFunc2
var aotDirectFn12 lang.FnFunc2
var aotDirectFn13 lang.ArityFn
var aotDirectFn13Arity2 lang.FnFunc2
var aotDirectFn13Arity3 lang.FnFunc3
var aotDirectFn14 lang.FnFunc1
var aotDirectFn15 lang.FnFunc1
var aotDirectFn16 lang.FnFunc1
var aotDirectFn17 lang.FnFunc2
var aotDirectFn18 lang.FnFunc1

func aotLinkFn0(vr *lang.Var) lang.FnFunc0 {
	if vr.IsBound() {
		return aotLinkBoundFn0(vr)
	}
	var once sync.Once
	var linked lang.FnFunc0
	return func() any {
		if !vr.IsBound() {
			return lang.Apply0(checkDerefVar(vr))
		}
		once.Do(func() { linked = aotLinkBoundFn0(vr) })
		return linked()
	}
}

func aotLinkBoundFn0(vr *lang.Var) lang.FnFunc0 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc0); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn0); ok {
		return fixed.Invoke0
	}
	return func() any { return lang.Apply0(fn) }
}

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func aotLinkFn4(vr *lang.Var) lang.FnFunc4 {
	if vr.IsBound() {
		return aotLinkBoundFn4(vr)
	}
	var once sync.Once
	var linked lang.FnFunc4
	return func(p0 any, p1 any, p2 any, p3 any) any {
		if !vr.IsBound() {
			return lang.Apply4(checkDerefVar(vr), p0, p1, p2, p3)
		}
		once.Do(func() { linked = aotLinkBoundFn4(vr) })
		return linked(p0, p1, p2, p3)
	}
}

func aotLinkBoundFn4(vr *lang.Var) lang.FnFunc4 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc4); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn4); ok {
		return fixed.Invoke4
	}
	return func(p0 any, p1 any, p2 any, p3 any) any { return lang.Apply4(fn, p0, p1, p2, p3) }
}

func init() {
	runtime.RegisterNSLoader("clojure/core/async", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "clojure.core.async"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym__LT__BANG_ := lang.NewSymbolUnchecked("<!")
	sym__LT__BANG__BANG_ := lang.NewSymbolUnchecked("<!!")
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym__GT__BANG_ := lang.NewSymbolUnchecked(">!")
	sym__GT__BANG__BANG_ := lang.NewSymbolUnchecked(">!!")
	sym_alt_BANG_ := lang.NewSymbolUnchecked("alt!")
	sym_alt_BANG__BANG_ := lang.NewSymbolUnchecked("alt!!")
	sym_alts := lang.NewSymbolUnchecked("alts")
	sym_alts_BANG_ := lang.NewSymbolUnchecked("alts!")
	sym_alts_BANG__BANG_ := lang.NewSymbolUnchecked("alts!!")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_args := lang.NewSymbolUnchecked("args")
	sym_bindings := lang.NewSymbolUnchecked("bindings")
	sym_body := lang.NewSymbolUnchecked("body")
	sym_buf_DASH_or_DASH_n := lang.NewSymbolUnchecked("buf-or-n")
	sym_c__0__auto__ := lang.NewSymbolUnchecked("c__0__auto__")
	sym_chan := lang.NewSymbolUnchecked("chan")
	sym_check_DASH_unique_DASH_ports_BANG_ := lang.NewSymbolUnchecked("check-unique-ports!")
	sym_clauses := lang.NewSymbolUnchecked("clauses")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_core_DOT_async := lang.NewSymbolUnchecked("clojure.core.async")
	sym_clojure_DOT_core_DOT_async_SLASH__GT__BANG_ := lang.NewSymbolUnchecked("clojure.core.async/>!")
	sym_clojure_DOT_core_DOT_async_SLASH_alt_BANG_ := lang.NewSymbolUnchecked("clojure.core.async/alt!")
	sym_clojure_DOT_core_DOT_async_SLASH_alts_BANG_ := lang.NewSymbolUnchecked("clojure.core.async/alts!")
	sym_clojure_DOT_core_DOT_async_SLASH_chan := lang.NewSymbolUnchecked("clojure.core.async/chan")
	sym_clojure_DOT_core_DOT_async_SLASH_go := lang.NewSymbolUnchecked("clojure.core.async/go")
	sym_clojure_DOT_core_SLASH__EQ_ := lang.NewSymbolUnchecked("clojure.core/=")
	sym_clojure_DOT_core_SLASH_cond := lang.NewSymbolUnchecked("clojure.core/cond")
	sym_clojure_DOT_core_SLASH_fn := lang.NewSymbolUnchecked("clojure.core/fn")
	sym_clojure_DOT_core_SLASH_let := lang.NewSymbolUnchecked("clojure.core/let")
	sym_clojure_DOT_core_SLASH_loop := lang.NewSymbolUnchecked("clojure.core/loop")
	sym_clojure_DOT_core_SLASH_or := lang.NewSymbolUnchecked("clojure.core/or")
	sym_close_BANG_ := lang.NewSymbolUnchecked("close!")
	sym_close_QMARK_ := lang.NewSymbolUnchecked("close?")
	sym_concat := lang.NewSymbolUnchecked("concat")
	sym_conj := lang.NewSymbolUnchecked("conj")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_core := lang.NewSymbolUnchecked("core")
	sym_default_DASH_case := lang.NewSymbolUnchecked("default-case")
	sym_do := lang.NewSymbolUnchecked("do")
	sym_do_DASH_alt := lang.NewSymbolUnchecked("do-alt")
	sym_do_DASH_alts := lang.NewSymbolUnchecked("do-alts")
	sym_ex_DASH_handler := lang.NewSymbolUnchecked("ex-handler")
	sym_f__1__auto__ := lang.NewSymbolUnchecked("f__1__auto__")
	sym_filter := lang.NewSymbolUnchecked("filter")
	sym_first := lang.NewSymbolUnchecked("first")
	sym_from := lang.NewSymbolUnchecked("from")
	sym_gensym := lang.NewSymbolUnchecked("gensym")
	sym_go := lang.NewSymbolUnchecked("go")
	sym_go_DASH_loop := lang.NewSymbolUnchecked("go-loop")
	sym_go_SLASH__LT__DASH_chan_DASH_of := lang.NewSymbolUnchecked("go/<-chan-of")
	sym_go_SLASH_any := lang.NewSymbolUnchecked("go/any")
	sym_go_SLASH_go := lang.NewSymbolUnchecked("go/go")
	sym_identity := lang.NewSymbolUnchecked("identity")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_list := lang.NewSymbolUnchecked("list")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_mapcat := lang.NewSymbolUnchecked("mapcat")
	sym_msecs := lang.NewSymbolUnchecked("msecs")
	sym_not_EQ_ := lang.NewSymbolUnchecked("not=")
	sym_offer_BANG_ := lang.NewSymbolUnchecked("offer!")
	sym_opts := lang.NewSymbolUnchecked("opts")
	sym_partition := lang.NewSymbolUnchecked("partition")
	sym_pipe := lang.NewSymbolUnchecked("pipe")
	sym_poll_BANG_ := lang.NewSymbolUnchecked("poll!")
	sym_port := lang.NewSymbolUnchecked("port")
	sym_port_DASH_case := lang.NewSymbolUnchecked("port-case")
	sym_port_DASH_or_DASH_put := lang.NewSymbolUnchecked("port-or-put")
	sym_ports := lang.NewSymbolUnchecked("ports")
	sym_reduce := lang.NewSymbolUnchecked("reduce")
	sym_remove := lang.NewSymbolUnchecked("remove")
	sym_res__2__auto__ := lang.NewSymbolUnchecked("res__2__auto__")
	sym_rest := lang.NewSymbolUnchecked("rest")
	sym_seq_QMARK_ := lang.NewSymbolUnchecked("seq?")
	sym_set := lang.NewSymbolUnchecked("set")
	sym_timeout := lang.NewSymbolUnchecked("timeout")
	sym_to := lang.NewSymbolUnchecked("to")
	sym_to_DASH_array := lang.NewSymbolUnchecked("to-array")
	sym_try_DASH_put := lang.NewSymbolUnchecked("try-put")
	sym_try_DASH_take := lang.NewSymbolUnchecked("try-take")
	sym_val := lang.NewSymbolUnchecked("val")
	sym_val__0__auto__ := lang.NewSymbolUnchecked("val__0__auto__")
	sym_vec := lang.NewSymbolUnchecked("vec")
	sym_vector := lang.NewSymbolUnchecked("vector")
	sym_vector_QMARK_ := lang.NewSymbolUnchecked("vector?")
	sym_xform := lang.NewSymbolUnchecked("xform")
	kw_arglists := lang.NewKeyword("arglists")
	kw_as := lang.NewKeyword("as")
	kw_column := lang.NewKeyword("column")
	kw_default := lang.NewKeyword("default")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_macro := lang.NewKeyword("macro")
	kw_ns := lang.NewKeyword("ns")
	kw_priority := lang.NewKeyword("priority")
	kw_private := lang.NewKeyword("private")
	// var clojure.core.async/>!
	var_clojure_DOT_core_DOT_async__GT__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__GT__BANG_)
	// var clojure.core.async/>!!
	var_clojure_DOT_core_DOT_async__GT__BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__GT__BANG__BANG_)
	// var clojure.core.async/<!
	var_clojure_DOT_core_DOT_async__LT__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__LT__BANG_)
	// var clojure.core.async/<!!
	var_clojure_DOT_core_DOT_async__LT__BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__LT__BANG__BANG_)
	// var clojure.core.async/alt!
	var_clojure_DOT_core_DOT_async_alt_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alt_BANG_)
	// var clojure.core.async/alt!!
	var_clojure_DOT_core_DOT_async_alt_BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alt_BANG__BANG_)
	// var clojure.core.async/alts!
	var_clojure_DOT_core_DOT_async_alts_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alts_BANG_)
	// var clojure.core.async/alts!!
	var_clojure_DOT_core_DOT_async_alts_BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alts_BANG__BANG_)
	// var clojure.core.async/chan
	var_clojure_DOT_core_DOT_async_chan := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_chan)
	// var clojure.core.async/check-unique-ports!
	var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_check_DASH_unique_DASH_ports_BANG_)
	// var clojure.core.async/close!
	var_clojure_DOT_core_DOT_async_close_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_close_BANG_)
	// var clojure.core.async/default-case
	var_clojure_DOT_core_DOT_async_default_DASH_case := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_default_DASH_case)
	// var clojure.core.async/do-alt
	var_clojure_DOT_core_DOT_async_do_DASH_alt := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_do_DASH_alt)
	// var clojure.core.async/do-alts
	var_clojure_DOT_core_DOT_async_do_DASH_alts := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_do_DASH_alts)
	// var clojure.core.async/go
	var_clojure_DOT_core_DOT_async_go := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_go)
	// var clojure.core.async/go-loop
	var_clojure_DOT_core_DOT_async_go_DASH_loop := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_go_DASH_loop)
	// var clojure.core.async/offer!
	var_clojure_DOT_core_DOT_async_offer_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_offer_BANG_)
	// var clojure.core.async/pipe
	var_clojure_DOT_core_DOT_async_pipe := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_pipe)
	// var clojure.core.async/poll!
	var_clojure_DOT_core_DOT_async_poll_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_poll_BANG_)
	// var clojure.core.async/port-case
	var_clojure_DOT_core_DOT_async_port_DASH_case := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_port_DASH_case)
	// var clojure.core.async/timeout
	var_clojure_DOT_core_DOT_async_timeout := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_timeout)
	// var clojure.core.async/try-put
	var_clojure_DOT_core_DOT_async_try_DASH_put := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_try_DASH_put)
	// var clojure.core.async/try-take
	var_clojure_DOT_core_DOT_async_try_DASH_take := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_try_DASH_take)
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/concat
	var_clojure_DOT_core_concat := lang.InternVarName(sym_clojure_DOT_core, sym_concat)
	// var clojure.core/conj
	var_clojure_DOT_core_conj := lang.InternVarName(sym_clojure_DOT_core, sym_conj)
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/filter
	var_clojure_DOT_core_filter := lang.InternVarName(sym_clojure_DOT_core, sym_filter)
	// var clojure.core/first
	var_clojure_DOT_core_first := lang.InternVarName(sym_clojure_DOT_core, sym_first)
	// var clojure.core/gensym
	var_clojure_DOT_core_gensym := lang.InternVarName(sym_clojure_DOT_core, sym_gensym)
	// var clojure.core/identity
	var_clojure_DOT_core_identity := lang.InternVarName(sym_clojure_DOT_core, sym_identity)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/list
	var_clojure_DOT_core_list := lang.InternVarName(sym_clojure_DOT_core, sym_list)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/mapcat
	var_clojure_DOT_core_mapcat := lang.InternVarName(sym_clojure_DOT_core, sym_mapcat)
	// var clojure.core/not=
	var_clojure_DOT_core_not_EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym_not_EQ_)
	// var clojure.core/partition
	var_clojure_DOT_core_partition := lang.InternVarName(sym_clojure_DOT_core, sym_partition)
	// var clojure.core/reduce
	var_clojure_DOT_core_reduce := lang.InternVarName(sym_clojure_DOT_core, sym_reduce)
	// var clojure.core/remove
	var_clojure_DOT_core_remove := lang.InternVarName(sym_clojure_DOT_core, sym_remove)
	// var clojure.core/rest
	var_clojure_DOT_core_rest := lang.InternVarName(sym_clojure_DOT_core, sym_rest)
	// var clojure.core/seq?
	var_clojure_DOT_core_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_seq_QMARK_)
	// var clojure.core/set
	var_clojure_DOT_core_set := lang.InternVarName(sym_clojure_DOT_core, sym_set)
	// var clojure.core/to-array
	var_clojure_DOT_core_to_DASH_array := lang.InternVarName(sym_clojure_DOT_core, sym_to_DASH_array)
	// var clojure.core/vec
	var_clojure_DOT_core_vec := lang.InternVarName(sym_clojure_DOT_core, sym_vec)
	// var clojure.core/vector
	var_clojure_DOT_core_vector := lang.InternVarName(sym_clojure_DOT_core, sym_vector)
	// var clojure.core/vector?
	var_clojure_DOT_core_vector_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_vector_QMARK_)
	aotExternalFn10 := aotLinkFn2(var_clojure_DOT_core_not_EQ_)
	aotExternalFn12 := aotLinkFn2(var_clojure_DOT_core_partition)
	aotExternalFn13 := aotLinkFn1(var_clojure_DOT_core_keyword_QMARK_)
	aotExternalFn14 := aotLinkFn2(var_clojure_DOT_core_filter)
	aotExternalFn15 := aotLinkFn2(var_clojure_DOT_core_remove)
	aotExternalFn16 := aotLinkFn3(var_clojure_DOT_core_reduce)
	aotExternalFn17 := aotLinkFn0(var_clojure_DOT_core_gensym)
	aotExternalFn19 := aotLinkFn3(var_clojure_DOT_core_conj)
	aotExternalFn2 := aotLinkFn2(var_clojure_DOT_core_concat)
	aotExternalFn20 := aotLinkFn1(var_clojure_DOT_core_gensym)
	aotExternalFn21 := aotLinkFn3(var_clojure_DOT_core_concat)
	aotExternalFn22 := aotLinkFn2(var_clojure_DOT_core_apply)
	aotExternalFn23 := aotLinkFn2(var_clojure_DOT_core_mapcat)
	aotExternalFn24 := aotLinkFn4(var_clojure_DOT_core_concat)
	aotExternalFn25 := aotLinkFn1(var_clojure_DOT_core_concat)
	aotExternalFn26 := aotLinkFn1(var_clojure_DOT_core_rest)
	aotExternalFn27 := aotLinkFn1(var_clojure_DOT_core_vec)
	aotExternalFn28 := aotLinkFn2(var_clojure_DOT_core_contains_QMARK_)
	aotExternalFn29 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_seq_QMARK_)
	aotExternalFn30 := aotLinkFn0(var_clojure_DOT_core_concat)
	aotExternalFn5 := aotLinkFn1(var_clojure_DOT_core_to_DASH_array)
	aotExternalFn7 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn8 := aotLinkFn1(var_clojure_DOT_core_vector_QMARK_)
	aotExternalFn9 := aotLinkFn1(var_clojure_DOT_core_set)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_core, lang.FindOrCreateNamespace(sym_clojure_DOT_core))
	// >!
	{
		tmp0 := sym__GT__BANG_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := lang.Apply2(lang.Builtins["send"], v2, v3)
			_ = tmp4
			return true
		})
		aotDirectFn2 = tmp1
		var_clojure_DOT_core_DOT_async__GT__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async__GT__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(44), kw_column, int(7), kw_end_DASH_line, int(44), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_port, sym_val)), kw_doc, "puts a val into port. nil values are not allowed. Will park if no buffer space is available.\n  Returns true, or throws if port is already closed.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// >!!
	{
		tmp0 := sym__GT__BANG__BANG_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := lang.Apply2(lang.Builtins["send"], v2, v3)
			_ = tmp4
			return true
		})
		aotDirectFn3 = tmp1
		var_clojure_DOT_core_DOT_async__GT__BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async__GT__BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(51), kw_column, int(6), kw_end_DASH_line, int(51), kw_end_DASH_column, int(8), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// <!
	{
		tmp0 := sym__LT__BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "vec__690"
				tmp4 := lang.Apply1(lang.Builtins["recv"], v2)
				var v5 any = tmp4
				_ = v5
				// let binding "val"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "_"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				tmp3 = v7
			} // end let
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_clojure_DOT_core_DOT_async__LT__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async__LT__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(35), kw_column, int(7), kw_end_DASH_line, int(35), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_port)), kw_doc, "takes a val from port. Will return nil if closed. Will park if\n  nothing is available.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// <!!
	{
		tmp0 := sym__LT__BANG__BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "vec__690"
				tmp4 := lang.Apply1(lang.Builtins["recv"], v2)
				var v5 any = tmp4
				_ = v5
				// let binding "val"
				tmp6 := runtime.RT.NthDefault(v5, lang.IntCast(int64(0)), nil)
				var v7 any = tmp6
				_ = v7
				// let binding "_"
				tmp8 := runtime.RT.NthDefault(v5, lang.IntCast(int64(1)), nil)
				var v9 any = tmp8
				_ = v9
				tmp3 = v7
			} // end let
			return tmp3
		})
		aotDirectFn1 = tmp1
		var_clojure_DOT_core_DOT_async__LT__BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async__LT__BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(42), kw_column, int(6), kw_end_DASH_line, int(42), kw_end_DASH_column, int(8), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// alt!
	{
		tmp0 := sym_alt_BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(2, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := aotDirectFn10(sym_clojure_DOT_core_DOT_async_SLASH_alts_BANG_, v4)
				return tmp5
			}),
			2,
		)
		var_clojure_DOT_core_DOT_async_alt_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alt_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(250), kw_column, int(11), kw_end_DASH_line, int(250), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_clauses)), kw_doc, "Makes a single choice between one of several channel operations,\n  as if by alts!, returning the value of the result expr corresponding\n  to the operation completed.\n\n  Each clause takes the form of:\n\n  channel-op[s] result-expr\n\n  where channel-ops is one of:\n\n  take-port - a single port to take\n  [take-port | [put-port put-val] ...] - a vector of ports as per alts!\n  :default | :priority - an option for alts!\n\n  and result-expr is either a list beginning with a vector, whereupon that\n  vector will be treated as a binding for the [val port] return of the\n  operation, else any other expression.\n\n  (alt!\n    [c t] ([val ch] (foo ch val))\n    x ([v] v)\n    [[out val]] :wrote\n    :default 42)\n\n  Each option may appear at most once. The choice and parking\n  characteristics are those of alts!.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_macro, true)
		})
	}
	// alts!
	{
		tmp0 := sym_alts_BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				var v3 any = rest
				_ = v3
				var tmp4 any
				{ // let
					// let binding "map__706"
					var v5 any = v3
					_ = v5
					// let binding "map__706"
					var tmp6 any
					tmp7 := aotExternalFn3(v5)
					if lang.IsTruthy(tmp7) {
						var tmp8 any
						tmp9 := lang.Next(v5)
						if lang.IsTruthy(tmp9) {
							tmp10 := aotExternalFn5(v5)
							tmp11 := lang.Apply1(lang.NewPersistentArrayMapAsIfByAssoc, tmp10)
							tmp8 = tmp11
						} else {
							var tmp12 any
							tmp13 := lang.IsSeqTruthy(v5)
							if tmp13 {
								tmp14 := lang.First(v5)
								tmp12 = tmp14
							} else {
								tmp15 := lang.Apply0(lang.NewMap)
								tmp12 = tmp15
							}
							tmp8 = tmp12
						}
						tmp6 = tmp8
					} else {
						tmp6 = v5
					}
					var v16 any = tmp6
					_ = v16
					// let binding "opts"
					var v17 any = v16
					_ = v17
					tmp18 := aotDirectFn11(v2, v17)
					tmp4 = tmp18
				} // end let
				return tmp4
			}),
			1,
		)
		aotDirectFn4 = tmp1
		var_clojure_DOT_core_DOT_async_alts_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alts_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(185), kw_column, int(7), kw_end_DASH_line, int(185), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_ports, sym__AMP_, lang.NewMap(kw_as, sym_opts))), kw_doc, "Completes at most one of several channel operations. Must ports is a\n  vector of channel endpoints, which can be either a channel to take\n  from or a vector of [channel-to-put-to val-to-put], in any\n  combination.  Takes will be made as if by <!, and puts will be made\n  as if by >!. Unless the :priority option is true, if more than one\n  port operation is ready a non-deterministic choice will be made. If\n  no operation is ready and a :default value is\n  supplied, [default-val :default] will be returned, otherwise alts!\n  will park until the first operation to become ready\n  completes. Returns [val port] of the completed operation, where val\n  is the value taken for takes, and true for puts.\n\n  opts are passed as :key val ... Supported options:\n\n  :default val - the value to use if none of the operations are immediately ready\n  :priority true - (default nil) when true, the operations will be tried in order.\n\n  Note: there is no guarantee that the port exps or val exprs will be\n  used, nor in what order should they be, so they should not be\n  depended upon for side effects.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// alts!!
	{
		tmp0 := sym_alts_BANG__BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				var v3 any = rest
				_ = v3
				var tmp4 any
				{ // let
					// let binding "map__706"
					var v5 any = v3
					_ = v5
					// let binding "map__706"
					var tmp6 any
					tmp7 := aotExternalFn3(v5)
					if lang.IsTruthy(tmp7) {
						var tmp8 any
						tmp9 := lang.Next(v5)
						if lang.IsTruthy(tmp9) {
							tmp10 := aotExternalFn5(v5)
							tmp11 := lang.Apply1(lang.NewPersistentArrayMapAsIfByAssoc, tmp10)
							tmp8 = tmp11
						} else {
							var tmp12 any
							tmp13 := lang.IsSeqTruthy(v5)
							if tmp13 {
								tmp14 := lang.First(v5)
								tmp12 = tmp14
							} else {
								tmp15 := lang.Apply0(lang.NewMap)
								tmp12 = tmp15
							}
							tmp8 = tmp12
						}
						tmp6 = tmp8
					} else {
						tmp6 = v5
					}
					var v16 any = tmp6
					_ = v16
					// let binding "opts"
					var v17 any = v16
					_ = v17
					tmp18 := aotDirectFn11(v2, v17)
					tmp4 = tmp18
				} // end let
				return tmp4
			}),
			1,
		)
		aotDirectFn5 = tmp1
		var_clojure_DOT_core_DOT_async_alts_BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alts_BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(210), kw_column, int(6), kw_end_DASH_line, int(210), kw_end_DASH_column, int(11), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// chan
	{
		tmp0 := sym_chan
		var tmp1 lang.ArityFn
		aotDirectFn6Arity0 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn6Arity1(nil)
			return tmp2
		})
		aotDirectFn6Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn6Arity2(v2, nil)
			return tmp3
		})
		aotDirectFn6Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := aotDirectFn6Arity3(v2, v3, nil)
			return tmp4
		})
		aotDirectFn6Arity3 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			if lang.IsTruthy(v3) {
			} else {
			}
			_ = tmp5
			var tmp6 any
			if lang.IsTruthy(v3) {
				tmp7 := lang.Apply1(fmt.Errorf, "xform and ex-handler not yet supported")
				panic(tmp7)
			} else {
			}
			_ = tmp6
			tmp8 := lang.Apply1(lang.Builtins["chan-of"], lang.Builtins["any"])
			var tmp9 any
			{ // let
				// let binding "or__0__auto__"
				var v10 any = v2
				_ = v10
				var tmp11 any
				if lang.IsTruthy(v10) {
					tmp11 = v10
				} else {
					tmp11 = int64(0)
				}
				tmp9 = tmp11
			} // end let
			tmp10 := lang.Apply2(lang.Builtins["make"], tmp8, tmp9)
			return tmp10
		})
		tmp1 = lang.NewArityFn(
			aotDirectFn6Arity0,
			aotDirectFn6Arity1,
			aotDirectFn6Arity2,
			aotDirectFn6Arity3,
			nil,
			nil,
			0,
		)
		aotDirectFn6 = tmp1
		var_clojure_DOT_core_DOT_async_chan = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_chan.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(18), kw_column, int(7), kw_end_DASH_line, int(18), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_buf_DASH_or_DASH_n), lang.NewVector(sym_buf_DASH_or_DASH_n, sym_xform), lang.NewVector(sym_buf_DASH_or_DASH_n, sym_xform, sym_ex_DASH_handler)), kw_doc, "Creates a channel with an optional buffer, an optional transducer\n  (like (map f), (filter p) etc or a composition thereof), and an\n  optional exception-handler.  If buf-or-n is a number, will create\n  and use a fixed buffer of that size. If a transducer is supplied a\n  buffer must be specified. ex-handler must be a fn of one argument -\n  if an exception occurs during transformation it will be called with\n  the Throwable as an argument, and any non-nil return value will be\n  placed in the channel.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// check-unique-ports!
	{
		tmp0 := sym_check_DASH_unique_DASH_ports_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "chans"
				var tmp4 lang.FnFunc1
				tmp4 = lang.FnFunc1(func(p0 any) any {
					v5 := p0
					_ = v5
					var tmp6 any
					tmp7 := aotExternalFn8(v5)
					if lang.IsTruthy(tmp7) {
						tmp8 := lang.Apply1(v5, int64(0))
						tmp6 = tmp8
					} else {
						tmp6 = v5
					}
					return tmp6
				})
				tmp5 := aotExternalFn7(tmp4, v2)
				var v6 any = tmp5
				_ = v6
				// let binding "s"
				tmp7 := aotExternalFn9(v6)
				var v8 any = tmp7
				_ = v8
				var tmp9 any
				tmp10 := lang.Count(v8)
				tmp11 := lang.Count(v2)
				tmp12 := aotExternalFn10(tmp10, tmp11)
				if lang.IsTruthy(tmp12) {
					tmp13 := lang.Apply1(fmt.Errorf, "duplicate ports found in alt(s)! operation")
					panic(tmp13)
				} else {
				}
				tmp3 = tmp9
			} // end let
			return tmp3
		})
		aotDirectFn7 = tmp1
		var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(158), kw_column, int(8), kw_end_DASH_line, int(158), kw_end_DASH_column, int(26), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_ports)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// close!
	{
		tmp0 := sym_close_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.Apply1(lang.Builtins["close"], v2)
			return tmp3
		})
		aotDirectFn8 = tmp1
		var_clojure_DOT_core_DOT_async_close_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_close_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(53), kw_column, int(7), kw_end_DASH_line, int(53), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_chan)), kw_doc, "Closes a channel. The channel will no longer accept any puts (they\n  will be ignored). Data in the channel remains available for taking,\n  until exhausted, after which takes will return nil. If there are any\n  pending takes, they will be dispatched with nil. Closing a closed\n  channel will throw an exception.\n\n  Logically closing happens after all puts have been\n  delivered. Therefore, any blocked or parked puts will remain\n  blocked/parked until a taker releases them.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// default-case
	{
		tmp0 := sym_default_DASH_case
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			var tmp2 any
			{ // let
				// let binding "def"
				tmp3 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp4 := reflect.New(tmp3).Interface()
				var v5 any = tmp4
				_ = v5
				// set! host field
				var tmp6 any
				{
					targetV := reflect.ValueOf(v5)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(reflect.SelectDefault)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp6 = reflect.SelectDefault
				}
				_ = tmp6
				tmp2 = v5
			} // end let
			return tmp2
		})
		aotDirectFn9 = tmp1
		var_clojure_DOT_core_DOT_async_default_DASH_case = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_default_DASH_case.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(100), kw_column, int(8), kw_end_DASH_line, int(100), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector()), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// offer!
	{
		tmp0 := sym_offer_BANG_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "ret"
				tmp5 := aotDirectFn17(v2, v3)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					tmp7 = v6
				} else {
				}
				tmp4 = tmp7
			} // end let
			return tmp4
		})
		aotDirectFn12 = tmp1
		var_clojure_DOT_core_DOT_async_offer_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_offer_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(143), kw_column, int(7), kw_end_DASH_line, int(143), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_port, sym_val)), kw_doc, "Puts a val into port if it's possible to do so immediately.\n   nil values are not allowed. Never blocks. Returns true if offer succeeds.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// pipe
	{
		tmp0 := sym_pipe
		var tmp1 lang.ArityFn
		aotDirectFn13Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := aotDirectFn13Arity3(v2, v3, true)
			return tmp4
		})
		aotDirectFn13Arity3 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "c__0__auto__"
				tmp6 := aotDirectFn6Arity1(int64(1))
				var v7 any = tmp6
				_ = v7
				// let binding "f__1__auto__"
				var tmp8 lang.FnFunc0
				tmp8 = lang.FnFunc0(func() any {
					var tmp9 any
					{ // let
						// let binding "res__2__auto__"
						var tmp10 any
						{ // let
							for {
								var tmp11 any
								{ // let
									// let binding "v"
									tmp12 := aotDirectFn0(v2)
									var v13 any = tmp12
									_ = v13
									var tmp14 any
									tmp15 := lang.Identical(v13, nil)
									if lang.IsTruthy(tmp15) {
										var tmp16 any
										if lang.IsTruthy(v4) {
											tmp17 := aotDirectFn8(v3)
											tmp16 = tmp17
										} else {
										}
										tmp14 = tmp16
									} else {
										var tmp18 any
										tmp19 := aotDirectFn2(v3, v13)
										if lang.IsTruthy(tmp19) {
											continue
										} else {
										}
										tmp14 = tmp18
									}
									tmp11 = tmp14
								} // end let
								tmp10 = tmp11
								break
							}
						} // end let
						var v11 any = tmp10
						_ = v11
						tmp12 := aotDirectFn2(v7, v11)
						tmp9 = tmp12
					} // end let
					return tmp9
				})
				var v9 any = tmp8
				_ = v9
				go lang.Apply(v9, []any{})
				tmp10 := lang.Apply1(lang.Builtins["<-chan-of"], lang.Builtins["any"])
				tmp11 := lang.Apply1(tmp10, v7)
				tmp5 = tmp11
			} // end let
			_ = tmp5
			return v3
		})
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			aotDirectFn13Arity2,
			aotDirectFn13Arity3,
			nil,
			nil,
			0,
		)
		aotDirectFn13 = tmp1
		var_clojure_DOT_core_DOT_async_pipe = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_pipe.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(292), kw_column, int(7), kw_end_DASH_line, int(292), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_from, sym_to), lang.NewVector(sym_from, sym_to, sym_close_QMARK_)), kw_doc, "Takes elements from the from channel and supplies them to the to\n  channel. By default, the to channel will be closed when the from\n  channel closes, but can be determined by the close?  parameter. Will\n  stop consuming the from channel if the to channel closes", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// poll!
	{
		tmp0 := sym_poll_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "res"
				tmp4 := aotDirectFn18(v2)
				var v5 any = tmp4
				_ = v5
				// let binding "vec__699"
				var v6 any = v5
				_ = v6
				// let binding "val"
				tmp7 := runtime.RT.NthDefault(v6, lang.IntCast(int64(0)), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "ok"
				tmp9 := runtime.RT.NthDefault(v6, lang.IntCast(int64(1)), nil)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				if lang.IsTruthy(v10) {
					tmp11 = v8
				} else {
				}
				tmp3 = tmp11
			} // end let
			return tmp3
		})
		aotDirectFn14 = tmp1
		var_clojure_DOT_core_DOT_async_poll_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_poll_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(150), kw_column, int(7), kw_end_DASH_line, int(150), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_port)), kw_doc, "Takes a val from port if it's possible to do so immediately.\n   Never blocks. Returns value if successful, nil otherwise.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// port-case
	{
		tmp0 := sym_port_DASH_case
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "wport"
				var tmp4 any
				tmp5 := aotExternalFn8(v2)
				if lang.IsTruthy(tmp5) {
					tmp6 := lang.Apply1(v2, int64(0))
					tmp4 = tmp6
				} else {
				}
				var v7 any = tmp4
				_ = v7
				// let binding "port"
				var tmp8 any
				{ // let
					// let binding "or__0__auto__"
					var v9 any = v7
					_ = v9
					var tmp10 any
					if lang.IsTruthy(v9) {
						tmp10 = v9
					} else {
						tmp10 = v2
					}
					tmp8 = tmp10
				} // end let
				var v9 any = tmp8
				_ = v9
				// let binding "val"
				var tmp10 any
				if lang.IsTruthy(v7) {
					tmp11 := lang.Apply1(v2, int64(1))
					tmp12 := reflect.ValueOf(tmp11)
					tmp10 = tmp12
				} else {
				}
				var v13 any = tmp10
				_ = v13
				// let binding "select-case"
				tmp14 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp15 := reflect.New(tmp14).Interface()
				var v16 any = tmp15
				_ = v16
				tmp17 := reflect.ValueOf(v9)
				// set! host field
				var tmp18 any
				{
					targetV := reflect.ValueOf(v16)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Chan")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Chan"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Chan"))
					}
					valV := reflect.ValueOf(tmp17)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Chan to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp18 = tmp17
				}
				_ = tmp18
				var tmp19 any
				if lang.IsTruthy(v7) {
					tmp19 = reflect.SelectSend
				} else {
					tmp19 = reflect.SelectRecv
				}
				// set! host field
				var tmp20 any
				{
					targetV := reflect.ValueOf(v16)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(tmp19)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp20 = tmp19
				}
				_ = tmp20
				var tmp21 any
				if lang.IsTruthy(v7) {
					// set! host field
					var tmp22 any
					{
						targetV := reflect.ValueOf(v16)
						if targetV.Kind() == reflect.Ptr {
							targetV = targetV.Elem()
						}
						fieldVal := targetV.FieldByName("Send")
						if !fieldVal.IsValid() {
							panic(fmt.Errorf("no such field Send"))
						}
						if !fieldVal.CanSet() {
							panic(fmt.Errorf("cannot set field Send"))
						}
						valV := reflect.ValueOf(v13)
						if !valV.IsValid() {
							switch fieldVal.Kind() {
							case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
								fieldVal.Set(reflect.Zero(fieldVal.Type()))
							default:
								panic(fmt.Errorf("cannot set field Send to nil"))
							}
						} else {
							fieldVal.Set(valV)
						}
						tmp22 = v13
					}
					tmp21 = tmp22
				} else {
				}
				_ = tmp21
				tmp3 = v16
			} // end let
			return tmp3
		})
		aotDirectFn15 = tmp1
		var_clojure_DOT_core_DOT_async_port_DASH_case = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_port_DASH_case.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(106), kw_column, int(8), kw_end_DASH_line, int(106), kw_end_DASH_column, int(16), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_port_DASH_or_DASH_put)), kw_doc, "Returns a *reflect.SelectCase for the given channel operation.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// timeout
	{
		tmp0 := sym_timeout
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "ret"
				tmp4 := aotDirectFn6Arity0()
				var v5 any = tmp4
				_ = v5
				// let binding "after"
				tmp6 := lang.Apply1(lang.Builtins["int64"], time4.Millisecond)
				tmp7 := lang.Numbers.Multiply(v2, tmp6)
				tmp8 := lang.Apply1(time4.After, tmp7)
				var v9 any = tmp8
				_ = v9
				var tmp10 any
				{ // let
					// let binding "c__0__auto__"
					tmp11 := aotDirectFn6Arity1(int64(1))
					var v12 any = tmp11
					_ = v12
					// let binding "f__1__auto__"
					var tmp13 lang.FnFunc0
					tmp13 = lang.FnFunc0(func() any {
						var tmp14 any
						{ // let
							// let binding "res__2__auto__"
							tmp15 := aotDirectFn0(v9)
							_ = tmp15
							tmp16 := aotDirectFn8(v5)
							var v17 any = tmp16
							_ = v17
							tmp18 := aotDirectFn2(v12, v17)
							tmp14 = tmp18
						} // end let
						return tmp14
					})
					var v14 any = tmp13
					_ = v14
					go lang.Apply(v14, []any{})
					tmp15 := lang.Apply1(lang.Builtins["<-chan-of"], lang.Builtins["any"])
					tmp16 := lang.Apply1(tmp15, v12)
					tmp10 = tmp16
				} // end let
				_ = tmp10
				tmp3 = v5
			} // end let
			return tmp3
		})
		aotDirectFn16 = tmp1
		var_clojure_DOT_core_DOT_async_timeout = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_timeout.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(91), kw_column, int(7), kw_end_DASH_line, int(91), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_msecs)), kw_doc, "Returns a channel that will close after msecs", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// try-put
	{
		tmp0 := sym_try_DASH_put
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "sc"
				tmp5 := lang.NewVector(v2, v3)
				tmp6 := aotDirectFn15(tmp5)
				var v7 any = tmp6
				_ = v7
				// let binding "def"
				tmp8 := aotDirectFn9()
				var v9 any = tmp8
				_ = v9
				// let binding "vec__693"
				tmp10 := lang.NewVector(v7, v9)
				tmp11 := aotExternalFn7(lang.Builtins["deref"], tmp10)
				tmp12 := lang.Apply1(reflect.Select, tmp11)
				var v13 any = tmp12
				_ = v13
				// let binding "chosen"
				tmp14 := runtime.RT.NthDefault(v13, lang.IntCast(int64(0)), nil)
				var v15 any = tmp14
				_ = v15
				// let binding "val"
				tmp16 := runtime.RT.NthDefault(v13, lang.IntCast(int64(1)), nil)
				var v17 any = tmp16
				_ = v17
				// let binding "ok"
				tmp18 := runtime.RT.NthDefault(v13, lang.IntCast(int64(2)), nil)
				var v19 any = tmp18
				_ = v19
				tmp20 := aotExternalFn29(int64(0), v15)
				tmp4 = tmp20
			} // end let
			return tmp4
		})
		aotDirectFn17 = tmp1
		var_clojure_DOT_core_DOT_async_try_DASH_put = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_try_DASH_put.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(118), kw_column, int(8), kw_end_DASH_line, int(118), kw_end_DASH_column, int(14), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_port, sym_val)), kw_doc, "Returns true if val was sent on the port, false if sending would\n  block", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// try-take
	{
		tmp0 := sym_try_DASH_take
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "sc"
				tmp4 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp5 := reflect.New(tmp4).Interface()
				var v6 any = tmp5
				_ = v6
				// let binding "_"
				// set! host field
				var tmp7 any
				{
					targetV := reflect.ValueOf(v6)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(reflect.SelectRecv)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp7 = reflect.SelectRecv
				}
				_ = tmp7
				tmp8 := reflect.ValueOf(v2)
				// set! host field
				var tmp9 any
				{
					targetV := reflect.ValueOf(v6)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Chan")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Chan"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Chan"))
					}
					valV := reflect.ValueOf(tmp8)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Chan to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp9 = tmp8
				}
				var v10 any = tmp9
				_ = v10
				// let binding "def"
				tmp11 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp12 := reflect.New(tmp11).Interface()
				var v13 any = tmp12
				_ = v13
				// let binding "_"
				// set! host field
				var tmp14 any
				{
					targetV := reflect.ValueOf(v13)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(reflect.SelectDefault)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp14 = reflect.SelectDefault
				}
				var v15 any = tmp14
				_ = v15
				// let binding "vec__696"
				tmp16 := lang.NewVector(v6, v13)
				tmp17 := aotExternalFn7(lang.Builtins["deref"], tmp16)
				tmp18 := lang.Apply1(reflect.Select, tmp17)
				var v19 any = tmp18
				_ = v19
				// let binding "chosen"
				tmp20 := runtime.RT.NthDefault(v19, lang.IntCast(int64(0)), nil)
				var v21 any = tmp20
				_ = v21
				// let binding "val"
				tmp22 := runtime.RT.NthDefault(v19, lang.IntCast(int64(1)), nil)
				var v23 any = tmp22
				_ = v23
				// let binding "ok"
				tmp24 := runtime.RT.NthDefault(v19, lang.IntCast(int64(2)), nil)
				var v25 any = tmp24
				_ = v25
				var tmp26 any
				tmp27 := aotExternalFn29(int64(1), v21)
				if lang.IsTruthy(tmp27) {
				} else {
					var tmp28 any
					if lang.IsTruthy(v25) {
						tmp29, ok := lang.FieldOrMethod(v23, "Interface")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v23, "Interface")))
						}
						var tmp30 any
						switch reflect.TypeOf(tmp29).Kind() {
						case reflect.Func:
							tmp30 = lang.Apply(tmp29, nil)
						default:
							tmp30 = tmp29
						}
						tmp31 := lang.NewVector(tmp30, true)
						tmp28 = tmp31
					} else {
						tmp32 := lang.NewVector(nil, false)
						tmp28 = tmp32
					}
					tmp26 = tmp28
				}
				tmp3 = tmp26
			} // end let
			return tmp3
		})
		aotDirectFn18 = tmp1
		var_clojure_DOT_core_DOT_async_try_DASH_take = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_try_DASH_take.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(127), kw_column, int(8), kw_end_DASH_line, int(127), kw_end_DASH_column, int(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_port)), kw_doc, "Returns [val true] if val was received from the port, [nil false] if the channel was closed,\n  and nil if receiving would block.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// do-alts
	{
		tmp0 := sym_do_DASH_alts
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := aotDirectFn7(v2)
			_ = tmp4
			var tmp5 any
			{ // let
				// let binding "ports"
				tmp6 := aotExternalFn27(v2)
				var v7 any = tmp6
				_ = v7
				// let binding "n"
				tmp8 := lang.Count(v7)
				var v9 any = tmp8
				_ = v9
				// let binding "priority"
				tmp10 := kw_priority.Invoke1(v3)
				var v11 any = tmp10
				_ = v11
				// let binding "selects"
				tmp12 := checkDerefVar(var_clojure_DOT_core_DOT_async_port_DASH_case)
				tmp13 := aotExternalFn7(tmp12, v7)
				var v14 any = tmp13
				_ = v14
				// let binding "selects"
				var tmp15 any
				tmp16 := aotExternalFn28(v3, kw_default)
				if lang.IsTruthy(tmp16) {
					tmp17 := aotExternalFn27(v14)
					tmp18 := aotDirectFn9()
					tmp19 := lang.ConjAny(tmp17, tmp18)
					tmp15 = tmp19
				} else {
					tmp15 = v14
				}
				var v20 any = tmp15
				_ = v20
				// let binding "def"
				tmp21 := aotDirectFn9()
				var v22 any = tmp21
				_ = v22
				// let binding "vec__702"
				tmp23 := aotExternalFn7(lang.Builtins["deref"], v20)
				tmp24 := lang.Apply1(reflect.Select, tmp23)
				var v25 any = tmp24
				_ = v25
				// let binding "chosen-idx"
				tmp26 := runtime.RT.NthDefault(v25, lang.IntCast(int64(0)), nil)
				var v27 any = tmp26
				_ = v27
				// let binding "val"
				tmp28 := runtime.RT.NthDefault(v25, lang.IntCast(int64(1)), nil)
				var v29 any = tmp28
				_ = v29
				// let binding "ok"
				tmp30 := runtime.RT.NthDefault(v25, lang.IntCast(int64(2)), nil)
				var v31 any = tmp30
				_ = v31
				// let binding "chosen"
				tmp32 := runtime.RT.Get(v7, v27)
				var v33 any = tmp32
				_ = v33
				var tmp34 any
				tmp35 := aotExternalFn8(v33)
				if lang.IsTruthy(tmp35) {
					tmp36 := lang.Apply1(v33, int64(0))
					tmp37 := lang.NewVector(true, tmp36)
					tmp34 = tmp37
				} else {
					var tmp38 any
					tmp39 := aotExternalFn29(v9, v27)
					if lang.IsTruthy(tmp39) {
						tmp40 := kw_default.Invoke1(v3)
						tmp41 := lang.NewVector(tmp40, kw_default)
						tmp38 = tmp41
					} else {
						var tmp42 any
						if lang.IsTruthy(v31) {
							tmp43, ok := lang.FieldOrMethod(v29, "Interface")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v29, "Interface")))
							}
							var tmp44 any
							switch reflect.TypeOf(tmp43).Kind() {
							case reflect.Func:
								tmp44 = lang.Apply(tmp43, nil)
							default:
								tmp44 = tmp43
							}
							tmp42 = tmp44
						} else {
						}
						tmp45 := lang.NewVector(tmp42, v33)
						tmp38 = tmp45
					}
					tmp34 = tmp38
				}
				tmp5 = tmp34
			} // end let
			return tmp5
		})
		aotDirectFn11 = tmp1
		var_clojure_DOT_core_DOT_async_do_DASH_alts = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_do_DASH_alts.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(165), kw_column, int(8), kw_end_DASH_line, int(165), kw_end_DASH_column, int(14), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_ports, sym_opts)), kw_doc, "returns derefable [val port] if immediate, nil if enqueued", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// alt!!
	{
		tmp0 := sym_alt_BANG__BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(2, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_list)
				tmp6 := lang.Apply1(tmp5, sym_clojure_DOT_core_DOT_async_SLASH_alt_BANG_)
				tmp7 := aotExternalFn2(tmp6, v4)
				tmp8 := lang.Seq(tmp7)
				return tmp8
			}),
			2,
		)
		var_clojure_DOT_core_DOT_async_alt_BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alt_BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(281), kw_column, int(11), kw_end_DASH_line, int(281), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_macro, true)
		})
	}
	// do-alt
	{
		tmp0 := sym_do_DASH_alt
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "clauses"
				tmp5 := aotExternalFn12(int64(2), v3)
				var v6 any = tmp5
				_ = v6
				// let binding "opt?"
				var tmp7 lang.FnFunc1
				tmp7 = lang.FnFunc1(func(p0 any) any {
					v8 := p0
					_ = v8
					tmp9 := lang.First(v8)
					tmp10 := aotExternalFn13(tmp9)
					return tmp10
				})
				var v8 any = tmp7
				_ = v8
				// let binding "opts"
				tmp9 := aotExternalFn14(v8, v6)
				var v10 any = tmp9
				_ = v10
				// let binding "clauses"
				tmp11 := aotExternalFn15(v8, v6)
				var v12 any = tmp11
				_ = v12
				// let binding "vec__707"
				var tmp13 lang.FnFunc2
				tmp13 = lang.FnFunc2(func(p0, p1 any) any {
					v14 := p0
					_ = v14
					v15 := p1
					_ = v15
					var tmp16 any
					{ // let
						// let binding "vec__712"
						var v17 any = v14
						_ = v17
						// let binding "clauses"
						tmp18 := runtime.RT.NthDefault(v17, lang.IntCast(int64(0)), nil)
						var v19 any = tmp18
						_ = v19
						// let binding "bindings"
						tmp20 := runtime.RT.NthDefault(v17, lang.IntCast(int64(1)), nil)
						var v21 any = tmp20
						_ = v21
						// let binding "vec__715"
						var v22 any = v15
						_ = v22
						// let binding "ports"
						tmp23 := runtime.RT.NthDefault(v22, lang.IntCast(int64(0)), nil)
						var v24 any = tmp23
						_ = v24
						// let binding "expr"
						tmp25 := runtime.RT.NthDefault(v22, lang.IntCast(int64(1)), nil)
						var v26 any = tmp25
						_ = v26
						var tmp27 any
						{ // let
							// let binding "ports"
							var tmp28 any
							tmp29 := aotExternalFn8(v24)
							if lang.IsTruthy(tmp29) {
								tmp28 = v24
							} else {
								tmp30 := lang.NewVector(v24)
								tmp28 = tmp30
							}
							var v31 any = tmp28
							_ = v31
							// let binding "vec__718"
							var tmp32 lang.FnFunc2
							tmp32 = lang.FnFunc2(func(p0, p1 any) any {
								v33 := p0
								_ = v33
								v34 := p1
								_ = v34
								var tmp35 any
								{ // let
									// let binding "vec__722"
									var v36 any = v33
									_ = v36
									// let binding "ports"
									tmp37 := runtime.RT.NthDefault(v36, lang.IntCast(int64(0)), nil)
									var v38 any = tmp37
									_ = v38
									// let binding "bindings"
									tmp39 := runtime.RT.NthDefault(v36, lang.IntCast(int64(1)), nil)
									var v40 any = tmp39
									_ = v40
									var tmp41 any
									tmp42 := aotExternalFn8(v34)
									if lang.IsTruthy(tmp42) {
										var tmp43 any
										{ // let
											// let binding "vec__725"
											var v44 any = v34
											_ = v44
											// let binding "port"
											tmp45 := runtime.RT.NthDefault(v44, lang.IntCast(int64(0)), nil)
											var v46 any = tmp45
											_ = v46
											// let binding "val"
											tmp47 := runtime.RT.NthDefault(v44, lang.IntCast(int64(1)), nil)
											var v48 any = tmp47
											_ = v48
											// let binding "gp"
											tmp49 := aotExternalFn17()
											var v50 any = tmp49
											_ = v50
											// let binding "gv"
											tmp51 := aotExternalFn17()
											var v52 any = tmp51
											_ = v52
											tmp53 := lang.NewVector(v50, v52)
											tmp54 := lang.ConjAny(v38, tmp53)
											tmp55 := lang.NewVector(v50, v46)
											tmp56 := lang.NewVector(v52, v48)
											tmp57 := aotExternalFn19(v40, tmp55, tmp56)
											tmp58 := lang.NewVector(tmp54, tmp57)
											tmp43 = tmp58
										} // end let
										tmp41 = tmp43
									} else {
										var tmp44 any
										{ // let
											// let binding "gp"
											tmp45 := aotExternalFn17()
											var v46 any = tmp45
											_ = v46
											tmp47 := lang.ConjAny(v38, v46)
											tmp48 := lang.NewVector(v46, v34)
											tmp49 := lang.ConjAny(v40, tmp48)
											tmp50 := lang.NewVector(tmp47, tmp49)
											tmp44 = tmp50
										} // end let
										tmp41 = tmp44
									}
									tmp35 = tmp41
								} // end let
								return tmp35
							})
							tmp33 := lang.NewVector()
							tmp34 := lang.NewVector(tmp33, v21)
							tmp35 := aotExternalFn16(tmp32, tmp34, v31)
							var v36 any = tmp35
							_ = v36
							// let binding "ports"
							tmp37 := runtime.RT.NthDefault(v36, lang.IntCast(int64(0)), nil)
							var v38 any = tmp37
							_ = v38
							// let binding "bindings"
							tmp39 := runtime.RT.NthDefault(v36, lang.IntCast(int64(1)), nil)
							var v40 any = tmp39
							_ = v40
							tmp41 := lang.NewVector(v38, v26)
							tmp42 := lang.ConjAny(v19, tmp41)
							tmp43 := lang.NewVector(tmp42, v40)
							tmp27 = tmp43
						} // end let
						tmp16 = tmp27
					} // end let
					return tmp16
				})
				tmp14 := lang.NewVector()
				tmp15 := lang.NewVector()
				tmp16 := lang.NewVector(tmp14, tmp15)
				tmp17 := aotExternalFn16(tmp13, tmp16, v12)
				var v18 any = tmp17
				_ = v18
				// let binding "clauses"
				tmp19 := runtime.RT.NthDefault(v18, lang.IntCast(int64(0)), nil)
				var v20 any = tmp19
				_ = v20
				// let binding "bindings"
				tmp21 := runtime.RT.NthDefault(v18, lang.IntCast(int64(1)), nil)
				var v22 any = tmp21
				_ = v22
				// let binding "gch"
				tmp23 := aotExternalFn20("ch")
				var v24 any = tmp23
				_ = v24
				// let binding "gret"
				tmp25 := aotExternalFn20("ret")
				var v26 any = tmp25
				_ = v26
				tmp27 := checkDerefVar(var_clojure_DOT_core_list)
				tmp28 := lang.Apply1(tmp27, sym_clojure_DOT_core_SLASH_let)
				tmp29 := checkDerefVar(var_clojure_DOT_core_list)
				tmp30 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp31 := checkDerefVar(var_clojure_DOT_core_identity)
				tmp32 := aotExternalFn23(tmp31, v22)
				tmp33 := checkDerefVar(var_clojure_DOT_core_list)
				tmp34 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp35 := checkDerefVar(var_clojure_DOT_core_list)
				tmp36 := lang.Apply1(tmp35, sym_val__0__auto__)
				tmp37 := checkDerefVar(var_clojure_DOT_core_list)
				tmp38 := lang.Apply1(tmp37, v24)
				tmp39 := checkDerefVar(var_clojure_DOT_core_list)
				tmp40 := lang.Apply1(tmp39, kw_as)
				tmp41 := checkDerefVar(var_clojure_DOT_core_list)
				tmp42 := lang.Apply1(tmp41, v26)
				tmp43 := aotExternalFn24(tmp36, tmp38, tmp40, tmp42)
				tmp44 := lang.Seq(tmp43)
				tmp45 := aotExternalFn22(tmp34, tmp44)
				tmp46 := lang.Apply1(tmp33, tmp45)
				tmp47 := checkDerefVar(var_clojure_DOT_core_list)
				tmp48 := checkDerefVar(var_clojure_DOT_core_list)
				tmp49 := lang.Apply1(tmp48, v2)
				tmp50 := checkDerefVar(var_clojure_DOT_core_list)
				tmp51 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp52 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp53 := checkDerefVar(var_clojure_DOT_core_first)
				tmp54 := aotExternalFn7(tmp53, v20)
				tmp55 := aotExternalFn22(tmp52, tmp54)
				tmp56 := aotExternalFn25(tmp55)
				tmp57 := lang.Seq(tmp56)
				tmp58 := aotExternalFn22(tmp51, tmp57)
				tmp59 := lang.Apply1(tmp50, tmp58)
				tmp60 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp61 := aotExternalFn22(tmp60, v10)
				tmp62 := aotExternalFn21(tmp49, tmp59, tmp61)
				tmp63 := lang.Seq(tmp62)
				tmp64 := lang.Apply1(tmp47, tmp63)
				tmp65 := aotExternalFn21(tmp32, tmp46, tmp64)
				tmp66 := lang.Seq(tmp65)
				tmp67 := aotExternalFn22(tmp30, tmp66)
				tmp68 := lang.Apply1(tmp29, tmp67)
				tmp69 := checkDerefVar(var_clojure_DOT_core_list)
				tmp70 := checkDerefVar(var_clojure_DOT_core_list)
				tmp71 := lang.Apply1(tmp70, sym_clojure_DOT_core_SLASH_cond)
				var tmp72 lang.FnFunc1
				tmp72 = lang.FnFunc1(func(p0 any) any {
					v73 := p0
					_ = v73
					var tmp74 any
					{ // let
						// let binding "vec__729"
						var v75 any = v73
						_ = v75
						// let binding "ports"
						tmp76 := runtime.RT.NthDefault(v75, lang.IntCast(int64(0)), nil)
						var v77 any = tmp76
						_ = v77
						// let binding "expr"
						tmp78 := runtime.RT.NthDefault(v75, lang.IntCast(int64(1)), nil)
						var v79 any = tmp78
						_ = v79
						tmp80 := checkDerefVar(var_clojure_DOT_core_list)
						tmp81 := lang.Apply1(tmp80, sym_clojure_DOT_core_SLASH_or)
						var tmp82 lang.FnFunc1
						tmp82 = lang.FnFunc1(func(p0 any) any {
							v83 := p0
							_ = v83
							tmp84 := checkDerefVar(var_clojure_DOT_core_list)
							tmp85 := lang.Apply1(tmp84, sym_clojure_DOT_core_SLASH__EQ_)
							tmp86 := checkDerefVar(var_clojure_DOT_core_list)
							tmp87 := lang.Apply1(tmp86, v24)
							tmp88 := checkDerefVar(var_clojure_DOT_core_list)
							var tmp89 any
							tmp90 := aotExternalFn8(v83)
							if lang.IsTruthy(tmp90) {
								tmp91 := lang.First(v83)
								tmp89 = tmp91
							} else {
								tmp89 = v83
							}
							tmp92 := lang.Apply1(tmp88, tmp89)
							tmp93 := aotExternalFn21(tmp85, tmp87, tmp92)
							tmp94 := lang.Seq(tmp93)
							return tmp94
						})
						tmp83 := aotExternalFn7(tmp82, v77)
						tmp84 := aotExternalFn2(tmp81, tmp83)
						tmp85 := lang.Seq(tmp84)
						var tmp86 any
						var tmp87 any
						{ // let
							// let binding "and__0__auto__"
							tmp88 := aotExternalFn3(v79)
							var v89 any = tmp88
							_ = v89
							var tmp90 any
							if lang.IsTruthy(v89) {
								tmp91 := lang.First(v79)
								tmp92 := aotExternalFn8(tmp91)
								tmp90 = tmp92
							} else {
								tmp90 = v89
							}
							tmp87 = tmp90
						} // end let
						if lang.IsTruthy(tmp87) {
							tmp88 := checkDerefVar(var_clojure_DOT_core_list)
							tmp89 := lang.Apply1(tmp88, sym_clojure_DOT_core_SLASH_let)
							tmp90 := checkDerefVar(var_clojure_DOT_core_list)
							tmp91 := checkDerefVar(var_clojure_DOT_core_vector)
							tmp92 := checkDerefVar(var_clojure_DOT_core_list)
							tmp93 := lang.First(v79)
							tmp94 := lang.Apply1(tmp92, tmp93)
							tmp95 := checkDerefVar(var_clojure_DOT_core_list)
							tmp96 := lang.Apply1(tmp95, v26)
							tmp97 := aotExternalFn2(tmp94, tmp96)
							tmp98 := lang.Seq(tmp97)
							tmp99 := aotExternalFn22(tmp91, tmp98)
							tmp100 := lang.Apply1(tmp90, tmp99)
							tmp101 := aotExternalFn26(v79)
							tmp102 := aotExternalFn21(tmp89, tmp100, tmp101)
							tmp103 := lang.Seq(tmp102)
							tmp86 = tmp103
						} else {
							tmp86 = v79
						}
						tmp104 := lang.NewVector(tmp85, tmp86)
						tmp74 = tmp104
					} // end let
					return tmp74
				})
				tmp73 := aotExternalFn23(tmp72, v20)
				tmp74 := checkDerefVar(var_clojure_DOT_core_list)
				tmp75 := checkDerefVar(var_clojure_DOT_core_list)
				tmp76 := lang.Apply1(tmp75, sym_clojure_DOT_core_SLASH__EQ_)
				tmp77 := checkDerefVar(var_clojure_DOT_core_list)
				tmp78 := lang.Apply1(tmp77, v24)
				tmp79 := checkDerefVar(var_clojure_DOT_core_list)
				tmp80 := lang.Apply1(tmp79, kw_default)
				tmp81 := aotExternalFn21(tmp76, tmp78, tmp80)
				tmp82 := lang.Seq(tmp81)
				tmp83 := lang.Apply1(tmp74, tmp82)
				tmp84 := checkDerefVar(var_clojure_DOT_core_list)
				tmp85 := lang.Apply1(tmp84, sym_val__0__auto__)
				tmp86 := aotExternalFn24(tmp71, tmp73, tmp83, tmp85)
				tmp87 := lang.Seq(tmp86)
				tmp88 := lang.Apply1(tmp69, tmp87)
				tmp89 := aotExternalFn21(tmp28, tmp68, tmp88)
				tmp90 := lang.Seq(tmp89)
				tmp4 = tmp90
			} // end let
			return tmp4
		})
		aotDirectFn10 = tmp1
		var_clojure_DOT_core_DOT_async_do_DASH_alt = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_do_DASH_alt.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(212), kw_column, int(7), kw_end_DASH_line, int(212), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_alts, sym_clauses)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// go
	{
		tmp0 := sym_go
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(2, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_list)
				tmp6 := lang.Apply1(tmp5, sym_clojure_DOT_core_SLASH_let)
				tmp7 := checkDerefVar(var_clojure_DOT_core_list)
				tmp8 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp9 := checkDerefVar(var_clojure_DOT_core_list)
				tmp10 := lang.Apply1(tmp9, sym_c__0__auto__)
				tmp11 := checkDerefVar(var_clojure_DOT_core_list)
				tmp12 := checkDerefVar(var_clojure_DOT_core_list)
				tmp13 := lang.Apply1(tmp12, sym_clojure_DOT_core_DOT_async_SLASH_chan)
				tmp14 := checkDerefVar(var_clojure_DOT_core_list)
				tmp15 := lang.Apply1(tmp14, int64(1))
				tmp16 := aotExternalFn2(tmp13, tmp15)
				tmp17 := lang.Seq(tmp16)
				tmp18 := lang.Apply1(tmp11, tmp17)
				tmp19 := checkDerefVar(var_clojure_DOT_core_list)
				tmp20 := lang.Apply1(tmp19, sym_f__1__auto__)
				tmp21 := checkDerefVar(var_clojure_DOT_core_list)
				tmp22 := checkDerefVar(var_clojure_DOT_core_list)
				tmp23 := lang.Apply1(tmp22, sym_clojure_DOT_core_SLASH_fn)
				tmp24 := checkDerefVar(var_clojure_DOT_core_list)
				tmp25 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp26 := aotExternalFn30()
				tmp27 := lang.Seq(tmp26)
				tmp28 := aotExternalFn22(tmp25, tmp27)
				tmp29 := lang.Apply1(tmp24, tmp28)
				tmp30 := checkDerefVar(var_clojure_DOT_core_list)
				tmp31 := checkDerefVar(var_clojure_DOT_core_list)
				tmp32 := lang.Apply1(tmp31, sym_clojure_DOT_core_SLASH_let)
				tmp33 := checkDerefVar(var_clojure_DOT_core_list)
				tmp34 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp35 := checkDerefVar(var_clojure_DOT_core_list)
				tmp36 := lang.Apply1(tmp35, sym_res__2__auto__)
				tmp37 := checkDerefVar(var_clojure_DOT_core_list)
				tmp38 := checkDerefVar(var_clojure_DOT_core_list)
				tmp39 := lang.Apply1(tmp38, sym_do)
				tmp40 := aotExternalFn2(tmp39, v4)
				tmp41 := lang.Seq(tmp40)
				tmp42 := lang.Apply1(tmp37, tmp41)
				tmp43 := aotExternalFn2(tmp36, tmp42)
				tmp44 := lang.Seq(tmp43)
				tmp45 := aotExternalFn22(tmp34, tmp44)
				tmp46 := lang.Apply1(tmp33, tmp45)
				tmp47 := checkDerefVar(var_clojure_DOT_core_list)
				tmp48 := checkDerefVar(var_clojure_DOT_core_list)
				tmp49 := lang.Apply1(tmp48, sym_clojure_DOT_core_DOT_async_SLASH__GT__BANG_)
				tmp50 := checkDerefVar(var_clojure_DOT_core_list)
				tmp51 := lang.Apply1(tmp50, sym_c__0__auto__)
				tmp52 := checkDerefVar(var_clojure_DOT_core_list)
				tmp53 := lang.Apply1(tmp52, sym_res__2__auto__)
				tmp54 := aotExternalFn21(tmp49, tmp51, tmp53)
				tmp55 := lang.Seq(tmp54)
				tmp56 := lang.Apply1(tmp47, tmp55)
				tmp57 := aotExternalFn21(tmp32, tmp46, tmp56)
				tmp58 := lang.Seq(tmp57)
				tmp59 := lang.Apply1(tmp30, tmp58)
				tmp60 := aotExternalFn21(tmp23, tmp29, tmp59)
				tmp61 := lang.Seq(tmp60)
				tmp62 := lang.Apply1(tmp21, tmp61)
				tmp63 := aotExternalFn24(tmp10, tmp18, tmp20, tmp62)
				tmp64 := lang.Seq(tmp63)
				tmp65 := aotExternalFn22(tmp8, tmp64)
				tmp66 := lang.Apply1(tmp7, tmp65)
				tmp67 := checkDerefVar(var_clojure_DOT_core_list)
				tmp68 := checkDerefVar(var_clojure_DOT_core_list)
				tmp69 := lang.Apply1(tmp68, sym_go_SLASH_go)
				tmp70 := checkDerefVar(var_clojure_DOT_core_list)
				tmp71 := checkDerefVar(var_clojure_DOT_core_list)
				tmp72 := lang.Apply1(tmp71, sym_f__1__auto__)
				tmp73 := aotExternalFn25(tmp72)
				tmp74 := lang.Seq(tmp73)
				tmp75 := lang.Apply1(tmp70, tmp74)
				tmp76 := aotExternalFn2(tmp69, tmp75)
				tmp77 := lang.Seq(tmp76)
				tmp78 := lang.Apply1(tmp67, tmp77)
				tmp79 := checkDerefVar(var_clojure_DOT_core_list)
				tmp80 := checkDerefVar(var_clojure_DOT_core_list)
				tmp81 := checkDerefVar(var_clojure_DOT_core_list)
				tmp82 := lang.Apply1(tmp81, sym_go_SLASH__LT__DASH_chan_DASH_of)
				tmp83 := checkDerefVar(var_clojure_DOT_core_list)
				tmp84 := lang.Apply1(tmp83, sym_go_SLASH_any)
				tmp85 := aotExternalFn2(tmp82, tmp84)
				tmp86 := lang.Seq(tmp85)
				tmp87 := lang.Apply1(tmp80, tmp86)
				tmp88 := checkDerefVar(var_clojure_DOT_core_list)
				tmp89 := lang.Apply1(tmp88, sym_c__0__auto__)
				tmp90 := aotExternalFn2(tmp87, tmp89)
				tmp91 := lang.Seq(tmp90)
				tmp92 := lang.Apply1(tmp79, tmp91)
				tmp93 := aotExternalFn24(tmp6, tmp66, tmp78, tmp92)
				tmp94 := lang.Seq(tmp93)
				return tmp94
			}),
			2,
		)
		var_clojure_DOT_core_DOT_async_go = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_go.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(67), kw_column, int(11), kw_end_DASH_line, int(67), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_body)), kw_doc, "Asynchronously executes the body, returning immediately to the\n  calling thread. Additionally, any visible calls to <!, >! and alt!/alts!\n  channel operations within the body will block (if necessary) by\n  'parking' the calling thread rather than tying up an OS thread (or\n  the only JS thread when in ClojureScript). Upon completion of the\n  operation, the body will be resumed.\n\n  Unlike in Clojure or ClojureScript, go blocks may (either directly\n  or indirectly) perform operations that may block indefinitely, as go\n  blocks are run on goroutines, which relinquish the thread of control\n  when parked.\n\n  Returns a channel which will receive the result of the body when\n  completed", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_macro, true)
		})
	}
	// go-loop
	{
		tmp0 := sym_go_DASH_loop
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(3, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				v4 := args[2]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_list)
				tmp7 := lang.Apply1(tmp6, sym_clojure_DOT_core_DOT_async_SLASH_go)
				tmp8 := checkDerefVar(var_clojure_DOT_core_list)
				tmp9 := checkDerefVar(var_clojure_DOT_core_list)
				tmp10 := lang.Apply1(tmp9, sym_clojure_DOT_core_SLASH_loop)
				tmp11 := checkDerefVar(var_clojure_DOT_core_list)
				tmp12 := lang.Apply1(tmp11, v4)
				tmp13 := aotExternalFn21(tmp10, tmp12, v5)
				tmp14 := lang.Seq(tmp13)
				tmp15 := lang.Apply1(tmp8, tmp14)
				tmp16 := aotExternalFn2(tmp7, tmp15)
				tmp17 := lang.Seq(tmp16)
				return tmp17
			}),
			3,
		)
		var_clojure_DOT_core_DOT_async_go_DASH_loop = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_go_DASH_loop.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "clojure/core/async.glj", kw_line, int(287), kw_column, int(11), kw_end_DASH_line, int(287), kw_end_DASH_column, int(17), kw_arglists, lang.NewList(lang.NewVector(sym_bindings, sym__AMP_, sym_body)), kw_doc, "Like (go (loop ...))", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_macro, true)
		})
	}
}
