// Code generated by glojure codegen. DO NOT EDIT.

package async

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	time4 "time"
)

var aotDirectFn0 lang.FnFunc1
var aotRootVersion0 *lang.VarRootVersion
var aotDirectFn1 lang.FnFunc1
var aotRootVersion1 *lang.VarRootVersion
var aotDirectFn2 lang.FnFunc2
var aotRootVersion2 *lang.VarRootVersion
var aotDirectFn3 lang.FnFunc2
var aotRootVersion3 *lang.VarRootVersion
var aotDirectFn4 lang.FnFunc1
var aotRootVersion4 *lang.VarRootVersion
var aotDirectFn5 lang.FnFunc1
var aotRootVersion5 *lang.VarRootVersion
var aotDirectFn6 lang.FnFunc0
var aotRootVersion6 *lang.VarRootVersion
var aotDirectFn7 lang.FnFunc2
var aotRootVersion7 *lang.VarRootVersion
var aotDirectFn8 lang.FnFunc2
var aotRootVersion8 *lang.VarRootVersion
var aotDirectFn9 lang.FnFunc2
var aotRootVersion9 *lang.VarRootVersion
var aotDirectFn10 lang.FnFunc1
var aotRootVersion10 *lang.VarRootVersion
var aotDirectFn11 lang.FnFunc1
var aotRootVersion11 *lang.VarRootVersion
var aotDirectFn12 lang.FnFunc1
var aotRootVersion12 *lang.VarRootVersion
var aotDirectFn13 lang.FnFunc2
var aotRootVersion13 *lang.VarRootVersion
var aotDirectFn14 lang.FnFunc1
var aotRootVersion14 *lang.VarRootVersion

func init() {
	runtime.RegisterNSLoader("clojure/core/async", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "clojure.core.async"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym__LT__BANG_ := lang.NewSymbolUnchecked("<!")
	sym__LT__BANG__BANG_ := lang.NewSymbolUnchecked("<!!")
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym__GT__BANG_ := lang.NewSymbolUnchecked(">!")
	sym__GT__BANG__BANG_ := lang.NewSymbolUnchecked(">!!")
	sym_alt_BANG_ := lang.NewSymbolUnchecked("alt!")
	sym_alt_BANG__BANG_ := lang.NewSymbolUnchecked("alt!!")
	sym_alts := lang.NewSymbolUnchecked("alts")
	sym_alts_BANG_ := lang.NewSymbolUnchecked("alts!")
	sym_alts_BANG__BANG_ := lang.NewSymbolUnchecked("alts!!")
	sym_apply := lang.NewSymbolUnchecked("apply")
	sym_args := lang.NewSymbolUnchecked("args")
	sym_bindings := lang.NewSymbolUnchecked("bindings")
	sym_body := lang.NewSymbolUnchecked("body")
	sym_buf_DASH_or_DASH_n := lang.NewSymbolUnchecked("buf-or-n")
	sym_c__0__auto__ := lang.NewSymbolUnchecked("c__0__auto__")
	sym_chan := lang.NewSymbolUnchecked("chan")
	sym_check_DASH_unique_DASH_ports_BANG_ := lang.NewSymbolUnchecked("check-unique-ports!")
	sym_clauses := lang.NewSymbolUnchecked("clauses")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_core_DOT_async := lang.NewSymbolUnchecked("clojure.core.async")
	sym_clojure_DOT_core_DOT_async_SLASH__GT__BANG_ := lang.NewSymbolUnchecked("clojure.core.async/>!")
	sym_clojure_DOT_core_DOT_async_SLASH_alt_BANG_ := lang.NewSymbolUnchecked("clojure.core.async/alt!")
	sym_clojure_DOT_core_DOT_async_SLASH_alts_BANG_ := lang.NewSymbolUnchecked("clojure.core.async/alts!")
	sym_clojure_DOT_core_DOT_async_SLASH_chan := lang.NewSymbolUnchecked("clojure.core.async/chan")
	sym_clojure_DOT_core_DOT_async_SLASH_go := lang.NewSymbolUnchecked("clojure.core.async/go")
	sym_clojure_DOT_core_SLASH__EQ_ := lang.NewSymbolUnchecked("clojure.core/=")
	sym_clojure_DOT_core_SLASH_cond := lang.NewSymbolUnchecked("clojure.core/cond")
	sym_clojure_DOT_core_SLASH_fn := lang.NewSymbolUnchecked("clojure.core/fn")
	sym_clojure_DOT_core_SLASH_let := lang.NewSymbolUnchecked("clojure.core/let")
	sym_clojure_DOT_core_SLASH_loop := lang.NewSymbolUnchecked("clojure.core/loop")
	sym_clojure_DOT_core_SLASH_or := lang.NewSymbolUnchecked("clojure.core/or")
	sym_close_BANG_ := lang.NewSymbolUnchecked("close!")
	sym_close_QMARK_ := lang.NewSymbolUnchecked("close?")
	sym_concat := lang.NewSymbolUnchecked("concat")
	sym_conj := lang.NewSymbolUnchecked("conj")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_core := lang.NewSymbolUnchecked("core")
	sym_count := lang.NewSymbolUnchecked("count")
	sym_default_DASH_case := lang.NewSymbolUnchecked("default-case")
	sym_do := lang.NewSymbolUnchecked("do")
	sym_do_DASH_alt := lang.NewSymbolUnchecked("do-alt")
	sym_do_DASH_alts := lang.NewSymbolUnchecked("do-alts")
	sym_ex_DASH_handler := lang.NewSymbolUnchecked("ex-handler")
	sym_f__1__auto__ := lang.NewSymbolUnchecked("f__1__auto__")
	sym_filter := lang.NewSymbolUnchecked("filter")
	sym_first := lang.NewSymbolUnchecked("first")
	sym_from := lang.NewSymbolUnchecked("from")
	sym_gensym := lang.NewSymbolUnchecked("gensym")
	sym_go := lang.NewSymbolUnchecked("go")
	sym_go_DASH_loop := lang.NewSymbolUnchecked("go-loop")
	sym_go_SLASH__LT__DASH_chan_DASH_of := lang.NewSymbolUnchecked("go/<-chan-of")
	sym_go_SLASH_any := lang.NewSymbolUnchecked("go/any")
	sym_go_SLASH_go := lang.NewSymbolUnchecked("go/go")
	sym_identity := lang.NewSymbolUnchecked("identity")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_list := lang.NewSymbolUnchecked("list")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_mapcat := lang.NewSymbolUnchecked("mapcat")
	sym_msecs := lang.NewSymbolUnchecked("msecs")
	sym_next := lang.NewSymbolUnchecked("next")
	sym_not_EQ_ := lang.NewSymbolUnchecked("not=")
	sym_nth := lang.NewSymbolUnchecked("nth")
	sym_offer_BANG_ := lang.NewSymbolUnchecked("offer!")
	sym_opts := lang.NewSymbolUnchecked("opts")
	sym_partition := lang.NewSymbolUnchecked("partition")
	sym_pipe := lang.NewSymbolUnchecked("pipe")
	sym_poll_BANG_ := lang.NewSymbolUnchecked("poll!")
	sym_port := lang.NewSymbolUnchecked("port")
	sym_port_DASH_case := lang.NewSymbolUnchecked("port-case")
	sym_port_DASH_or_DASH_put := lang.NewSymbolUnchecked("port-or-put")
	sym_ports := lang.NewSymbolUnchecked("ports")
	sym_reduce := lang.NewSymbolUnchecked("reduce")
	sym_remove := lang.NewSymbolUnchecked("remove")
	sym_res__2__auto__ := lang.NewSymbolUnchecked("res__2__auto__")
	sym_rest := lang.NewSymbolUnchecked("rest")
	sym_seq := lang.NewSymbolUnchecked("seq")
	sym_seq_QMARK_ := lang.NewSymbolUnchecked("seq?")
	sym_set := lang.NewSymbolUnchecked("set")
	sym_timeout := lang.NewSymbolUnchecked("timeout")
	sym_to := lang.NewSymbolUnchecked("to")
	sym_to_DASH_array := lang.NewSymbolUnchecked("to-array")
	sym_try_DASH_put := lang.NewSymbolUnchecked("try-put")
	sym_try_DASH_take := lang.NewSymbolUnchecked("try-take")
	sym_val := lang.NewSymbolUnchecked("val")
	sym_val__0__auto__ := lang.NewSymbolUnchecked("val__0__auto__")
	sym_vec := lang.NewSymbolUnchecked("vec")
	sym_vector := lang.NewSymbolUnchecked("vector")
	sym_vector_QMARK_ := lang.NewSymbolUnchecked("vector?")
	sym_xform := lang.NewSymbolUnchecked("xform")
	kw_arglists := lang.NewKeyword("arglists")
	kw_as := lang.NewKeyword("as")
	kw_column := lang.NewKeyword("column")
	kw_default := lang.NewKeyword("default")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_macro := lang.NewKeyword("macro")
	kw_ns := lang.NewKeyword("ns")
	kw_priority := lang.NewKeyword("priority")
	kw_private := lang.NewKeyword("private")
	// var clojure.core.async/>!
	var_clojure_DOT_core_DOT_async__GT__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__GT__BANG_)
	// var clojure.core.async/>!!
	var_clojure_DOT_core_DOT_async__GT__BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__GT__BANG__BANG_)
	// var clojure.core.async/<!
	var_clojure_DOT_core_DOT_async__LT__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__LT__BANG_)
	// var clojure.core.async/<!!
	var_clojure_DOT_core_DOT_async__LT__BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym__LT__BANG__BANG_)
	// var clojure.core.async/alt!
	var_clojure_DOT_core_DOT_async_alt_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alt_BANG_)
	// var clojure.core.async/alt!!
	var_clojure_DOT_core_DOT_async_alt_BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alt_BANG__BANG_)
	// var clojure.core.async/alts!
	var_clojure_DOT_core_DOT_async_alts_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alts_BANG_)
	// var clojure.core.async/alts!!
	var_clojure_DOT_core_DOT_async_alts_BANG__BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_alts_BANG__BANG_)
	// var clojure.core.async/chan
	var_clojure_DOT_core_DOT_async_chan := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_chan)
	// var clojure.core.async/check-unique-ports!
	var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_check_DASH_unique_DASH_ports_BANG_)
	// var clojure.core.async/close!
	var_clojure_DOT_core_DOT_async_close_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_close_BANG_)
	// var clojure.core.async/default-case
	var_clojure_DOT_core_DOT_async_default_DASH_case := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_default_DASH_case)
	// var clojure.core.async/do-alt
	var_clojure_DOT_core_DOT_async_do_DASH_alt := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_do_DASH_alt)
	// var clojure.core.async/do-alts
	var_clojure_DOT_core_DOT_async_do_DASH_alts := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_do_DASH_alts)
	// var clojure.core.async/go
	var_clojure_DOT_core_DOT_async_go := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_go)
	// var clojure.core.async/go-loop
	var_clojure_DOT_core_DOT_async_go_DASH_loop := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_go_DASH_loop)
	// var clojure.core.async/offer!
	var_clojure_DOT_core_DOT_async_offer_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_offer_BANG_)
	// var clojure.core.async/pipe
	var_clojure_DOT_core_DOT_async_pipe := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_pipe)
	// var clojure.core.async/poll!
	var_clojure_DOT_core_DOT_async_poll_BANG_ := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_poll_BANG_)
	// var clojure.core.async/port-case
	var_clojure_DOT_core_DOT_async_port_DASH_case := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_port_DASH_case)
	// var clojure.core.async/timeout
	var_clojure_DOT_core_DOT_async_timeout := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_timeout)
	// var clojure.core.async/try-put
	var_clojure_DOT_core_DOT_async_try_DASH_put := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_try_DASH_put)
	// var clojure.core.async/try-take
	var_clojure_DOT_core_DOT_async_try_DASH_take := lang.InternVarName(sym_clojure_DOT_core_DOT_async, sym_try_DASH_take)
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/apply
	var_clojure_DOT_core_apply := lang.InternVarName(sym_clojure_DOT_core, sym_apply)
	// var clojure.core/concat
	var_clojure_DOT_core_concat := lang.InternVarName(sym_clojure_DOT_core, sym_concat)
	// var clojure.core/conj
	var_clojure_DOT_core_conj := lang.InternVarName(sym_clojure_DOT_core, sym_conj)
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/count
	var_clojure_DOT_core_count := lang.InternVarName(sym_clojure_DOT_core, sym_count)
	// var clojure.core/filter
	var_clojure_DOT_core_filter := lang.InternVarName(sym_clojure_DOT_core, sym_filter)
	// var clojure.core/first
	var_clojure_DOT_core_first := lang.InternVarName(sym_clojure_DOT_core, sym_first)
	// var clojure.core/gensym
	var_clojure_DOT_core_gensym := lang.InternVarName(sym_clojure_DOT_core, sym_gensym)
	// var clojure.core/identity
	var_clojure_DOT_core_identity := lang.InternVarName(sym_clojure_DOT_core, sym_identity)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/list
	var_clojure_DOT_core_list := lang.InternVarName(sym_clojure_DOT_core, sym_list)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/mapcat
	var_clojure_DOT_core_mapcat := lang.InternVarName(sym_clojure_DOT_core, sym_mapcat)
	// var clojure.core/next
	var_clojure_DOT_core_next := lang.InternVarName(sym_clojure_DOT_core, sym_next)
	// var clojure.core/not=
	var_clojure_DOT_core_not_EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym_not_EQ_)
	// var clojure.core/nth
	var_clojure_DOT_core_nth := lang.InternVarName(sym_clojure_DOT_core, sym_nth)
	// var clojure.core/partition
	var_clojure_DOT_core_partition := lang.InternVarName(sym_clojure_DOT_core, sym_partition)
	// var clojure.core/reduce
	var_clojure_DOT_core_reduce := lang.InternVarName(sym_clojure_DOT_core, sym_reduce)
	// var clojure.core/remove
	var_clojure_DOT_core_remove := lang.InternVarName(sym_clojure_DOT_core, sym_remove)
	// var clojure.core/rest
	var_clojure_DOT_core_rest := lang.InternVarName(sym_clojure_DOT_core, sym_rest)
	// var clojure.core/seq
	var_clojure_DOT_core_seq := lang.InternVarName(sym_clojure_DOT_core, sym_seq)
	// var clojure.core/seq?
	var_clojure_DOT_core_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_seq_QMARK_)
	// var clojure.core/set
	var_clojure_DOT_core_set := lang.InternVarName(sym_clojure_DOT_core, sym_set)
	// var clojure.core/to-array
	var_clojure_DOT_core_to_DASH_array := lang.InternVarName(sym_clojure_DOT_core, sym_to_DASH_array)
	// var clojure.core/vec
	var_clojure_DOT_core_vec := lang.InternVarName(sym_clojure_DOT_core, sym_vec)
	// var clojure.core/vector
	var_clojure_DOT_core_vector := lang.InternVarName(sym_clojure_DOT_core, sym_vector)
	// var clojure.core/vector?
	var_clojure_DOT_core_vector_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_vector_QMARK_)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_core, lang.FindOrCreateNamespace(sym_clojure_DOT_core))
	// >!
	{
		tmp0 := sym__GT__BANG_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := lang.Apply2(lang.Builtins["send"], v2, v3)
			_ = tmp4
			return true
		})
		aotDirectFn2 = tmp1
		var_clojure_DOT_core_DOT_async__GT__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion2 = var_clojure_DOT_core_DOT_async__GT__BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async__GT__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(44), kw_column, int(7), kw_end_DASH_line, int(44), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_port, sym_val)), kw_doc, "puts a val into port. nil values are not allowed. Will park if no buffer space is available.\n  Returns true, or throws if port is already closed.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// >!!
	{
		tmp0 := sym__GT__BANG__BANG_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := lang.Apply2(lang.Builtins["send"], v2, v3)
			_ = tmp4
			return true
		})
		aotDirectFn3 = tmp1
		var_clojure_DOT_core_DOT_async__GT__BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion3 = var_clojure_DOT_core_DOT_async__GT__BANG__BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async__GT__BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(51), kw_column, int(6), kw_end_DASH_line, int(51), kw_end_DASH_column, int(8), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// chan
	{
		tmp0 := sym_chan
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			lang.FnFunc0(func() any {
				tmp2 := checkDerefVar(var_clojure_DOT_core_DOT_async_chan)
				tmp3 := lang.Apply1(tmp2, nil)
				return tmp3
			}),
			lang.FnFunc1(func(p0 any) any {
				v2 := p0
				_ = v2
				tmp3 := checkDerefVar(var_clojure_DOT_core_DOT_async_chan)
				tmp4 := lang.Apply2(tmp3, v2, nil)
				return tmp4
			}),
			lang.FnFunc2(func(p0, p1 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				tmp4 := checkDerefVar(var_clojure_DOT_core_DOT_async_chan)
				tmp5 := lang.Apply3(tmp4, v2, v3, nil)
				return tmp5
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				v4 := p2
				_ = v4
				var tmp5 any
				if lang.IsTruthy(v3) {
				} else {
				}
				_ = tmp5
				var tmp6 any
				if lang.IsTruthy(v3) {
					tmp7 := lang.Apply1(fmt.Errorf, "xform and ex-handler not yet supported")
					panic(tmp7)
				} else {
				}
				_ = tmp6
				tmp8 := lang.Apply1(lang.Builtins["chan-of"], lang.Builtins["any"])
				var tmp9 any
				{ // let
					// let binding "or__0__auto__"
					var v10 any = v2
					_ = v10
					var tmp11 any
					if lang.IsTruthy(v10) {
						tmp11 = v10
					} else {
						tmp11 = int64(0)
					}
					tmp9 = tmp11
				} // end let
				tmp10 := lang.Apply2(lang.Builtins["make"], tmp8, tmp9)
				return tmp10
			}),
			nil,
			nil,
			0,
		)
		var_clojure_DOT_core_DOT_async_chan = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_chan.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(18), kw_column, int(7), kw_end_DASH_line, int(18), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_buf_DASH_or_DASH_n), lang.NewVector(sym_buf_DASH_or_DASH_n, sym_xform), lang.NewVector(sym_buf_DASH_or_DASH_n, sym_xform, sym_ex_DASH_handler)), kw_doc, "Creates a channel with an optional buffer, an optional transducer\n  (like (map f), (filter p) etc or a composition thereof), and an\n  optional exception-handler.  If buf-or-n is a number, will create\n  and use a fixed buffer of that size. If a transducer is supplied a\n  buffer must be specified. ex-handler must be a fn of one argument -\n  if an exception occurs during transformation it will be called with\n  the Throwable as an argument, and any non-nil return value will be\n  placed in the channel.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// close!
	{
		tmp0 := sym_close_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.Apply1(lang.Builtins["close"], v2)
			return tmp3
		})
		aotDirectFn5 = tmp1
		var_clojure_DOT_core_DOT_async_close_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion5 = var_clojure_DOT_core_DOT_async_close_BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async_close_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(53), kw_column, int(7), kw_end_DASH_line, int(53), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_chan)), kw_doc, "Closes a channel. The channel will no longer accept any puts (they\n  will be ignored). Data in the channel remains available for taking,\n  until exhausted, after which takes will return nil. If there are any\n  pending takes, they will be dispatched with nil. Closing a closed\n  channel will throw an exception.\n\n  Logically closing happens after all puts have been\n  delivered. Therefore, any blocked or parked puts will remain\n  blocked/parked until a taker releases them.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// default-case
	{
		tmp0 := sym_default_DASH_case
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			var tmp2 any
			{ // let
				// let binding "def"
				tmp3 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp4 := reflect.New(tmp3).Interface()
				var v5 any = tmp4
				_ = v5
				// set! host field
				var tmp6 any
				{
					targetV := reflect.ValueOf(v5)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(reflect.SelectDefault)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp6 = reflect.SelectDefault
				}
				_ = tmp6
				tmp2 = v5
			} // end let
			return tmp2
		})
		aotDirectFn6 = tmp1
		var_clojure_DOT_core_DOT_async_default_DASH_case = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion6 = var_clojure_DOT_core_DOT_async_default_DASH_case.RootVersion()
		var_clojure_DOT_core_DOT_async_default_DASH_case.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(100), kw_column, int(8), kw_end_DASH_line, int(100), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector()), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// <!
	{
		tmp0 := sym__LT__BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "vec__690"
				tmp4 := lang.Apply1(lang.Builtins["recv"], v2)
				var v5 any = tmp4
				_ = v5
				// let binding "val"
				tmp6 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp7 := lang.Apply3(tmp6, v5, int64(0), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "_"
				tmp9 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp10 := lang.Apply3(tmp9, v5, int64(1), nil)
				var v11 any = tmp10
				_ = v11
				tmp3 = v8
			} // end let
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_clojure_DOT_core_DOT_async__LT__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion0 = var_clojure_DOT_core_DOT_async__LT__BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async__LT__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(35), kw_column, int(7), kw_end_DASH_line, int(35), kw_end_DASH_column, int(8), kw_arglists, lang.NewList(lang.NewVector(sym_port)), kw_doc, "takes a val from port. Will return nil if closed. Will park if\n  nothing is available.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// pipe
	{
		tmp0 := sym_pipe
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			lang.FnFunc2(func(p0, p1 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				tmp4 := checkDerefVar(var_clojure_DOT_core_DOT_async_pipe)
				tmp5 := lang.Apply3(tmp4, v2, v3, true)
				return tmp5
			}),
			lang.FnFunc3(func(p0, p1, p2 any) any {
				v2 := p0
				_ = v2
				v3 := p1
				_ = v3
				v4 := p2
				_ = v4
				var tmp5 any
				{ // let
					// let binding "c__0__auto__"
					tmp6 := checkDerefVar(var_clojure_DOT_core_DOT_async_chan)
					tmp7 := lang.Apply1(tmp6, int64(1))
					var v8 any = tmp7
					_ = v8
					// let binding "f__1__auto__"
					var tmp9 lang.FnFunc0
					tmp9 = lang.FnFunc0(func() any {
						var tmp10 any
						{ // let
							// let binding "res__2__auto__"
							var tmp11 any
							{ // let
								for {
									var tmp12 any
									{ // let
										// let binding "v"
										tmp13 := var_clojure_DOT_core_DOT_async__LT__BANG_.RootVersion() == aotRootVersion0 && !var_clojure_DOT_core_DOT_async__LT__BANG_.IsMacro()
										var tmp14 any
										if !tmp13 {
											tmp14 = checkDerefVar(var_clojure_DOT_core_DOT_async__LT__BANG_)
										}
										var tmp15 any
										if tmp13 {
											tmp15 = aotDirectFn0(v2)
										} else {
											tmp15 = lang.Apply1(tmp14, v2)
										}
										var v16 any = tmp15
										_ = v16
										var tmp17 any
										tmp18 := lang.Identical(v16, nil)
										if lang.IsTruthy(tmp18) {
											var tmp19 any
											if lang.IsTruthy(v4) {
												tmp20 := var_clojure_DOT_core_DOT_async_close_BANG_.RootVersion() == aotRootVersion5 && !var_clojure_DOT_core_DOT_async_close_BANG_.IsMacro()
												var tmp21 any
												if !tmp20 {
													tmp21 = checkDerefVar(var_clojure_DOT_core_DOT_async_close_BANG_)
												}
												var tmp22 any
												if tmp20 {
													tmp22 = aotDirectFn5(v3)
												} else {
													tmp22 = lang.Apply1(tmp21, v3)
												}
												tmp19 = tmp22
											} else {
											}
											tmp17 = tmp19
										} else {
											var tmp23 any
											tmp24 := var_clojure_DOT_core_DOT_async__GT__BANG_.RootVersion() == aotRootVersion2 && !var_clojure_DOT_core_DOT_async__GT__BANG_.IsMacro()
											var tmp25 any
											if !tmp24 {
												tmp25 = checkDerefVar(var_clojure_DOT_core_DOT_async__GT__BANG_)
											}
											var tmp26 any
											if tmp24 {
												tmp26 = aotDirectFn2(v3, v16)
											} else {
												tmp26 = lang.Apply2(tmp25, v3, v16)
											}
											if lang.IsTruthy(tmp26) {
												continue
											} else {
											}
											tmp17 = tmp23
										}
										tmp12 = tmp17
									} // end let
									tmp11 = tmp12
									break
								}
							} // end let
							var v12 any = tmp11
							_ = v12
							tmp13 := var_clojure_DOT_core_DOT_async__GT__BANG_.RootVersion() == aotRootVersion2 && !var_clojure_DOT_core_DOT_async__GT__BANG_.IsMacro()
							var tmp14 any
							if !tmp13 {
								tmp14 = checkDerefVar(var_clojure_DOT_core_DOT_async__GT__BANG_)
							}
							var tmp15 any
							if tmp13 {
								tmp15 = aotDirectFn2(v8, v12)
							} else {
								tmp15 = lang.Apply2(tmp14, v8, v12)
							}
							tmp10 = tmp15
						} // end let
						return tmp10
					})
					var v10 any = tmp9
					_ = v10
					go lang.Apply(v10, []any{})
					tmp11 := lang.Apply1(lang.Builtins["<-chan-of"], lang.Builtins["any"])
					tmp12 := lang.Apply1(tmp11, v8)
					tmp5 = tmp12
				} // end let
				_ = tmp5
				return v3
			}),
			nil,
			nil,
			0,
		)
		var_clojure_DOT_core_DOT_async_pipe = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_pipe.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(292), kw_column, int(7), kw_end_DASH_line, int(292), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_from, sym_to), lang.NewVector(sym_from, sym_to, sym_close_QMARK_)), kw_doc, "Takes elements from the from channel and supplies them to the to\n  channel. By default, the to channel will be closed when the from\n  channel closes, but can be determined by the close?  parameter. Will\n  stop consuming the from channel if the to channel closes", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// timeout
	{
		tmp0 := sym_timeout
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "ret"
				tmp4 := checkDerefVar(var_clojure_DOT_core_DOT_async_chan)
				tmp5 := lang.Apply0(tmp4)
				var v6 any = tmp5
				_ = v6
				// let binding "after"
				tmp7 := lang.Apply1(lang.Builtins["int64"], time4.Millisecond)
				tmp8 := lang.Numbers.Multiply(v2, tmp7)
				tmp9 := lang.Apply1(time4.After, tmp8)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				{ // let
					// let binding "c__0__auto__"
					tmp12 := checkDerefVar(var_clojure_DOT_core_DOT_async_chan)
					tmp13 := lang.Apply1(tmp12, int64(1))
					var v14 any = tmp13
					_ = v14
					// let binding "f__1__auto__"
					var tmp15 lang.FnFunc0
					tmp15 = lang.FnFunc0(func() any {
						var tmp16 any
						{ // let
							// let binding "res__2__auto__"
							tmp17 := var_clojure_DOT_core_DOT_async__LT__BANG_.RootVersion() == aotRootVersion0 && !var_clojure_DOT_core_DOT_async__LT__BANG_.IsMacro()
							var tmp18 any
							if !tmp17 {
								tmp18 = checkDerefVar(var_clojure_DOT_core_DOT_async__LT__BANG_)
							}
							var tmp19 any
							if tmp17 {
								tmp19 = aotDirectFn0(v10)
							} else {
								tmp19 = lang.Apply1(tmp18, v10)
							}
							_ = tmp19
							tmp20 := var_clojure_DOT_core_DOT_async_close_BANG_.RootVersion() == aotRootVersion5 && !var_clojure_DOT_core_DOT_async_close_BANG_.IsMacro()
							var tmp21 any
							if !tmp20 {
								tmp21 = checkDerefVar(var_clojure_DOT_core_DOT_async_close_BANG_)
							}
							var tmp22 any
							if tmp20 {
								tmp22 = aotDirectFn5(v6)
							} else {
								tmp22 = lang.Apply1(tmp21, v6)
							}
							var v23 any = tmp22
							_ = v23
							tmp24 := var_clojure_DOT_core_DOT_async__GT__BANG_.RootVersion() == aotRootVersion2 && !var_clojure_DOT_core_DOT_async__GT__BANG_.IsMacro()
							var tmp25 any
							if !tmp24 {
								tmp25 = checkDerefVar(var_clojure_DOT_core_DOT_async__GT__BANG_)
							}
							var tmp26 any
							if tmp24 {
								tmp26 = aotDirectFn2(v14, v23)
							} else {
								tmp26 = lang.Apply2(tmp25, v14, v23)
							}
							tmp16 = tmp26
						} // end let
						return tmp16
					})
					var v16 any = tmp15
					_ = v16
					go lang.Apply(v16, []any{})
					tmp17 := lang.Apply1(lang.Builtins["<-chan-of"], lang.Builtins["any"])
					tmp18 := lang.Apply1(tmp17, v14)
					tmp11 = tmp18
				} // end let
				_ = tmp11
				tmp3 = v6
			} // end let
			return tmp3
		})
		aotDirectFn12 = tmp1
		var_clojure_DOT_core_DOT_async_timeout = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion12 = var_clojure_DOT_core_DOT_async_timeout.RootVersion()
		var_clojure_DOT_core_DOT_async_timeout.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(91), kw_column, int(7), kw_end_DASH_line, int(91), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_msecs)), kw_doc, "Returns a channel that will close after msecs", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// <!!
	{
		tmp0 := sym__LT__BANG__BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "vec__690"
				tmp4 := lang.Apply1(lang.Builtins["recv"], v2)
				var v5 any = tmp4
				_ = v5
				// let binding "val"
				tmp6 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp7 := lang.Apply3(tmp6, v5, int64(0), nil)
				var v8 any = tmp7
				_ = v8
				// let binding "_"
				tmp9 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp10 := lang.Apply3(tmp9, v5, int64(1), nil)
				var v11 any = tmp10
				_ = v11
				tmp3 = v8
			} // end let
			return tmp3
		})
		aotDirectFn1 = tmp1
		var_clojure_DOT_core_DOT_async__LT__BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion1 = var_clojure_DOT_core_DOT_async__LT__BANG__BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async__LT__BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(42), kw_column, int(6), kw_end_DASH_line, int(42), kw_end_DASH_column, int(8), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// alt!
	{
		tmp0 := sym_alt_BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(2, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := var_clojure_DOT_core_DOT_async_do_DASH_alt.RootVersion() == aotRootVersion7 && !var_clojure_DOT_core_DOT_async_do_DASH_alt.IsMacro()
				var tmp6 any
				if !tmp5 {
					tmp6 = checkDerefVar(var_clojure_DOT_core_DOT_async_do_DASH_alt)
				}
				var tmp7 any
				if tmp5 {
					tmp7 = aotDirectFn7(sym_clojure_DOT_core_DOT_async_SLASH_alts_BANG_, v4)
				} else {
					tmp7 = lang.Apply2(tmp6, sym_clojure_DOT_core_DOT_async_SLASH_alts_BANG_, v4)
				}
				return tmp7
			}),
			2,
		)
		var_clojure_DOT_core_DOT_async_alt_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alt_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_macro, true, kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_clauses)), kw_doc, "Makes a single choice between one of several channel operations,\n  as if by alts!, returning the value of the result expr corresponding\n  to the operation completed.\n\n  Each clause takes the form of:\n\n  channel-op[s] result-expr\n\n  where channel-ops is one of:\n\n  take-port - a single port to take\n  [take-port | [put-port put-val] ...] - a vector of ports as per alts!\n  :default | :priority - an option for alts!\n\n  and result-expr is either a list beginning with a vector, whereupon that\n  vector will be treated as a binding for the [val port] return of the\n  operation, else any other expression.\n\n  (alt!\n    [c t] ([val ch] (foo ch val))\n    x ([v] v)\n    [[out val]] :wrote\n    :default 42)\n\n  Each option may appear at most once. The choice and parking\n  characteristics are those of alts!.", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(14), kw_column, int(11), kw_line, int(250), kw_end_DASH_line, int(250))
		})
	}
	// alt!!
	{
		tmp0 := sym_alt_BANG__BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(2, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp6 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp7 := checkDerefVar(var_clojure_DOT_core_list)
				tmp8 := lang.Apply1(tmp7, sym_clojure_DOT_core_DOT_async_SLASH_alt_BANG_)
				tmp9 := lang.Apply2(tmp6, tmp8, v4)
				tmp10 := lang.Apply1(tmp5, tmp9)
				return tmp10
			}),
			2,
		)
		var_clojure_DOT_core_DOT_async_alt_BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alt_BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(281), kw_column, int(11), kw_end_DASH_line, int(281), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_macro, true)
		})
	}
	// alts!
	{
		tmp0 := sym_alts_BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				var v3 any = rest
				_ = v3
				var tmp4 any
				{ // let
					// let binding "map__706"
					var v5 any = v3
					_ = v5
					// let binding "map__706"
					var tmp6 any
					tmp7 := checkDerefVar(var_clojure_DOT_core_seq_QMARK_)
					tmp8 := lang.Apply1(tmp7, v5)
					if lang.IsTruthy(tmp8) {
						var tmp9 any
						tmp10 := checkDerefVar(var_clojure_DOT_core_next)
						tmp11 := lang.Apply1(tmp10, v5)
						if lang.IsTruthy(tmp11) {
							tmp12 := checkDerefVar(var_clojure_DOT_core_to_DASH_array)
							tmp13 := lang.Apply1(tmp12, v5)
							tmp14 := lang.Apply1(lang.NewPersistentArrayMapAsIfByAssoc, tmp13)
							tmp9 = tmp14
						} else {
							var tmp15 any
							tmp16 := checkDerefVar(var_clojure_DOT_core_seq)
							tmp17 := lang.Apply1(tmp16, v5)
							if lang.IsTruthy(tmp17) {
								tmp18 := checkDerefVar(var_clojure_DOT_core_first)
								tmp19 := lang.Apply1(tmp18, v5)
								tmp15 = tmp19
							} else {
								tmp20 := lang.Apply0(lang.NewMap)
								tmp15 = tmp20
							}
							tmp9 = tmp15
						}
						tmp6 = tmp9
					} else {
						tmp6 = v5
					}
					var v21 any = tmp6
					_ = v21
					// let binding "opts"
					var v22 any = v21
					_ = v22
					tmp23 := var_clojure_DOT_core_DOT_async_do_DASH_alts.RootVersion() == aotRootVersion8 && !var_clojure_DOT_core_DOT_async_do_DASH_alts.IsMacro()
					var tmp24 any
					if !tmp23 {
						tmp24 = checkDerefVar(var_clojure_DOT_core_DOT_async_do_DASH_alts)
					}
					var tmp25 any
					if tmp23 {
						tmp25 = aotDirectFn8(v2, v22)
					} else {
						tmp25 = lang.Apply2(tmp24, v2, v22)
					}
					tmp4 = tmp25
				} // end let
				return tmp4
			}),
			1,
		)
		var_clojure_DOT_core_DOT_async_alts_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alts_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(185), kw_column, int(7), kw_end_DASH_line, int(185), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_ports, sym__AMP_, lang.NewMap(kw_as, sym_opts))), kw_doc, "Completes at most one of several channel operations. Must ports is a\n  vector of channel endpoints, which can be either a channel to take\n  from or a vector of [channel-to-put-to val-to-put], in any\n  combination.  Takes will be made as if by <!, and puts will be made\n  as if by >!. Unless the :priority option is true, if more than one\n  port operation is ready a non-deterministic choice will be made. If\n  no operation is ready and a :default value is\n  supplied, [default-val :default] will be returned, otherwise alts!\n  will park until the first operation to become ready\n  completes. Returns [val port] of the completed operation, where val\n  is the value taken for takes, and true for puts.\n\n  opts are passed as :key val ... Supported options:\n\n  :default val - the value to use if none of the operations are immediately ready\n  :priority true - (default nil) when true, the operations will be tried in order.\n\n  Note: there is no guarantee that the port exps or val exprs will be\n  used, nor in what order should they be, so they should not be\n  depended upon for side effects.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// alts!!
	{
		tmp0 := sym_alts_BANG__BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				var v3 any = rest
				_ = v3
				var tmp4 any
				{ // let
					// let binding "map__706"
					var v5 any = v3
					_ = v5
					// let binding "map__706"
					var tmp6 any
					tmp7 := checkDerefVar(var_clojure_DOT_core_seq_QMARK_)
					tmp8 := lang.Apply1(tmp7, v5)
					if lang.IsTruthy(tmp8) {
						var tmp9 any
						tmp10 := checkDerefVar(var_clojure_DOT_core_next)
						tmp11 := lang.Apply1(tmp10, v5)
						if lang.IsTruthy(tmp11) {
							tmp12 := checkDerefVar(var_clojure_DOT_core_to_DASH_array)
							tmp13 := lang.Apply1(tmp12, v5)
							tmp14 := lang.Apply1(lang.NewPersistentArrayMapAsIfByAssoc, tmp13)
							tmp9 = tmp14
						} else {
							var tmp15 any
							tmp16 := checkDerefVar(var_clojure_DOT_core_seq)
							tmp17 := lang.Apply1(tmp16, v5)
							if lang.IsTruthy(tmp17) {
								tmp18 := checkDerefVar(var_clojure_DOT_core_first)
								tmp19 := lang.Apply1(tmp18, v5)
								tmp15 = tmp19
							} else {
								tmp20 := lang.Apply0(lang.NewMap)
								tmp15 = tmp20
							}
							tmp9 = tmp15
						}
						tmp6 = tmp9
					} else {
						tmp6 = v5
					}
					var v21 any = tmp6
					_ = v21
					// let binding "opts"
					var v22 any = v21
					_ = v22
					tmp23 := var_clojure_DOT_core_DOT_async_do_DASH_alts.RootVersion() == aotRootVersion8 && !var_clojure_DOT_core_DOT_async_do_DASH_alts.IsMacro()
					var tmp24 any
					if !tmp23 {
						tmp24 = checkDerefVar(var_clojure_DOT_core_DOT_async_do_DASH_alts)
					}
					var tmp25 any
					if tmp23 {
						tmp25 = aotDirectFn8(v2, v22)
					} else {
						tmp25 = lang.Apply2(tmp24, v2, v22)
					}
					tmp4 = tmp25
				} // end let
				return tmp4
			}),
			1,
		)
		var_clojure_DOT_core_DOT_async_alts_BANG__BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_alts_BANG__BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(210), kw_column, int(6), kw_end_DASH_line, int(210), kw_end_DASH_column, int(11), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// check-unique-ports!
	{
		tmp0 := sym_check_DASH_unique_DASH_ports_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "chans"
				tmp4 := checkDerefVar(var_clojure_DOT_core_map)
				var tmp5 lang.FnFunc1
				tmp5 = lang.FnFunc1(func(p0 any) any {
					v6 := p0
					_ = v6
					var tmp7 any
					tmp8 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
					tmp9 := lang.Apply1(tmp8, v6)
					if lang.IsTruthy(tmp9) {
						tmp10 := lang.Apply1(v6, int64(0))
						tmp7 = tmp10
					} else {
						tmp7 = v6
					}
					return tmp7
				})
				tmp6 := lang.Apply2(tmp4, tmp5, v2)
				var v7 any = tmp6
				_ = v7
				// let binding "s"
				tmp8 := checkDerefVar(var_clojure_DOT_core_set)
				tmp9 := lang.Apply1(tmp8, v7)
				var v10 any = tmp9
				_ = v10
				var tmp11 any
				tmp12 := checkDerefVar(var_clojure_DOT_core_not_EQ_)
				tmp13 := checkDerefVar(var_clojure_DOT_core_count)
				tmp14 := lang.Apply1(tmp13, v10)
				tmp15 := checkDerefVar(var_clojure_DOT_core_count)
				tmp16 := lang.Apply1(tmp15, v2)
				tmp17 := lang.Apply2(tmp12, tmp14, tmp16)
				if lang.IsTruthy(tmp17) {
					tmp18 := lang.Apply1(fmt.Errorf, "duplicate ports found in alt(s)! operation")
					panic(tmp18)
				} else {
				}
				tmp3 = tmp11
			} // end let
			return tmp3
		})
		aotDirectFn4 = tmp1
		var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion4 = var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(158), kw_column, int(8), kw_end_DASH_line, int(158), kw_end_DASH_column, int(26), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_ports)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// do-alt
	{
		tmp0 := sym_do_DASH_alt
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "clauses"
				tmp5 := checkDerefVar(var_clojure_DOT_core_partition)
				tmp6 := lang.Apply2(tmp5, int64(2), v3)
				var v7 any = tmp6
				_ = v7
				// let binding "opt?"
				var tmp8 lang.FnFunc1
				tmp8 = lang.FnFunc1(func(p0 any) any {
					v9 := p0
					_ = v9
					tmp10 := checkDerefVar(var_clojure_DOT_core_keyword_QMARK_)
					tmp11 := checkDerefVar(var_clojure_DOT_core_first)
					tmp12 := lang.Apply1(tmp11, v9)
					tmp13 := lang.Apply1(tmp10, tmp12)
					return tmp13
				})
				var v9 any = tmp8
				_ = v9
				// let binding "opts"
				tmp10 := checkDerefVar(var_clojure_DOT_core_filter)
				tmp11 := lang.Apply2(tmp10, v9, v7)
				var v12 any = tmp11
				_ = v12
				// let binding "clauses"
				tmp13 := checkDerefVar(var_clojure_DOT_core_remove)
				tmp14 := lang.Apply2(tmp13, v9, v7)
				var v15 any = tmp14
				_ = v15
				// let binding "vec__707"
				tmp16 := checkDerefVar(var_clojure_DOT_core_reduce)
				var tmp17 lang.FnFunc2
				tmp17 = lang.FnFunc2(func(p0, p1 any) any {
					v18 := p0
					_ = v18
					v19 := p1
					_ = v19
					var tmp20 any
					{ // let
						// let binding "vec__712"
						var v21 any = v18
						_ = v21
						// let binding "clauses"
						tmp22 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp23 := lang.Apply3(tmp22, v21, int64(0), nil)
						var v24 any = tmp23
						_ = v24
						// let binding "bindings"
						tmp25 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp26 := lang.Apply3(tmp25, v21, int64(1), nil)
						var v27 any = tmp26
						_ = v27
						// let binding "vec__715"
						var v28 any = v19
						_ = v28
						// let binding "ports"
						tmp29 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp30 := lang.Apply3(tmp29, v28, int64(0), nil)
						var v31 any = tmp30
						_ = v31
						// let binding "expr"
						tmp32 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp33 := lang.Apply3(tmp32, v28, int64(1), nil)
						var v34 any = tmp33
						_ = v34
						var tmp35 any
						{ // let
							// let binding "ports"
							var tmp36 any
							tmp37 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
							tmp38 := lang.Apply1(tmp37, v31)
							if lang.IsTruthy(tmp38) {
								tmp36 = v31
							} else {
								tmp39 := lang.NewVector(v31)
								tmp40 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(221), kw_column, int(50), kw_end_DASH_line, int(221), kw_end_DASH_column, int(56))
								tmp41, err := lang.WithMeta(tmp39, tmp40.(lang.IPersistentMap))
								if err != nil {
									panic(err)
								}
								tmp36 = tmp41
							}
							var v42 any = tmp36
							_ = v42
							// let binding "vec__718"
							tmp43 := checkDerefVar(var_clojure_DOT_core_reduce)
							var tmp44 lang.FnFunc2
							tmp44 = lang.FnFunc2(func(p0, p1 any) any {
								v45 := p0
								_ = v45
								v46 := p1
								_ = v46
								var tmp47 any
								{ // let
									// let binding "vec__722"
									var v48 any = v45
									_ = v48
									// let binding "ports"
									tmp49 := checkDerefVar(var_clojure_DOT_core_nth)
									tmp50 := lang.Apply3(tmp49, v48, int64(0), nil)
									var v51 any = tmp50
									_ = v51
									// let binding "bindings"
									tmp52 := checkDerefVar(var_clojure_DOT_core_nth)
									tmp53 := lang.Apply3(tmp52, v48, int64(1), nil)
									var v54 any = tmp53
									_ = v54
									var tmp55 any
									tmp56 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
									tmp57 := lang.Apply1(tmp56, v46)
									if lang.IsTruthy(tmp57) {
										var tmp58 any
										{ // let
											// let binding "vec__725"
											var v59 any = v46
											_ = v59
											// let binding "port"
											tmp60 := checkDerefVar(var_clojure_DOT_core_nth)
											tmp61 := lang.Apply3(tmp60, v59, int64(0), nil)
											var v62 any = tmp61
											_ = v62
											// let binding "val"
											tmp63 := checkDerefVar(var_clojure_DOT_core_nth)
											tmp64 := lang.Apply3(tmp63, v59, int64(1), nil)
											var v65 any = tmp64
											_ = v65
											// let binding "gp"
											tmp66 := checkDerefVar(var_clojure_DOT_core_gensym)
											tmp67 := lang.Apply0(tmp66)
											var v68 any = tmp67
											_ = v68
											// let binding "gv"
											tmp69 := checkDerefVar(var_clojure_DOT_core_gensym)
											tmp70 := lang.Apply0(tmp69)
											var v71 any = tmp70
											_ = v71
											tmp72 := checkDerefVar(var_clojure_DOT_core_conj)
											tmp73 := lang.NewVector(v68, v71)
											tmp74 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(229), kw_column, int(38), kw_end_DASH_line, int(229), kw_end_DASH_column, int(44))
											tmp75, err := lang.WithMeta(tmp73, tmp74.(lang.IPersistentMap))
											if err != nil {
												panic(err)
											}
											tmp76 := lang.Apply2(tmp72, v51, tmp75)
											tmp77 := checkDerefVar(var_clojure_DOT_core_conj)
											tmp78 := lang.NewVector(v68, v62)
											tmp79 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(229), kw_column, int(62), kw_end_DASH_line, int(229), kw_end_DASH_column, int(70))
											tmp80, err := lang.WithMeta(tmp78, tmp79.(lang.IPersistentMap))
											if err != nil {
												panic(err)
											}
											tmp81 := lang.NewVector(v71, v65)
											tmp82 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(229), kw_column, int(72), kw_end_DASH_line, int(229), kw_end_DASH_column, int(79))
											tmp83, err := lang.WithMeta(tmp81, tmp82.(lang.IPersistentMap))
											if err != nil {
												panic(err)
											}
											tmp84 := lang.Apply3(tmp77, v54, tmp80, tmp83)
											tmp85 := lang.NewVector(tmp76, tmp84)
											tmp86 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(229), kw_column, int(25), kw_end_DASH_line, int(229), kw_end_DASH_column, int(81))
											tmp87, err := lang.WithMeta(tmp85, tmp86.(lang.IPersistentMap))
											if err != nil {
												panic(err)
											}
											tmp58 = tmp87
										} // end let
										tmp55 = tmp58
									} else {
										var tmp59 any
										{ // let
											// let binding "gp"
											tmp60 := checkDerefVar(var_clojure_DOT_core_gensym)
											tmp61 := lang.Apply0(tmp60)
											var v62 any = tmp61
											_ = v62
											tmp63 := checkDerefVar(var_clojure_DOT_core_conj)
											tmp64 := lang.Apply2(tmp63, v51, v62)
											tmp65 := checkDerefVar(var_clojure_DOT_core_conj)
											tmp66 := lang.NewVector(v62, v46)
											tmp67 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(231), kw_column, int(57), kw_end_DASH_line, int(231), kw_end_DASH_column, int(65))
											tmp68, err := lang.WithMeta(tmp66, tmp67.(lang.IPersistentMap))
											if err != nil {
												panic(err)
											}
											tmp69 := lang.Apply2(tmp65, v54, tmp68)
											tmp70 := lang.NewVector(tmp64, tmp69)
											tmp71 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(231), kw_column, int(25), kw_end_DASH_line, int(231), kw_end_DASH_column, int(67))
											tmp72, err := lang.WithMeta(tmp70, tmp71.(lang.IPersistentMap))
											if err != nil {
												panic(err)
											}
											tmp59 = tmp72
										} // end let
										tmp55 = tmp59
									}
									tmp47 = tmp55
								} // end let
								return tmp47
							})
							tmp45 := lang.NewVector()
							tmp46 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(232), kw_column, int(20), kw_end_DASH_line, int(232), kw_end_DASH_column, int(21))
							tmp47, err := lang.WithMeta(tmp45, tmp46.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp48 := lang.NewVector(tmp47, v27)
							tmp49 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(232), kw_column, int(19), kw_end_DASH_line, int(232), kw_end_DASH_column, int(31))
							tmp50, err := lang.WithMeta(tmp48, tmp49.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp51 := lang.Apply3(tmp43, tmp44, tmp50, v42)
							var v52 any = tmp51
							_ = v52
							// let binding "ports"
							tmp53 := checkDerefVar(var_clojure_DOT_core_nth)
							tmp54 := lang.Apply3(tmp53, v52, int64(0), nil)
							var v55 any = tmp54
							_ = v55
							// let binding "bindings"
							tmp56 := checkDerefVar(var_clojure_DOT_core_nth)
							tmp57 := lang.Apply3(tmp56, v52, int64(1), nil)
							var v58 any = tmp57
							_ = v58
							tmp59 := checkDerefVar(var_clojure_DOT_core_conj)
							tmp60 := lang.NewVector(v55, v34)
							tmp61 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(233), kw_column, int(29), kw_end_DASH_line, int(233), kw_end_DASH_column, int(40))
							tmp62, err := lang.WithMeta(tmp60, tmp61.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp63 := lang.Apply2(tmp59, v24, tmp62)
							tmp64 := lang.NewVector(tmp63, v58)
							tmp65 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(233), kw_column, int(14), kw_end_DASH_line, int(233), kw_end_DASH_column, int(51))
							tmp66, err := lang.WithMeta(tmp64, tmp65.(lang.IPersistentMap))
							if err != nil {
								panic(err)
							}
							tmp35 = tmp66
						} // end let
						tmp20 = tmp35
					} // end let
					return tmp20
				})
				tmp18 := lang.NewVector()
				tmp19 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(234), kw_column, int(11), kw_end_DASH_line, int(234), kw_end_DASH_column, int(12))
				tmp20, err := lang.WithMeta(tmp18, tmp19.(lang.IPersistentMap))
				if err != nil {
					panic(err)
				}
				tmp21 := lang.NewVector()
				tmp22 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(234), kw_column, int(14), kw_end_DASH_line, int(234), kw_end_DASH_column, int(15))
				tmp23, err := lang.WithMeta(tmp21, tmp22.(lang.IPersistentMap))
				if err != nil {
					panic(err)
				}
				tmp24 := lang.NewVector(tmp20, tmp23)
				tmp25 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(234), kw_column, int(10), kw_end_DASH_line, int(234), kw_end_DASH_column, int(16))
				tmp26, err := lang.WithMeta(tmp24, tmp25.(lang.IPersistentMap))
				if err != nil {
					panic(err)
				}
				tmp27 := lang.Apply3(tmp16, tmp17, tmp26, v15)
				var v28 any = tmp27
				_ = v28
				// let binding "clauses"
				tmp29 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp30 := lang.Apply3(tmp29, v28, int64(0), nil)
				var v31 any = tmp30
				_ = v31
				// let binding "bindings"
				tmp32 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp33 := lang.Apply3(tmp32, v28, int64(1), nil)
				var v34 any = tmp33
				_ = v34
				// let binding "gch"
				tmp35 := checkDerefVar(var_clojure_DOT_core_gensym)
				tmp36 := lang.Apply1(tmp35, "ch")
				var v37 any = tmp36
				_ = v37
				// let binding "gret"
				tmp38 := checkDerefVar(var_clojure_DOT_core_gensym)
				tmp39 := lang.Apply1(tmp38, "ret")
				var v40 any = tmp39
				_ = v40
				tmp41 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp42 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp43 := checkDerefVar(var_clojure_DOT_core_list)
				tmp44 := lang.Apply1(tmp43, sym_clojure_DOT_core_SLASH_let)
				tmp45 := checkDerefVar(var_clojure_DOT_core_list)
				tmp46 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp47 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp48 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp49 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp50 := checkDerefVar(var_clojure_DOT_core_mapcat)
				tmp51 := checkDerefVar(var_clojure_DOT_core_identity)
				tmp52 := lang.Apply2(tmp50, tmp51, v34)
				tmp53 := checkDerefVar(var_clojure_DOT_core_list)
				tmp54 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp55 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp56 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp57 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp58 := checkDerefVar(var_clojure_DOT_core_list)
				tmp59 := lang.Apply1(tmp58, sym_val__0__auto__)
				tmp60 := checkDerefVar(var_clojure_DOT_core_list)
				tmp61 := lang.Apply1(tmp60, v37)
				tmp62 := checkDerefVar(var_clojure_DOT_core_list)
				tmp63 := lang.Apply1(tmp62, kw_as)
				tmp64 := checkDerefVar(var_clojure_DOT_core_list)
				tmp65 := lang.Apply1(tmp64, v40)
				tmp66 := lang.Apply4(tmp57, tmp59, tmp61, tmp63, tmp65)
				tmp67 := lang.Apply1(tmp56, tmp66)
				tmp68 := lang.Apply2(tmp54, tmp55, tmp67)
				tmp69 := lang.Apply1(tmp53, tmp68)
				tmp70 := checkDerefVar(var_clojure_DOT_core_list)
				tmp71 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp72 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp73 := checkDerefVar(var_clojure_DOT_core_list)
				tmp74 := lang.Apply1(tmp73, v2)
				tmp75 := checkDerefVar(var_clojure_DOT_core_list)
				tmp76 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp77 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp78 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp79 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp80 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp81 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp82 := checkDerefVar(var_clojure_DOT_core_map)
				tmp83 := checkDerefVar(var_clojure_DOT_core_first)
				tmp84 := lang.Apply2(tmp82, tmp83, v31)
				tmp85 := lang.Apply2(tmp80, tmp81, tmp84)
				tmp86 := lang.Apply1(tmp79, tmp85)
				tmp87 := lang.Apply1(tmp78, tmp86)
				tmp88 := lang.Apply2(tmp76, tmp77, tmp87)
				tmp89 := lang.Apply1(tmp75, tmp88)
				tmp90 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp91 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp92 := lang.Apply2(tmp90, tmp91, v12)
				tmp93 := lang.Apply3(tmp72, tmp74, tmp89, tmp92)
				tmp94 := lang.Apply1(tmp71, tmp93)
				tmp95 := lang.Apply1(tmp70, tmp94)
				tmp96 := lang.Apply3(tmp49, tmp52, tmp69, tmp95)
				tmp97 := lang.Apply1(tmp48, tmp96)
				tmp98 := lang.Apply2(tmp46, tmp47, tmp97)
				tmp99 := lang.Apply1(tmp45, tmp98)
				tmp100 := checkDerefVar(var_clojure_DOT_core_list)
				tmp101 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp102 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp103 := checkDerefVar(var_clojure_DOT_core_list)
				tmp104 := lang.Apply1(tmp103, sym_clojure_DOT_core_SLASH_cond)
				tmp105 := checkDerefVar(var_clojure_DOT_core_mapcat)
				var tmp106 lang.FnFunc1
				tmp106 = lang.FnFunc1(func(p0 any) any {
					v107 := p0
					_ = v107
					var tmp108 any
					{ // let
						// let binding "vec__729"
						var v109 any = v107
						_ = v109
						// let binding "ports"
						tmp110 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp111 := lang.Apply3(tmp110, v109, int64(0), nil)
						var v112 any = tmp111
						_ = v112
						// let binding "expr"
						tmp113 := checkDerefVar(var_clojure_DOT_core_nth)
						tmp114 := lang.Apply3(tmp113, v109, int64(1), nil)
						var v115 any = tmp114
						_ = v115
						tmp116 := checkDerefVar(var_clojure_DOT_core_seq)
						tmp117 := checkDerefVar(var_clojure_DOT_core_concat)
						tmp118 := checkDerefVar(var_clojure_DOT_core_list)
						tmp119 := lang.Apply1(tmp118, sym_clojure_DOT_core_SLASH_or)
						tmp120 := checkDerefVar(var_clojure_DOT_core_map)
						var tmp121 lang.FnFunc1
						tmp121 = lang.FnFunc1(func(p0 any) any {
							v122 := p0
							_ = v122
							tmp123 := checkDerefVar(var_clojure_DOT_core_seq)
							tmp124 := checkDerefVar(var_clojure_DOT_core_concat)
							tmp125 := checkDerefVar(var_clojure_DOT_core_list)
							tmp126 := lang.Apply1(tmp125, sym_clojure_DOT_core_SLASH__EQ_)
							tmp127 := checkDerefVar(var_clojure_DOT_core_list)
							tmp128 := lang.Apply1(tmp127, v37)
							tmp129 := checkDerefVar(var_clojure_DOT_core_list)
							var tmp130 any
							tmp131 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
							tmp132 := lang.Apply1(tmp131, v122)
							if lang.IsTruthy(tmp132) {
								tmp133 := checkDerefVar(var_clojure_DOT_core_first)
								tmp134 := lang.Apply1(tmp133, v122)
								tmp130 = tmp134
							} else {
								tmp130 = v122
							}
							tmp135 := lang.Apply1(tmp129, tmp130)
							tmp136 := lang.Apply3(tmp124, tmp126, tmp128, tmp135)
							tmp137 := lang.Apply1(tmp123, tmp136)
							return tmp137
						})
						tmp122 := lang.Apply2(tmp120, tmp121, v112)
						tmp123 := lang.Apply2(tmp117, tmp119, tmp122)
						tmp124 := lang.Apply1(tmp116, tmp123)
						var tmp125 any
						var tmp126 any
						{ // let
							// let binding "and__0__auto__"
							tmp127 := checkDerefVar(var_clojure_DOT_core_seq_QMARK_)
							tmp128 := lang.Apply1(tmp127, v115)
							var v129 any = tmp128
							_ = v129
							var tmp130 any
							if lang.IsTruthy(v129) {
								tmp131 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
								tmp132 := checkDerefVar(var_clojure_DOT_core_first)
								tmp133 := lang.Apply1(tmp132, v115)
								tmp134 := lang.Apply1(tmp131, tmp133)
								tmp130 = tmp134
							} else {
								tmp130 = v129
							}
							tmp126 = tmp130
						} // end let
						if lang.IsTruthy(tmp126) {
							tmp127 := checkDerefVar(var_clojure_DOT_core_seq)
							tmp128 := checkDerefVar(var_clojure_DOT_core_concat)
							tmp129 := checkDerefVar(var_clojure_DOT_core_list)
							tmp130 := lang.Apply1(tmp129, sym_clojure_DOT_core_SLASH_let)
							tmp131 := checkDerefVar(var_clojure_DOT_core_list)
							tmp132 := checkDerefVar(var_clojure_DOT_core_apply)
							tmp133 := checkDerefVar(var_clojure_DOT_core_vector)
							tmp134 := checkDerefVar(var_clojure_DOT_core_seq)
							tmp135 := checkDerefVar(var_clojure_DOT_core_concat)
							tmp136 := checkDerefVar(var_clojure_DOT_core_list)
							tmp137 := checkDerefVar(var_clojure_DOT_core_first)
							tmp138 := lang.Apply1(tmp137, v115)
							tmp139 := lang.Apply1(tmp136, tmp138)
							tmp140 := checkDerefVar(var_clojure_DOT_core_list)
							tmp141 := lang.Apply1(tmp140, v40)
							tmp142 := lang.Apply2(tmp135, tmp139, tmp141)
							tmp143 := lang.Apply1(tmp134, tmp142)
							tmp144 := lang.Apply2(tmp132, tmp133, tmp143)
							tmp145 := lang.Apply1(tmp131, tmp144)
							tmp146 := checkDerefVar(var_clojure_DOT_core_rest)
							tmp147 := lang.Apply1(tmp146, v115)
							tmp148 := lang.Apply3(tmp128, tmp130, tmp145, tmp147)
							tmp149 := lang.Apply1(tmp127, tmp148)
							tmp125 = tmp149
						} else {
							tmp125 = v115
						}
						tmp150 := lang.NewVector(tmp124, tmp125)
						tmp151 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(241), kw_column, int(21), kw_end_DASH_line, int(246), kw_end_DASH_column, int(29))
						tmp152, err := lang.WithMeta(tmp150, tmp151.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp108 = tmp152
					} // end let
					return tmp108
				})
				tmp107 := lang.Apply2(tmp105, tmp106, v31)
				tmp108 := checkDerefVar(var_clojure_DOT_core_list)
				tmp109 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp110 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp111 := checkDerefVar(var_clojure_DOT_core_list)
				tmp112 := lang.Apply1(tmp111, sym_clojure_DOT_core_SLASH__EQ_)
				tmp113 := checkDerefVar(var_clojure_DOT_core_list)
				tmp114 := lang.Apply1(tmp113, v37)
				tmp115 := checkDerefVar(var_clojure_DOT_core_list)
				tmp116 := lang.Apply1(tmp115, kw_default)
				tmp117 := lang.Apply3(tmp110, tmp112, tmp114, tmp116)
				tmp118 := lang.Apply1(tmp109, tmp117)
				tmp119 := lang.Apply1(tmp108, tmp118)
				tmp120 := checkDerefVar(var_clojure_DOT_core_list)
				tmp121 := lang.Apply1(tmp120, sym_val__0__auto__)
				tmp122 := lang.Apply4(tmp102, tmp104, tmp107, tmp119, tmp121)
				tmp123 := lang.Apply1(tmp101, tmp122)
				tmp124 := lang.Apply1(tmp100, tmp123)
				tmp125 := lang.Apply3(tmp42, tmp44, tmp99, tmp124)
				tmp126 := lang.Apply1(tmp41, tmp125)
				tmp4 = tmp126
			} // end let
			return tmp4
		})
		aotDirectFn7 = tmp1
		var_clojure_DOT_core_DOT_async_do_DASH_alt = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion7 = var_clojure_DOT_core_DOT_async_do_DASH_alt.RootVersion()
		var_clojure_DOT_core_DOT_async_do_DASH_alt.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(212), kw_column, int(7), kw_end_DASH_line, int(212), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_alts, sym_clauses)), kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// do-alts
	{
		tmp0 := sym_do_DASH_alts
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			tmp4 := var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_.RootVersion() == aotRootVersion4 && !var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_.IsMacro()
			var tmp5 any
			if !tmp4 {
				tmp5 = checkDerefVar(var_clojure_DOT_core_DOT_async_check_DASH_unique_DASH_ports_BANG_)
			}
			var tmp6 any
			if tmp4 {
				tmp6 = aotDirectFn4(v2)
			} else {
				tmp6 = lang.Apply1(tmp5, v2)
			}
			_ = tmp6
			var tmp7 any
			{ // let
				// let binding "ports"
				tmp8 := checkDerefVar(var_clojure_DOT_core_vec)
				tmp9 := lang.Apply1(tmp8, v2)
				var v10 any = tmp9
				_ = v10
				// let binding "n"
				tmp11 := checkDerefVar(var_clojure_DOT_core_count)
				tmp12 := lang.Apply1(tmp11, v10)
				var v13 any = tmp12
				_ = v13
				// let binding "priority"
				tmp14 := lang.Apply1(kw_priority, v3)
				var v15 any = tmp14
				_ = v15
				// let binding "selects"
				tmp16 := checkDerefVar(var_clojure_DOT_core_map)
				tmp17 := checkDerefVar(var_clojure_DOT_core_DOT_async_port_DASH_case)
				tmp18 := lang.Apply2(tmp16, tmp17, v10)
				var v19 any = tmp18
				_ = v19
				// let binding "selects"
				var tmp20 any
				tmp21 := checkDerefVar(var_clojure_DOT_core_contains_QMARK_)
				tmp22 := lang.Apply2(tmp21, v3, kw_default)
				if lang.IsTruthy(tmp22) {
					tmp23 := checkDerefVar(var_clojure_DOT_core_conj)
					tmp24 := checkDerefVar(var_clojure_DOT_core_vec)
					tmp25 := lang.Apply1(tmp24, v19)
					tmp26 := var_clojure_DOT_core_DOT_async_default_DASH_case.RootVersion() == aotRootVersion6 && !var_clojure_DOT_core_DOT_async_default_DASH_case.IsMacro()
					var tmp27 any
					if !tmp26 {
						tmp27 = checkDerefVar(var_clojure_DOT_core_DOT_async_default_DASH_case)
					}
					var tmp28 any
					if tmp26 {
						tmp28 = aotDirectFn6()
					} else {
						tmp28 = lang.Apply0(tmp27)
					}
					tmp29 := lang.Apply2(tmp23, tmp25, tmp28)
					tmp20 = tmp29
				} else {
					tmp20 = v19
				}
				var v30 any = tmp20
				_ = v30
				// let binding "def"
				tmp31 := var_clojure_DOT_core_DOT_async_default_DASH_case.RootVersion() == aotRootVersion6 && !var_clojure_DOT_core_DOT_async_default_DASH_case.IsMacro()
				var tmp32 any
				if !tmp31 {
					tmp32 = checkDerefVar(var_clojure_DOT_core_DOT_async_default_DASH_case)
				}
				var tmp33 any
				if tmp31 {
					tmp33 = aotDirectFn6()
				} else {
					tmp33 = lang.Apply0(tmp32)
				}
				var v34 any = tmp33
				_ = v34
				// let binding "vec__702"
				tmp35 := checkDerefVar(var_clojure_DOT_core_map)
				tmp36 := lang.Apply2(tmp35, lang.Builtins["deref"], v30)
				tmp37 := lang.Apply1(reflect.Select, tmp36)
				var v38 any = tmp37
				_ = v38
				// let binding "chosen-idx"
				tmp39 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp40 := lang.Apply3(tmp39, v38, int64(0), nil)
				var v41 any = tmp40
				_ = v41
				// let binding "val"
				tmp42 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp43 := lang.Apply3(tmp42, v38, int64(1), nil)
				var v44 any = tmp43
				_ = v44
				// let binding "ok"
				tmp45 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp46 := lang.Apply3(tmp45, v38, int64(2), nil)
				var v47 any = tmp46
				_ = v47
				// let binding "chosen"
				tmp48, _ := lang.FieldOrMethod(runtime.RT, "Get")
				if reflect.TypeOf(tmp48).Kind() != reflect.Func {
					panic(lang.NewIllegalArgumentError(fmt.Sprintf("Get is not a function")))
				}
				tmp49 := lang.Apply2(tmp48, v10, v41)
				var v50 any = tmp49
				_ = v50
				var tmp51 any
				tmp52 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
				tmp53 := lang.Apply1(tmp52, v50)
				if lang.IsTruthy(tmp53) {
					tmp54 := lang.Apply1(v50, int64(0))
					tmp55 := lang.NewVector(true, tmp54)
					tmp56 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(181), kw_column, int(24), kw_end_DASH_line, int(181), kw_end_DASH_column, int(40))
					tmp57, err := lang.WithMeta(tmp55, tmp56.(lang.IPersistentMap))
					if err != nil {
						panic(err)
					}
					tmp51 = tmp57
				} else {
					var tmp58 any
					tmp59 := checkDerefVar(var_clojure_DOT_core__EQ_)
					tmp60 := lang.Apply2(tmp59, v13, v41)
					if lang.IsTruthy(tmp60) {
						tmp61 := lang.Apply1(kw_default, v3)
						tmp62 := lang.NewVector(tmp61, kw_default)
						tmp63 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(182), kw_column, int(24), kw_end_DASH_line, int(182), kw_end_DASH_column, int(49))
						tmp64, err := lang.WithMeta(tmp62, tmp63.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp58 = tmp64
					} else {
						var tmp65 any
						if lang.IsTruthy(v47) {
							tmp66, ok := lang.FieldOrMethod(v44, "Interface")
							if !ok {
								panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v44, "Interface")))
							}
							var tmp67 any
							switch reflect.TypeOf(tmp66).Kind() {
							case reflect.Func:
								tmp67 = lang.Apply(tmp66, nil)
							default:
								tmp67 = tmp66
							}
							tmp65 = tmp67
						} else {
						}
						tmp68 := lang.NewVector(tmp65, v50)
						tmp69 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(183), kw_column, int(13), kw_end_DASH_line, int(183), kw_end_DASH_column, int(47))
						tmp70, err := lang.WithMeta(tmp68, tmp69.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp58 = tmp70
					}
					tmp51 = tmp58
				}
				tmp7 = tmp51
			} // end let
			return tmp7
		})
		aotDirectFn8 = tmp1
		var_clojure_DOT_core_DOT_async_do_DASH_alts = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion8 = var_clojure_DOT_core_DOT_async_do_DASH_alts.RootVersion()
		var_clojure_DOT_core_DOT_async_do_DASH_alts.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_ports, sym_opts)), kw_doc, "returns derefable [val port] if immediate, nil if enqueued", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(14), kw_column, int(8), kw_line, int(165), kw_end_DASH_line, int(165), kw_private, true)
		})
	}
	// go
	{
		tmp0 := sym_go
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(2, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				var v4 any = rest
				_ = v4
				tmp5 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp6 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp7 := checkDerefVar(var_clojure_DOT_core_list)
				tmp8 := lang.Apply1(tmp7, sym_clojure_DOT_core_SLASH_let)
				tmp9 := checkDerefVar(var_clojure_DOT_core_list)
				tmp10 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp11 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp12 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp13 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp14 := checkDerefVar(var_clojure_DOT_core_list)
				tmp15 := lang.Apply1(tmp14, sym_c__0__auto__)
				tmp16 := checkDerefVar(var_clojure_DOT_core_list)
				tmp17 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp18 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp19 := checkDerefVar(var_clojure_DOT_core_list)
				tmp20 := lang.Apply1(tmp19, sym_clojure_DOT_core_DOT_async_SLASH_chan)
				tmp21 := checkDerefVar(var_clojure_DOT_core_list)
				tmp22 := lang.Apply1(tmp21, int64(1))
				tmp23 := lang.Apply2(tmp18, tmp20, tmp22)
				tmp24 := lang.Apply1(tmp17, tmp23)
				tmp25 := lang.Apply1(tmp16, tmp24)
				tmp26 := checkDerefVar(var_clojure_DOT_core_list)
				tmp27 := lang.Apply1(tmp26, sym_f__1__auto__)
				tmp28 := checkDerefVar(var_clojure_DOT_core_list)
				tmp29 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp30 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp31 := checkDerefVar(var_clojure_DOT_core_list)
				tmp32 := lang.Apply1(tmp31, sym_clojure_DOT_core_SLASH_fn)
				tmp33 := checkDerefVar(var_clojure_DOT_core_list)
				tmp34 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp35 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp36 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp37 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp38 := lang.Apply0(tmp37)
				tmp39 := lang.Apply1(tmp36, tmp38)
				tmp40 := lang.Apply2(tmp34, tmp35, tmp39)
				tmp41 := lang.Apply1(tmp33, tmp40)
				tmp42 := checkDerefVar(var_clojure_DOT_core_list)
				tmp43 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp44 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp45 := checkDerefVar(var_clojure_DOT_core_list)
				tmp46 := lang.Apply1(tmp45, sym_clojure_DOT_core_SLASH_let)
				tmp47 := checkDerefVar(var_clojure_DOT_core_list)
				tmp48 := checkDerefVar(var_clojure_DOT_core_apply)
				tmp49 := checkDerefVar(var_clojure_DOT_core_vector)
				tmp50 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp51 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp52 := checkDerefVar(var_clojure_DOT_core_list)
				tmp53 := lang.Apply1(tmp52, sym_res__2__auto__)
				tmp54 := checkDerefVar(var_clojure_DOT_core_list)
				tmp55 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp56 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp57 := checkDerefVar(var_clojure_DOT_core_list)
				tmp58 := lang.Apply1(tmp57, sym_do)
				tmp59 := lang.Apply2(tmp56, tmp58, v4)
				tmp60 := lang.Apply1(tmp55, tmp59)
				tmp61 := lang.Apply1(tmp54, tmp60)
				tmp62 := lang.Apply2(tmp51, tmp53, tmp61)
				tmp63 := lang.Apply1(tmp50, tmp62)
				tmp64 := lang.Apply2(tmp48, tmp49, tmp63)
				tmp65 := lang.Apply1(tmp47, tmp64)
				tmp66 := checkDerefVar(var_clojure_DOT_core_list)
				tmp67 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp68 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp69 := checkDerefVar(var_clojure_DOT_core_list)
				tmp70 := lang.Apply1(tmp69, sym_clojure_DOT_core_DOT_async_SLASH__GT__BANG_)
				tmp71 := checkDerefVar(var_clojure_DOT_core_list)
				tmp72 := lang.Apply1(tmp71, sym_c__0__auto__)
				tmp73 := checkDerefVar(var_clojure_DOT_core_list)
				tmp74 := lang.Apply1(tmp73, sym_res__2__auto__)
				tmp75 := lang.Apply3(tmp68, tmp70, tmp72, tmp74)
				tmp76 := lang.Apply1(tmp67, tmp75)
				tmp77 := lang.Apply1(tmp66, tmp76)
				tmp78 := lang.Apply3(tmp44, tmp46, tmp65, tmp77)
				tmp79 := lang.Apply1(tmp43, tmp78)
				tmp80 := lang.Apply1(tmp42, tmp79)
				tmp81 := lang.Apply3(tmp30, tmp32, tmp41, tmp80)
				tmp82 := lang.Apply1(tmp29, tmp81)
				tmp83 := lang.Apply1(tmp28, tmp82)
				tmp84 := lang.Apply4(tmp13, tmp15, tmp25, tmp27, tmp83)
				tmp85 := lang.Apply1(tmp12, tmp84)
				tmp86 := lang.Apply2(tmp10, tmp11, tmp85)
				tmp87 := lang.Apply1(tmp9, tmp86)
				tmp88 := checkDerefVar(var_clojure_DOT_core_list)
				tmp89 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp90 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp91 := checkDerefVar(var_clojure_DOT_core_list)
				tmp92 := lang.Apply1(tmp91, sym_go_SLASH_go)
				tmp93 := checkDerefVar(var_clojure_DOT_core_list)
				tmp94 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp95 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp96 := checkDerefVar(var_clojure_DOT_core_list)
				tmp97 := lang.Apply1(tmp96, sym_f__1__auto__)
				tmp98 := lang.Apply1(tmp95, tmp97)
				tmp99 := lang.Apply1(tmp94, tmp98)
				tmp100 := lang.Apply1(tmp93, tmp99)
				tmp101 := lang.Apply2(tmp90, tmp92, tmp100)
				tmp102 := lang.Apply1(tmp89, tmp101)
				tmp103 := lang.Apply1(tmp88, tmp102)
				tmp104 := checkDerefVar(var_clojure_DOT_core_list)
				tmp105 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp106 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp107 := checkDerefVar(var_clojure_DOT_core_list)
				tmp108 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp109 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp110 := checkDerefVar(var_clojure_DOT_core_list)
				tmp111 := lang.Apply1(tmp110, sym_go_SLASH__LT__DASH_chan_DASH_of)
				tmp112 := checkDerefVar(var_clojure_DOT_core_list)
				tmp113 := lang.Apply1(tmp112, sym_go_SLASH_any)
				tmp114 := lang.Apply2(tmp109, tmp111, tmp113)
				tmp115 := lang.Apply1(tmp108, tmp114)
				tmp116 := lang.Apply1(tmp107, tmp115)
				tmp117 := checkDerefVar(var_clojure_DOT_core_list)
				tmp118 := lang.Apply1(tmp117, sym_c__0__auto__)
				tmp119 := lang.Apply2(tmp106, tmp116, tmp118)
				tmp120 := lang.Apply1(tmp105, tmp119)
				tmp121 := lang.Apply1(tmp104, tmp120)
				tmp122 := lang.Apply4(tmp6, tmp8, tmp87, tmp103, tmp121)
				tmp123 := lang.Apply1(tmp5, tmp122)
				return tmp123
			}),
			2,
		)
		var_clojure_DOT_core_DOT_async_go = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_go.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_macro, true, kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_body)), kw_doc, "Asynchronously executes the body, returning immediately to the\n  calling thread. Additionally, any visible calls to <!, >! and alt!/alts!\n  channel operations within the body will block (if necessary) by\n  'parking' the calling thread rather than tying up an OS thread (or\n  the only JS thread when in ClojureScript). Upon completion of the\n  operation, the body will be resumed.\n\n  Unlike in Clojure or ClojureScript, go blocks may (either directly\n  or indirectly) perform operations that may block indefinitely, as go\n  blocks are run on goroutines, which relinquish the thread of control\n  when parked.\n\n  Returns a channel which will receive the result of the body when\n  completed", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(12), kw_column, int(11), kw_line, int(67), kw_end_DASH_line, int(67))
		})
	}
	// go-loop
	{
		tmp0 := sym_go_DASH_loop
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(3, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				v3 := args[1]
				_ = v3
				v4 := args[2]
				_ = v4
				var v5 any = rest
				_ = v5
				tmp6 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp7 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp8 := checkDerefVar(var_clojure_DOT_core_list)
				tmp9 := lang.Apply1(tmp8, sym_clojure_DOT_core_DOT_async_SLASH_go)
				tmp10 := checkDerefVar(var_clojure_DOT_core_list)
				tmp11 := checkDerefVar(var_clojure_DOT_core_seq)
				tmp12 := checkDerefVar(var_clojure_DOT_core_concat)
				tmp13 := checkDerefVar(var_clojure_DOT_core_list)
				tmp14 := lang.Apply1(tmp13, sym_clojure_DOT_core_SLASH_loop)
				tmp15 := checkDerefVar(var_clojure_DOT_core_list)
				tmp16 := lang.Apply1(tmp15, v4)
				tmp17 := lang.Apply3(tmp12, tmp14, tmp16, v5)
				tmp18 := lang.Apply1(tmp11, tmp17)
				tmp19 := lang.Apply1(tmp10, tmp18)
				tmp20 := lang.Apply2(tmp7, tmp9, tmp19)
				tmp21 := lang.Apply1(tmp6, tmp20)
				return tmp21
			}),
			3,
		)
		var_clojure_DOT_core_DOT_async_go_DASH_loop = ns.InternWithValue(tmp0, tmp1, true)
		var_clojure_DOT_core_DOT_async_go_DASH_loop.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_macro, true, kw_arglists, lang.NewList(lang.NewVector(sym_bindings, sym__AMP_, sym_body)), kw_doc, "Like (go (loop ...))", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(17), kw_column, int(11), kw_line, int(287), kw_end_DASH_line, int(287))
		})
	}
	// offer!
	{
		tmp0 := sym_offer_BANG_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "ret"
				tmp5 := var_clojure_DOT_core_DOT_async_try_DASH_put.RootVersion() == aotRootVersion13 && !var_clojure_DOT_core_DOT_async_try_DASH_put.IsMacro()
				var tmp6 any
				if !tmp5 {
					tmp6 = checkDerefVar(var_clojure_DOT_core_DOT_async_try_DASH_put)
				}
				var tmp7 any
				if tmp5 {
					tmp7 = aotDirectFn13(v2, v3)
				} else {
					tmp7 = lang.Apply2(tmp6, v2, v3)
				}
				var v8 any = tmp7
				_ = v8
				var tmp9 any
				if lang.IsTruthy(v8) {
					tmp9 = v8
				} else {
				}
				tmp4 = tmp9
			} // end let
			return tmp4
		})
		aotDirectFn9 = tmp1
		var_clojure_DOT_core_DOT_async_offer_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion9 = var_clojure_DOT_core_DOT_async_offer_BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async_offer_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(143), kw_column, int(7), kw_end_DASH_line, int(143), kw_end_DASH_column, int(12), kw_arglists, lang.NewList(lang.NewVector(sym_port, sym_val)), kw_doc, "Puts a val into port if it's possible to do so immediately.\n   nil values are not allowed. Never blocks. Returns true if offer succeeds.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// poll!
	{
		tmp0 := sym_poll_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "res"
				tmp4 := var_clojure_DOT_core_DOT_async_try_DASH_take.RootVersion() == aotRootVersion14 && !var_clojure_DOT_core_DOT_async_try_DASH_take.IsMacro()
				var tmp5 any
				if !tmp4 {
					tmp5 = checkDerefVar(var_clojure_DOT_core_DOT_async_try_DASH_take)
				}
				var tmp6 any
				if tmp4 {
					tmp6 = aotDirectFn14(v2)
				} else {
					tmp6 = lang.Apply1(tmp5, v2)
				}
				var v7 any = tmp6
				_ = v7
				// let binding "vec__699"
				var v8 any = v7
				_ = v8
				// let binding "val"
				tmp9 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp10 := lang.Apply3(tmp9, v8, int64(0), nil)
				var v11 any = tmp10
				_ = v11
				// let binding "ok"
				tmp12 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp13 := lang.Apply3(tmp12, v8, int64(1), nil)
				var v14 any = tmp13
				_ = v14
				var tmp15 any
				if lang.IsTruthy(v14) {
					tmp15 = v11
				} else {
				}
				tmp3 = tmp15
			} // end let
			return tmp3
		})
		aotDirectFn10 = tmp1
		var_clojure_DOT_core_DOT_async_poll_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion10 = var_clojure_DOT_core_DOT_async_poll_BANG_.RootVersion()
		var_clojure_DOT_core_DOT_async_poll_BANG_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(150), kw_column, int(7), kw_end_DASH_line, int(150), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_port)), kw_doc, "Takes a val from port if it's possible to do so immediately.\n   Never blocks. Returns value if successful, nil otherwise.", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async))
		})
	}
	// port-case
	{
		tmp0 := sym_port_DASH_case
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "wport"
				var tmp4 any
				tmp5 := checkDerefVar(var_clojure_DOT_core_vector_QMARK_)
				tmp6 := lang.Apply1(tmp5, v2)
				if lang.IsTruthy(tmp6) {
					tmp7 := lang.Apply1(v2, int64(0))
					tmp4 = tmp7
				} else {
				}
				var v8 any = tmp4
				_ = v8
				// let binding "port"
				var tmp9 any
				{ // let
					// let binding "or__0__auto__"
					var v10 any = v8
					_ = v10
					var tmp11 any
					if lang.IsTruthy(v10) {
						tmp11 = v10
					} else {
						tmp11 = v2
					}
					tmp9 = tmp11
				} // end let
				var v10 any = tmp9
				_ = v10
				// let binding "val"
				var tmp11 any
				if lang.IsTruthy(v8) {
					tmp12 := lang.Apply1(v2, int64(1))
					tmp13 := reflect.ValueOf(tmp12)
					tmp11 = tmp13
				} else {
				}
				var v14 any = tmp11
				_ = v14
				// let binding "select-case"
				tmp15 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp16 := reflect.New(tmp15).Interface()
				var v17 any = tmp16
				_ = v17
				tmp18 := reflect.ValueOf(v10)
				// set! host field
				var tmp19 any
				{
					targetV := reflect.ValueOf(v17)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Chan")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Chan"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Chan"))
					}
					valV := reflect.ValueOf(tmp18)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Chan to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp19 = tmp18
				}
				_ = tmp19
				var tmp20 any
				if lang.IsTruthy(v8) {
					tmp20 = reflect.SelectSend
				} else {
					tmp20 = reflect.SelectRecv
				}
				// set! host field
				var tmp21 any
				{
					targetV := reflect.ValueOf(v17)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(tmp20)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp21 = tmp20
				}
				_ = tmp21
				var tmp22 any
				if lang.IsTruthy(v8) {
					// set! host field
					var tmp23 any
					{
						targetV := reflect.ValueOf(v17)
						if targetV.Kind() == reflect.Ptr {
							targetV = targetV.Elem()
						}
						fieldVal := targetV.FieldByName("Send")
						if !fieldVal.IsValid() {
							panic(fmt.Errorf("no such field Send"))
						}
						if !fieldVal.CanSet() {
							panic(fmt.Errorf("cannot set field Send"))
						}
						valV := reflect.ValueOf(v14)
						if !valV.IsValid() {
							switch fieldVal.Kind() {
							case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
								fieldVal.Set(reflect.Zero(fieldVal.Type()))
							default:
								panic(fmt.Errorf("cannot set field Send to nil"))
							}
						} else {
							fieldVal.Set(valV)
						}
						tmp23 = v14
					}
					tmp22 = tmp23
				} else {
				}
				_ = tmp22
				tmp3 = v17
			} // end let
			return tmp3
		})
		aotDirectFn11 = tmp1
		var_clojure_DOT_core_DOT_async_port_DASH_case = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion11 = var_clojure_DOT_core_DOT_async_port_DASH_case.RootVersion()
		var_clojure_DOT_core_DOT_async_port_DASH_case.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_port_DASH_or_DASH_put)), kw_doc, "Returns a *reflect.SelectCase for the given channel operation.", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(16), kw_column, int(8), kw_line, int(106), kw_end_DASH_line, int(106), kw_private, true)
		})
	}
	// try-put
	{
		tmp0 := sym_try_DASH_put
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "sc"
				tmp5 := var_clojure_DOT_core_DOT_async_port_DASH_case.RootVersion() == aotRootVersion11 && !var_clojure_DOT_core_DOT_async_port_DASH_case.IsMacro()
				var tmp6 any
				if !tmp5 {
					tmp6 = checkDerefVar(var_clojure_DOT_core_DOT_async_port_DASH_case)
				}
				tmp7 := lang.NewVector(v2, v3)
				tmp8 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(122), kw_column, int(23), kw_end_DASH_line, int(122), kw_end_DASH_column, int(32))
				tmp9, err := lang.WithMeta(tmp7, tmp8.(lang.IPersistentMap))
				if err != nil {
					panic(err)
				}
				var tmp10 any
				if tmp5 {
					tmp10 = aotDirectFn11(tmp9)
				} else {
					tmp10 = lang.Apply1(tmp6, tmp9)
				}
				var v11 any = tmp10
				_ = v11
				// let binding "def"
				tmp12 := var_clojure_DOT_core_DOT_async_default_DASH_case.RootVersion() == aotRootVersion6 && !var_clojure_DOT_core_DOT_async_default_DASH_case.IsMacro()
				var tmp13 any
				if !tmp12 {
					tmp13 = checkDerefVar(var_clojure_DOT_core_DOT_async_default_DASH_case)
				}
				var tmp14 any
				if tmp12 {
					tmp14 = aotDirectFn6()
				} else {
					tmp14 = lang.Apply0(tmp13)
				}
				var v15 any = tmp14
				_ = v15
				// let binding "vec__693"
				tmp16 := checkDerefVar(var_clojure_DOT_core_map)
				tmp17 := lang.NewVector(v11, v15)
				tmp18 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(124), kw_column, int(55), kw_end_DASH_line, int(124), kw_end_DASH_column, int(62))
				tmp19, err := lang.WithMeta(tmp17, tmp18.(lang.IPersistentMap))
				if err != nil {
					panic(err)
				}
				tmp20 := lang.Apply2(tmp16, lang.Builtins["deref"], tmp19)
				tmp21 := lang.Apply1(reflect.Select, tmp20)
				var v22 any = tmp21
				_ = v22
				// let binding "chosen"
				tmp23 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp24 := lang.Apply3(tmp23, v22, int64(0), nil)
				var v25 any = tmp24
				_ = v25
				// let binding "val"
				tmp26 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp27 := lang.Apply3(tmp26, v22, int64(1), nil)
				var v28 any = tmp27
				_ = v28
				// let binding "ok"
				tmp29 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp30 := lang.Apply3(tmp29, v22, int64(2), nil)
				var v31 any = tmp30
				_ = v31
				tmp32 := checkDerefVar(var_clojure_DOT_core__EQ_)
				tmp33 := lang.Apply2(tmp32, int64(0), v25)
				tmp4 = tmp33
			} // end let
			return tmp4
		})
		aotDirectFn13 = tmp1
		var_clojure_DOT_core_DOT_async_try_DASH_put = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion13 = var_clojure_DOT_core_DOT_async_try_DASH_put.RootVersion()
		var_clojure_DOT_core_DOT_async_try_DASH_put.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_port, sym_val)), kw_doc, "Returns true if val was sent on the port, false if sending would\n  block", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(14), kw_column, int(8), kw_line, int(118), kw_end_DASH_line, int(118), kw_private, true)
		})
	}
	// try-take
	{
		tmp0 := sym_try_DASH_take
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "sc"
				tmp4 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp5 := reflect.New(tmp4).Interface()
				var v6 any = tmp5
				_ = v6
				// let binding "_"
				// set! host field
				var tmp7 any
				{
					targetV := reflect.ValueOf(v6)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(reflect.SelectRecv)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp7 = reflect.SelectRecv
				}
				_ = tmp7
				tmp8 := reflect.ValueOf(v2)
				// set! host field
				var tmp9 any
				{
					targetV := reflect.ValueOf(v6)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Chan")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Chan"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Chan"))
					}
					valV := reflect.ValueOf(tmp8)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Chan to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp9 = tmp8
				}
				var v10 any = tmp9
				_ = v10
				// let binding "def"
				tmp11 := reflect.TypeOf((*reflect.SelectCase)(nil)).Elem()
				tmp12 := reflect.New(tmp11).Interface()
				var v13 any = tmp12
				_ = v13
				// let binding "_"
				// set! host field
				var tmp14 any
				{
					targetV := reflect.ValueOf(v13)
					if targetV.Kind() == reflect.Ptr {
						targetV = targetV.Elem()
					}
					fieldVal := targetV.FieldByName("Dir")
					if !fieldVal.IsValid() {
						panic(fmt.Errorf("no such field Dir"))
					}
					if !fieldVal.CanSet() {
						panic(fmt.Errorf("cannot set field Dir"))
					}
					valV := reflect.ValueOf(reflect.SelectDefault)
					if !valV.IsValid() {
						switch fieldVal.Kind() {
						case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice, reflect.UnsafePointer:
							fieldVal.Set(reflect.Zero(fieldVal.Type()))
						default:
							panic(fmt.Errorf("cannot set field Dir to nil"))
						}
					} else {
						fieldVal.Set(valV)
					}
					tmp14 = reflect.SelectDefault
				}
				var v15 any = tmp14
				_ = v15
				// let binding "vec__696"
				tmp16 := checkDerefVar(var_clojure_DOT_core_map)
				tmp17 := lang.NewVector(v6, v13)
				tmp18 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(138), kw_column, int(55), kw_end_DASH_line, int(138), kw_end_DASH_column, int(62))
				tmp19, err := lang.WithMeta(tmp17, tmp18.(lang.IPersistentMap))
				if err != nil {
					panic(err)
				}
				tmp20 := lang.Apply2(tmp16, lang.Builtins["deref"], tmp19)
				tmp21 := lang.Apply1(reflect.Select, tmp20)
				var v22 any = tmp21
				_ = v22
				// let binding "chosen"
				tmp23 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp24 := lang.Apply3(tmp23, v22, int64(0), nil)
				var v25 any = tmp24
				_ = v25
				// let binding "val"
				tmp26 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp27 := lang.Apply3(tmp26, v22, int64(1), nil)
				var v28 any = tmp27
				_ = v28
				// let binding "ok"
				tmp29 := checkDerefVar(var_clojure_DOT_core_nth)
				tmp30 := lang.Apply3(tmp29, v22, int64(2), nil)
				var v31 any = tmp30
				_ = v31
				var tmp32 any
				tmp33 := checkDerefVar(var_clojure_DOT_core__EQ_)
				tmp34 := lang.Apply2(tmp33, int64(1), v25)
				if lang.IsTruthy(tmp34) {
				} else {
					var tmp35 any
					if lang.IsTruthy(v31) {
						tmp36, ok := lang.FieldOrMethod(v28, "Interface")
						if !ok {
							panic(lang.NewIllegalArgumentError(fmt.Sprintf("no such field or method on %T: %s", v28, "Interface")))
						}
						var tmp37 any
						switch reflect.TypeOf(tmp36).Kind() {
						case reflect.Func:
							tmp37 = lang.Apply(tmp36, nil)
						default:
							tmp37 = tmp36
						}
						tmp38 := lang.NewVector(tmp37, true)
						tmp39 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(140), kw_column, int(14), kw_end_DASH_line, int(140), kw_end_DASH_column, int(36))
						tmp40, err := lang.WithMeta(tmp38, tmp39.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp35 = tmp40
					} else {
						tmp41 := lang.NewVector(nil, false)
						tmp42 := lang.NewMap(kw_file, "clojure/core/async.glj", kw_line, int(141), kw_column, int(17), kw_end_DASH_line, int(141), kw_end_DASH_column, int(27))
						tmp43, err := lang.WithMeta(tmp41, tmp42.(lang.IPersistentMap))
						if err != nil {
							panic(err)
						}
						tmp35 = tmp43
					}
					tmp32 = tmp35
				}
				tmp3 = tmp32
			} // end let
			return tmp3
		})
		aotDirectFn14 = tmp1
		var_clojure_DOT_core_DOT_async_try_DASH_take = ns.InternWithValue(tmp0, tmp1, true)
		aotRootVersion14 = var_clojure_DOT_core_DOT_async_try_DASH_take.RootVersion()
		var_clojure_DOT_core_DOT_async_try_DASH_take.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_arglists, lang.NewList(lang.NewVector(sym_port)), kw_doc, "Returns [val true] if val was received from the port, [nil false] if the channel was closed,\n  and nil if receiving would block.", kw_file, "clojure/core/async.glj", kw_ns, lang.FindOrCreateNamespace(sym_clojure_DOT_core_DOT_async), kw_end_DASH_column, int(15), kw_column, int(8), kw_line, int(127), kw_end_DASH_line, int(127), kw_private, true)
		})
	}
}
